### ISSUE TITLE
Remove "The Software shall be used for Good, not Evil" from license

### ISSUE THREAD

**Issue by xtreye** [miloyip/rapidjson#1000]
This statement is evil itself because eventually prevents from using the library in Spring Boot, a mainstream Java framework.

**Comment by miloyip** [comment]
That only due to JSON test suite. You can only use the include folder in your project and ignore those licenses.

**Comment by miloyip** [comment]
Wow, by the way, finally this is the #1000 issue.

**Comment by xtreye** [comment]
It is :1st_place_medal: 
Seriously, this is the reason Spring Boot maintainers can not include the implementation as default one and forced to use an outdated Android lib that lacks functionality: https://github.com/spring-projects/spring-boot/issues/9248

**Comment by miloyip** [comment]
You may tell them by removing those files, the license of that part can be removed.

**Comment by xtreye** [comment]
Thanks, hope this helps. Congrats with the anniversary again :)

**Comment by xtreye** [comment]
Sorry, I just found that this project is totally unrelated to the problem despite having the same "not evil" licence. Please remove this ticket. I feel silly.
