### ISSUE TITLE
HasParseError doesn't detect invalid documents

### ISSUE THREAD

**Issue by jcourtat** [miloyip/rapidjson#1001]
Hello,

Don't ask me how i went to find this issue but the result is interresting:
HasParseError("\\"@rx_message_dto.json\\"") doesn't return an error.
It then leads to segfault some methods later because the document object is garbage.

Here is my code
#include <iomanip>
#include <string>
#include <cstring>
#include <cstdint>
#include <iostream>
#include <cstdlib>
#include <sstream>

#include <rapidjson/document.h>     // rapidjson's DOM-style API
#include <rapidjson/prettywriter.h> // for stringify JSON

using namespace rapidjson;

void parse_rapidjson()
{
    char* json_doc = "\\"@rx_message_dto.json\\"";
    char* json_doc2 = "{\\"@rx_message_dto.json\\":2}";
    Document* document = new rapidjson::Document();
    if (document->Parse(json_doc).HasParseError()) {
        delete document;
        std::cerr << "Malformed json document" << std::endl;
    }
    else
        std::cout << "Document accepted !" << endl;
    Document* document2 = new rapidjson::Document();
    if (document2->Parse(json_doc2).HasParseError()) {
        delete document2;
        std::cerr << "Malformed json document" << std::endl;
    }
    else
        std::cout << "Document accepted !" << endl;
}

int main()
{
 parse_rapidjson();
 return 0;
}

output:
Document accepted !
Document accepted !

regards !

**Comment by miloyip** [comment]
These two are both valid JSON.

**Comment by jcourtat** [comment]
my apologies, i badly validated the document using a online tool.
