### ISSUE TITLE
Natvis file for Visual Studio

### ISSUE THREAD

**Issue by bmuzzin** [miloyip/rapidjson#1028]
https://docs.microsoft.com/en-gb/visualstudio/debugger/create-custom-views-of-native-objects

A visualizer for rapidjson would be very useful in debugging within Visual Studio. I have updated the one here: https://github.com/mojmir-svoboda/json.natvis. However, it might be useful if the updated version was put somewhere within the rapidjson repository itself (although, I'm not sure of the appropriate location for the file).

**Comment by miloyip** [comment]
How about storing it in the path `/contrib/natvis` with a readme in it?
