### ISSUE TITLE
Get memory usage for SAX parsing

### ISSUE THREAD

**Issue by foxtog** [miloyip/rapidjson#1029]
Is it somehow possible to get memory usage statistics when SAX parsing i.e. handler/reader functionality is used for parsing JSON file (string)?

**Comment by miloyip** [comment]
You need to create an allocator class with statistics functionality.
And then use it to construct a reader by:

~~~cpp
YourAllocator allocator;
GenericReader<YourAllocator> reader(&allocator);
reader.Parse(...);
~~~

Finally, you can obtain statistics from the allocator.

**Comment by foxtog** [comment]
Do I get it correctly that for DOM parsing the same is achieved by 
```
rapijdson::Document document;
auto allocatedBytes = document.getAllocator().Capacity() + document.GetStackCapacity(); 
```
?

**Comment by foxtog** [comment]
With my gcc 4.8.4 I get the following compilation error:

>  error: ‘pcx::rapidjson::Reader {aka pcx::rapidjson::GenericReader<pcx::rapidjson::UTF8<>, pcx::rapidjson::UTF8<> >}’ is not a template
>          rapidjson::Reader<RapidjsonCustomAllocator> jsonReader;

**Comment by miloyip** [comment]
Yes, when using the default allocator.

**Comment by foxtog** [comment]
Thank you!
