### ISSUE TITLE
How to store parsed JSON objects in a map

### ISSUE THREAD

**Issue by schmidt9** [miloyip/rapidjson#1031]
Hello
I'd like to store parsed JSON objects in a static map to access it later and not to parse it again, is it possible? Private constructor doesn't allow to store `Document` objects, and their references get invalid after return.

```
typedef rapidjson::Document Json;

static std::unordered_map<size_t, JsonParser::Json&> mJsonMap;
static std::hash<std::string> hashFn;

    JsonParser::Json&
    JsonParser::parse(std::string jsonString)
    {
        size_t hash = hashFn(jsonString);
        
        if (mJsonMap.count(hash) == 0) {
            JsonParser::Json json;
            json.Parse(jsonString.c_str());
            mJsonMap.insert({hash, json});
        }
        
        return mJsonMap.at(hash);
    }
```

**Comment by Bu11etmagnet** [comment]
Try compiling with `-std=c++11`. This will hopefully turn on `RAPIDJSON_HAS_CXX11_RVALUE_REFS`.

**Comment by schmidt9** [comment]
@Bu11etmagnet unfortunately it did not help.
returning from above routine...
```
        std::ifstream file(mResourcePath.c_str());
        auto json = &JsonParser::parse(file);

        printf("%i\n", RAPIDJSON_HAS_CXX11_RVALUE_REFS); // is 1
        StringBuffer sb;
        PrettyWriter<StringBuffer> writer(sb);
        (*json).Accept(writer); // !!! crash
```

**Comment by schmidt9** [comment]
[Crash screenshot here](https://ibb.co/gFqsKk)

**Comment by miloyip** [comment]
I think you will need rvalue reference to make that work.
If you are not familiar with C++11, you may just use pointer `std::map<size_t, rapidjson::Document*>` instead. But you need to take care of `new` and `delete`.

**Comment by schmidt9** [comment]
@miloyip could you please show me how to use rvalue reference in this case especially using map? (`return mJsonMap.at(hash);`), I'm not so skilled at C++ yet :/

**Comment by miloyip** [comment]
~~~cpp
#include <iostream>
#include <map>
#include <string>
#include "rapidjson/document.h"

using namespace rapidjson;

Document f(const std::string& json) {
    Document d;
    d.Parse(json.c_str());
    return d;
}

int main() {
    std::map<int, Document> m;
    m.insert(std::make_pair(42, f("{\"a\" : 123 }")));
    m.insert(std::make_pair(43, f("{\"a\" : 246 }")));
    std::cout << m[42]["a"].GetInt() << std::endl;
    std::cout << m[43]["a"].GetInt() << std::endl;
}
~~~

**Comment by schmidt9** [comment]
@miloyip thanks but how can I return Document stored in the map?

```
        rapidjson::Document f(const std::string& json) {
        rapidjson::Document d;
        d.Parse(json.c_str());
        return d;
    }
    
    rapidjson::Document returnFromMap(const std::string& json)
    {
        rapidjson::Document d = f("{\"a\" : 123 }");
        d.Parse(json.c_str());
        
        std::unordered_map<size_t, rapidjson::Document> m;
        m.insert({43, d});
        
        return m.at(43); // error
    }
```
Error message
`Calling a private constructor of class 'rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>'`

**Comment by miloyip** [comment]
Returning a reference or const reference is possible.
~~~cpp
    Document& d1 = m[42];
    const Document& d2 = m[43];
~~~

**Comment by schmidt9** [comment]
@miloyip it seems we returned to beginning, where I had `malloc: *** mach_vm_map(size=1638846464) failed (error code=3) *** error: can't allocate region *** set a breakpoint in malloc_error_break to debug` after return

```
    rapidjson::Document& returnFromMap()
    {
        const char *str = "{\"a\" : 123 }";
        rapidjson::Document d;
        d.Parse(str);
        std::unordered_map<size_t, rapidjson::Document& > m;
        m.insert({43, d});
        
        return m.at(43);
    }
```
and then  
```
auto &d = returnFromMap(); 
d.Accept(...); // crash here just like before
```

**Comment by schmidt9** [comment]
By the way we cannot return `m[43]`, only `m.at(43)` works

**Comment by miloyip** [comment]
Your `map` object `m` was destroyed at the end of that function...

**Comment by schmidt9** [comment]
@miloyip but the same occurs if I declare this map as static, I suppose static map shouldn't be destroyed, or  is it wrong?

**Comment by miloyip** [comment]
You should use `std::unordered_map<size_t, rapidjson::Document>` instead of `std::unordered_map<size_t, rapidjson::Document& >` if you want to store the document in the map.

**Comment by schmidt9** [comment]
In this case I get `Calling a private constructor...`. Anyway, I finally stopped at your earlier advice to use pointers, thanks for your help and for your parser, it is really very fast.

**Comment by Bu11etmagnet** [comment]
@schmidt9 
If you return a `rapidjson::Document` from a function, you are not returning the object from the map; you are returning a copy. Unfortunately, Document objects can't be copied.
Perhaps your best bet is to make a `map<size_t, std::unique_ptr<rapidjson::Document>>`. This will take care of cleaning up automatically.

**Comment by schmidt9** [comment]
@Bu11etmagnet please look at it
So how can I use `std::unordered_map<size_t, rapidjson::Document>`?
```
    rapidjson::Document returnFromMap()
    {
        static std::unordered_map<size_t, rapidjson::Document> m;
        const char *str = "{\"a\" : 123 }";
        rapidjson::Document d;
        d.Parse(str);
        m.insert({43, d});
        
        return m.at(43); // Getting Calling a private constructor... here
    }
```

**Comment by Bu11etmagnet** [comment]
@schmidt9 
You can use `std::unordered_map<size_t, rapidjson::Document>`, you just can't return a `rapidjson::Document` from a function. You need to return a reference (which runs the risk of becoming dangling if the map element (or the entire map) is destroyed).

Note that I recommended  `map<size_t, **std::unique_ptr**<rapidjson::Document>>` but you can use `unordered_map<size_t, **std::unique_ptr**<rapidjson::Document>>` in the same fashion.

**Comment by schmidt9** [comment]
@Bu11etmagnet ah sorry I did not notice `unique_ptr` part in your proposal... I'll give a try, since I'm not going to destroy stored `Document`s.

**Comment by schmidt9** [comment]
@Bu11etmagnet I cannot manage returning right result, it gives me error `No viable conversion from returned value of type 'rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>' to function return type 'std::unique_ptr<rapidjson::Document>' (aka 'unique_ptr<GenericDocument<UTF8<> > >')`

```
    std::unique_ptr<rapidjson::Document> returnFromMap()
    {
        static std::unordered_map<size_t, std::unique_ptr<rapidjson::Document>> m;
        const char *str = "{\"a\" : 123 }";
        auto *d = new rapidjson::Document();
        d->Parse(str);
        m.insert({43, std::unique_ptr<rapidjson::Document>(d)});
        return *m.at(43); // how to return??
    }
```

**Comment by Bu11etmagnet** [comment]
`std::unique_ptr<rapidjson::Document> returnFromMap()` (returning unique_ptr by value) won't work because the only way it would work would be to take away the Document from the map.
It could work if you used `std::shared_ptr` instead of `std::unique_ptr` in my example.

Anyway, your line `return *m.at(43); // how to return??` is incorrect because your map contains `unique_ptr` objects. `m.at()` returns you a `unique_ptr`. When you use `operator*`, you no longer have a `unique_ptr` but a Document (which you cannot assign to a `unique_ptr`).
You should remove the * from the `m.at(43)` line **and** change the return type of the function to `std::unique_ptr const&` . This should compile (I don't have a compiler handy right now).

**Comment by schmidt9** [comment]
@Bu11etmagnet this way I get error message while compiling `Call to implicitly-deleted copy constructor of 'std::__1::pair<const unsigned long, std::__1::unique_ptr<rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>, std::__1::default_delete<rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> > > >'`

```
    std::unique_ptr<rapidjson::Document> const& returnFromMap()
    {
        static std::unordered_map<size_t, std::unique_ptr<rapidjson::Document>> m;
        const char *str = "{\"a\" : 123 }";
        auto *d = new rapidjson::Document();
        d->Parse(str);
        m.insert({43, std::unique_ptr<rapidjson::Document>(d)});
        return m.at(43);
    }
```

**Comment by schmidt9** [comment]
To end this long discussion - I stopped at advice of @miloyip 

> you may just use pointer std::map<size_t, rapidjson::Document*> instead

**Comment by nestoroprysk** [comment]
```shared_ptr``` is a way better option than ```*``` (and it works)
