### ISSUE TITLE
How to print an Object?

### ISSUE THREAD

**Issue by schmidt9** [miloyip/rapidjson#1035]
Hello
I'm able to print a `Document` using this code
```
void 
JsonParser::print(rapidjson::Document &json)
    {
        using namespace rapidjson;
        
        StringBuffer sb;
        PrettyWriter<StringBuffer> writer(sb);
        json.Accept(writer);
        auto str = sb.GetString();
        printf("%s\n", str);
    }
```
However I did not find how to print just one `Object` from s `Document`
I tried this, but this code seems to modify my object and I cannot find values there afterwards.
```
        rapidjson::Document json;
        json.Set(object);
        print(json); // pass to the above routine
```

**Comment by miloyip** [comment]
Change
~~~
void JsonParser::print(rapidjson::Document &json)
~~~
To
~~~
void JsonParser::print(const rapidjson::Value &json)
~~~

`const` is optional but better.

**Comment by schmidt9** [comment]
@miloyip thanks I'll check ASAP

**Comment by Srythuutr** [comment]
.Set() does not exist.

**Comment by asn10038** [comment]
I also ran into the Set doesn't exist issue. 

In case anyone runs into this again. I fixed with this SO post
https://stackoverflow.com/questions/13200191/stringify-with-rapidjson
