### ISSUE TITLE
Core dump for some cases

### ISSUE THREAD

**Issue by chenglongwei** [miloyip/rapidjson#1037]
I am using version of 1.0.2 and sometimes my code has core dump. The following is how my code looks like. Could anyone help to see whether my code has some memory issue?

~~~cpp
// Global variables.
rapidjson::Document *document = new rapidjson::Document();
document->SetObject();

rapidjson::Value messages(rapidjson::kArrayType);

// Called several times to add messages.
void record() {
    rapidjson::Value message(rapidjson::KObjectType);
    
    {
        rapidjson::Value sub1(rapidjson::KObjectType);
        .... // AddMember(...);
        rapidjson::Value sub1Union(rapidjson::KObjectType);
        sub1Union.AddMember("sub1Union", sub1, document->GetAllocator());
        message.AddMember("sub1", sub1Union, document->GetAllocator());
    }
    
    messages.PushBack(message, document->GetAllocator());
}

// Serialize to string
void serialize() {
    // local document for serialization.
    rapidjson::Document d;
    d.SetObject();
    d.AddMember("field1", "value1", document->GetAllocator());
    d.AddMember("messages", messages, document->GetAllocator());
    
    rapidjson::StringBuffer sb;
    rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
    d.Accept(writer); // core dump here
    string jsonMessages = buffer.GetString();
}
~~~

**Comment by miloyip** [comment]
It will be better for us to investigate if you can provide a minimal, reproducible example code.

**Comment by chenglongwei** [comment]
I am sorry but the code in production is complex that it is not easy provide a reproducible code.
Last line of `void record()`, do you think `messages.PushBack()` a stack object `rapidjson::Value message` may have some problem? In `void serialize()`, I use that object to serialize a string.

**Comment by miloyip** [comment]
From the code I can hardly realize the reason for the core dump.
But ideally you should use the same allocator in a document.

**Comment by sumory** [comment]
```
rapidjson::StringBuffer sb;
rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
d.Accept(writer); // core dump here
```

i got a similar core dump with version 1.1.0

**Comment by miloyip** [comment]
Is this happen on particular document? platform?

**Comment by sumory** [comment]
only happen in some particular cases on Debian 8. 
the origin data is protobuf format, i'll check whether the pb data is illegal or maybe i didn't use rapidjson in a right way.

**Comment by miloyip** [comment]
I hope that a minimal reproducible example can be provided. Otherwise it may be difficult for us to diagnose.

**Comment by sumory** [comment]
i found the reason caused core dump: i used another `allocator` in the sub method which return part of `rapidjson::Document` object.

**Comment by chenglongwei** [comment]
@miloyip If the same `allocator` is used in different threads, is this may cause the issue? For my code sniper, there may be multi-threads to call `record()` and `serialize()` and use the same `allocator` from `global document`.

**Comment by miloyip** [comment]
@chenglongwei Allocators provided cannot be used in multiple threads at the same time!

**Comment by chenglongwei** [comment]
@miloyip Yes, I already verified the issue. I will deploy and test in production environment.

**Comment by chenglongwei** [comment]
I verified in Production. We can close this issue. Thanks.
