### ISSUE TITLE
how to use the same document's memory allocator for parsing multiple times

### ISSUE THREAD

**Issue by hhzrz** [miloyip/rapidjson#1041]
Hey guys, i'm new to rapidjson library, and i've read rapidjson's documentations carefully.
but still, I have a problem when using rapidjson.
the following is the demonstration code which cause problem.

```c++
#include <iostream>
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include <vector>

using namespace std;
using namespace rapidjson;

// just for debug
string rapidjsonValueToString(const Value& value) {
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    value.Accept(writer);
    string str(buffer.GetString(), buffer.GetLength());
    return str;
}

// parse
Document parse(const string& str, MemoryPoolAllocator<>& ma) {
    Document doc(&ma);
    doc.Parse(str.c_str(), str.size());
    return doc;
}

int main() {
    string string1("{\"k1\":\"v1\"}");
    string string2("{\"k2\":\"v2\"}");
    string string3("{\"k3\":\"v3\"}");
    vector<string> vec{string1, string2, string3};

    Document doc;
    for (const auto& str : vec) {
        doc = parse(str, doc.GetAllocator());  // here will cause SIGSEGV error in the second loop
        std::cerr << "doc : " << rapidjsonValueToString(doc) << std::endl;
    }
    std::cerr << "doc : " << rapidjsonValueToString(doc) << std::endl;

    return 0;
}
```

My problems are:
1. From rapidjson's documentation, for saving memory reallocation for a new Document, and avoiding copying/deepCopy json Values between two different documents, I need to use the same Document's memory to do everything related. Am i right?
2. As commented in the code, `doc = parse(str, doc.GetAllocator());` this snippet will cause segment fault error in the second time when `str = string2`, could you please tell me why?

Thanks in advance!

**Comment by hhzrz** [comment]
I guess i've got to know the reason about the problem 2:
- This assignment operator `=` from `parse` to `doc`, cause the `doc` to call the destructor `Destroy()`https://github.com/miloyip/rapidjson/blob/f05edc9296507a9864d99931e203631c2ffd8d4a/include/rapidjson/document.h#L2156
so after this, our `doc` has no memory allocator.
so the next time invoking `doc = parse(str, doc.GetAllocator());` which will use the previous memory allocator will cause segment fault error.

**Comment by miloyip** [comment]
Yes. You should not assign to the `doc` which destroys the allocator in it.
But I am not sure why you need this. Why not just simply `doc.Parse(json)`?

**Comment by hhzrz** [comment]
@miloyip , Thanks for your reply.
Yes, You are right.
I just want to use the same document's memory allocator for parse multiple times, and avoid copy operations as possible.
