### ISSUE TITLE
Why Can't I use the GetAllocator of a const document

### ISSUE THREAD

**Issue by eclan** [miloyip/rapidjson#1053]
Here is an extract of my code.

void fill_tree(const rapidjson::Document& json_data)
```
{
	rapidjson::rapidjson::Document::AllocatorType& alloc = json_data.GetAllocator();
        
        rapidjson::Value selected_fields;
	selected_fields.SetArray();
	for (auto& field : json_data["fields"].GetArray()) {
		if (field["select"].GetBool()) {
			rapidjson::Value val(field, alloc);
			selected_fields.GetArray().PushBack(val, alloc);
		}
	}
[...]
}
```

I get this error message at compile time.

```
error: passing ‘const Document {aka const rapidjson::GenericDocument<rapidjson::UTF8<> >}’ as ‘this’ argument of ‘Allocator& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::GetAllocator() [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]’ discards qualifiers [-fpermissive]
```

I don't find in the document the way to use an allocator for a const rapidjson::document. 

Your help will be valuable to me. Thank you.

**Comment by miloyip** [comment]
Since the allocator is owned by `Document`, if the `Document` is const, it shall not return a non-const allocator.

If you need to modify `json_data`, why shouldn't it be non-const? Or you can pass an non-const allocator to the function.

**Comment by eclan** [comment]
Ok thank you for your answer. 

I was wondering if two documents can share the same allocator or if one could use the allocator of one document (json_data) to manipulate another rapidjson::Value item (selected_fields). That's what I'm trying to do here.

json_data is const but selected_fields is not.

 What do you think ?
