### ISSUE TITLE
MessagePack/msgpack support

### ISSUE THREAD

**Issue by spl** [miloyip/rapidjson#143]
I'm looking at evaluating RapidJSON for JSON encoding/decoding (via the SAX interface, in particular). I'm very happy with the level of documentation. You seem to be actively developing, too, unlike a number of other libraries. Thanks!

In addition to JSON, I will soon need MessagePack encoding/decoding (also via a SAX interface). I wanted to find out what the RapidJSON developers thought about adding support for encoding/decoding MessagePack?

Here are a couple thoughts:

* Can RapidJSON support MessagePack seamlessly with JSON?
  * Can the same reader handler and writer types be used? Or, perhaps, they can be extended to support some features of MessagePack not in JSON.
  * Can RapidJSON read in JSON and write out MessagePack, and vice versa?

I'm interested enough that I can contribute code to this. Would the RapidJSON developers be willing to accept it and help out?

**Comment by miloyip** [comment]
I think controlling the versioning of such sub-projects is quite inconvenient. I think some code snippet that enhances RapidJSON itself but do not want to put into the main source code can put into `contrib` area. If that code is not depending on other thirdparty, it will be OK.

But currently I added https://github.com/miloyip/rapidjson/wiki/Related-Projects for showing related project.

I am welcome to have PR or discussion if there is some works done on this and would put into this repository.
