### ISSUE TITLE
Default Value?

### ISSUE THREAD

**Issue by liuyanghejerry** [miloyip/rapidjson#151]
I'm new to rapidjson, and wondering is it possible to have default values?
example:

document.HasMember("hello") // say false
document["hello"].GetString() // since document doesn't contain hello, it returns an empty string.
document["another_hello"].GetInt64() // since document doesn't contain another_hello, it returns 0.
document["another_hello"].GetInt64(12) // or even better, default value provided by user

Possible? Any plans?

**Comment by miloyip** [comment]
I think #297 should be a better solution. So I close this.
