### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by ashkan2200** [miloyip/rapidjson#153]
Hi,
I would like to suggest two improvements to rapidJson
1. Support c/c++ type comment in JSON file. It would be very beneficial if one can have comments in the JSON file.
2. A generic method that gets a type argument and converts the value to that argument type. i.e.
doc["key"]->Get < int > ();

Thank you,
Ashkan

**Comment by miloyip** [comment]
I added #316 for the second point, in order to replace this issue.
