### ISSUE TITLE
Parser fails on valid JSON

### ISSUE THREAD

**Issue by mj2015** [miloyip/rapidjson#155]
According to jsonlint.com this is valid JSON, but it fails to be parsed by rapidjson with a kParseErrorStringMissQuotationMark error status. Yes, it's a little odd having empty values, but it's what my test system generated.

{"events":[{"eventname":"Tuesday","runners":[{"runnername":"Jon","time":"14:10"},{"runnername":"165886"},{"runnername":"Fred"}]},{"eventname":"","runners":[{"runnername":""}]}],"runnercount":3}

**Comment by tphauvlvl1991** [comment]
Thank you so much! It is very helpful
