### ISSUE TITLE
Parse non-null-terminated strings / Parse with std::string

### ISSUE THREAD

**Issue by spl** [miloyip/rapidjson#158]
I would like to parse strings that are not null-terminated but do have a string length.

What's the best way to do that now? Implement the `Stream` concept? I guess it would involve something like copying the `GenericStringStream`, adding a length-remaining member, and modifying `Peek()` to return `'\0'` when the end is reached.

I think this would be useful for RapidJSON in general. It could be exposed as overloaded `Parse(const Ch *, size_t)` and `ParseInsitu (Ch *, size_t)` methods.

**Comment by miloyip** [comment]
I am OK for PR for supporting `Parse(std::string)`.
That may be put in v1.1 Beta.

**Comment by jmrico01** [comment]
> This doesn't work with `ParseInsitu` yet or does it?

+1 ! I don't think it does - `MemoryStream` doesn't support the required write ops. Maybe we need an `InsituMemoryStream`?
