### ISSUE TITLE
Raise exception by default

### ISSUE THREAD

**Issue by ltworf** [miloyip/rapidjson#160]
By default the library crashes on malformed input.

This commit is for a fork of this library but can be easily adapted.

I think it would be a better behaviour.

https://github.com/ltworf/rapidjsonxml/commit/4fa8e58d7575dc8dc412c0651e93ec079f9ed1e3

It wouldn't change custom defined behaviours, just the default.

**Comment by jack155** [comment]
I want to know how to catch a exception when use doc.Parse(cJSON) or  doc.HasMember ?  when I pass the CJON a simple string  ,it crashed and can not be catched by my try-catch

**Comment by marciobarcellos** [comment]
> I want to know how to catch a exception when use doc.Parse(cJSON) or doc.HasMember ? when I pass the CJON a simple string ,it crashed and can not be catched by my try-catch

Same here

**Comment by pah** [comment]
> I want to know how to catch a exception when use doc.Parse(cJSON) or doc.HasMember ? when I pass the CJON a simple string ,it crashed and can not be catched by my try-catch

See my https://github.com/Tencent/rapidjson/issues/160#issuecomment-58946238 above.  In https://github.com/pah/rapidjson-upstream/commit/f4a1b55cab you can find an example to configure RapidJSON to throw an exception on parse errors.

**Comment by pah** [comment]
Even better: The customization point is documented [here]( http://rapidjson.org/group___r_a_p_i_d_j_s_o_n___e_r_r_o_r_s.html#ga7f8c4265b2edda78568ae3338aaf1461).

**Comment by Kleenox** [comment]
Just to add my two cents, please don't add exceptions to this library, we are in the process of migrating a large codebase from jsoncpp to rapidjson precisely because rapidjson doesn't use exceptions. The use of exceptions by jsoncpp was incredibly frustrating.
