### ISSUE TITLE
Support C++11 range-based loop

### ISSUE THREAD

**Issue by drewnoakes** [miloyip/rapidjson#162]
Currently the `for(auto item& : myValue)` loop is not supported by rapidjson. I guess this is because the case of `Begin` and `End` does not match what the standard expects.

I'd like to use this for array iteration, though I suspect it could also be useful over members as well.

**Comment by weepy** [comment]
+1

**Comment by evil-jester** [comment]
+1

**Comment by miloyip** [comment]
@pah Your idea of `GetArray()`/`GetObject` has been implemented in PR #542 .
Please review the PR when you have time. Thank you.

**Comment by miloyip** [comment]
Merged #542

**Comment by kklouzal** [comment]
As mentioned in the first post, the capitalization of `B` and `E` on `Begin()` and `End()` functions are preventing auto ranged based for looping. for `(auto Val : Doc)`.

I've attempted to change them to lowercase myself however at that point the compiler starts telling you you're trying to access private/protected member functions when you shouldn't be..

**Comment by pah** [comment]
Two things to note here:

* You can use `GetArray()/GetObject()` functions to use range-based `for` over arrays or objects:
* As RapidJSON value are generally not copyable, you should loop over **references** instead

```cpp
  Document doc;
  // ... fill the array
  for( const auto& e : doc.GetArray() ) // loop over array
     std::cout << e.GetInt() << std::endl;

  // ... fill an object
  for( auto& m : doc.GetObject() ) // loop over object (non-const)
    m.value.SetNull(); // modify entry 
```
