### ISSUE TITLE
[enhancement] Sparse parsing shouldn't consume too much memory

### ISSUE THREAD

**Issue by yurivict** [miloyip/rapidjson#182]
I observe this problem: The program parses large 1GB json, which consists of 400-element equally-sized array at the top level. Program only looks at the first element (~1/400th of the document), but the memory usage jumps by 10GB. Later, when subsequent elements are looked at, memory grows further, which is expected.

I am not sure if this is doable, but for such situation 'sparse' option would be beneficial. In order to parse the first element of the array, rapidjson doesn't even have to look past that element's closing bracket. 

But that 10GB initial memory usage seems to indicate that rapidjson does parse the whole json to some degree right away.

So I suggest the 'sparse' option that would only parse the parts that the program actually requests and skip over the rest.

**Comment by miloyip** [comment]
I think http://stackoverflow.com/questions/28391434/how-to-parse-bigdata-json-file-wikidata-in-c-efficiently/28403323 is similar to this issue. And I cannot think of good solution for RapidJSON to handle this. So I close this issue.

**Comment by Sarev0k** [comment]
Have you seen Jackson's streaming parser APIs?  [This article](http://www.ngdata.com/parsing-a-large-json-file-efficiently-and-easily/) describes how Jackson's streaming API makes it possible to skip entire objects trees that the processing code of a large JSON file isn't interested in parsing, and parsing the portions of the JSON file it is interested in, into a DOM.

Conceivably, RapidJSON could allow you to follow a similar pattern.  Here's an example of what that experience might look like:
```c++
FILE* fp = fopen("big.json", "rb");

char readBuffer[65536];
FileReadStream is(fp, readBuffer, sizeof(readBuffer));
Parser parser(is);

// move past the start of the root token
parser.NextToken();

while (parser.NextToken() != Token.END_OBJECT)
{
    const char* fieldName = parser.GetText();
    parser.NextToken();
    if (isInterestingField(fieldName))
    {
        // Parses the value at the current position
        // and automatically advances the parser to
        // the start of the token at the current level.
        Value value = parser.ParseValue();
        // Business logic using completely parsed
        // value goes here.
    }
    else
    {
        // Skips all child tokens of the current object
        // or array and advances parser to the
        // corresponding end token.  If the current token
        // is not Token.START_OBJECT or Token.START_ARRAY,
        // this call does nothing.
        parser.SkipChildren();
    }
}

fclose(fp);
```

I believe an API like that described above would allow RapidJSON to sparsely parse large JSON files more elegantly.

@miloyip what do you think?

**Comment by miloyip** [comment]
During development of JSON Schema, we have added an API in `Document`:

~~~
    //! Populate this document by a generator which produces SAX events.
    /*! \tparam Generator A functor with <tt>bool f(Handler)</tt> prototype.
        \param g Generator functor which sends SAX events to the parameter.
        \return The document itself for fluent API.
    */
    template <typename Generator>
    GenericDocument& Populate(Generator& g) {
~~~

It is possible to do filtering in SAX event, and then passed the filtered events to document to construct a DOM.

However, SAX parser in RapidJSON did not separate tokenization and parsing. All input will be parsed. Some parsing routines are quite expensive, such as parsing numbers, and they cannot be skipped.

Therefore, currently RapidJSON can support filtering for constructing a subset of a JSON into DOMs, but it cannot prevent parsing of unused portions in JSON.

**Comment by akki401** [comment]
Hello miloyip,
Thanks for your support.
I started analyzing the This parser and i love it.
I have a query
can RapidJson parse,edit and write more than 1GB size of json file?
what is the max size input data limitation of RapidJson  can handle ?
