### ISSUE TITLE
Weird issue on Android (Document's allocator set to 0 at first time)

### ISSUE THREAD

**Issue by dcracker** [miloyip/rapidjson#200]
NDK: Android NDK, Revision 10c 
OS: Android 4.1.2
IDE: Eclipse Luna (4.4.0)
rapidjson: master (2014/11/19)

I tested very simple function call with Android NDK.

1. App started.
2. Press back button. (I set the native function call trigger with back button.)
3. Then call a native function, use rapidjson library.
4. Document's allocator is 0
5. Press back button again (call a native function again)
6. Document has allocator (it's good, and expected behavior.)
7. now everything fine. Until restart the app.

---- add tested function ----
native function (just 3 lines + log)

JNIEXPORT void JNICALL Java_~~~~~~~~_Tester_testing( JNIEnv* env, jobject thiz )
{
    rapidjson::Document json;
    json.SetObject();
    rapidjson::Document::AllocatorType& allocator = json.GetAllocator();
    LOGD( "allocator:::%p", &allocator );
}

Issue: I think allocator set slowly(?)

I'm not sure this is an issue. Did I something wrong to use this library?

---- add comments ----
with same library, iOS/Windows apps are OK.

**Comment by niekbouman** [comment]
I also observed a segfault when running my program  (which uses a rapidjson Document) after compiling with cmake's release-optimisation flags (by setting -DCMAKE_BUILD_TYPE=Release, among other things, this enables -O3 optimisations) for an ARMv7-A Cortex A9 with GCC 4.9.2-10.

Pah's suggestion, i.e., 
  `typedef rapidjson::GenericDocument<rapidjson::UTF8<>,rapidjson::CrtAllocator> Document;`
solved the problem for me.
