### ISSUE TITLE
Json validation

### ISSUE THREAD

**Issue by justgook** [miloyip/rapidjson#210]
there is special syntax to check data http://json-schema.org
would be nice have that feature in rapidjson

**Comment by KarelJakubec** [comment]
:+1: 
Hi,
this would be really usefull feature. I found no c++ json parser which could do this and I really like the idea to have a lib which can do both parsing and validating.

@justgook Have you made any progress so far? If so, maybe I could contribute.

@miloyip Are there any plans when the 1.0 release will occur?

**Comment by miloyip** [comment]
1.0 release will be soon. Probably March.
I am finalizing the documents.
Also, the build system was changed to CMAKE recently. It may need some time to be stabilized.

**Comment by miloyip** [comment]
I added an issue #326 for tacking the implementation progress of JSON Schema.
