### ISSUE TITLE
Add support for JSONB (binary JSON)

### ISSUE THREAD

**Issue by Adriatic1** [miloyip/rapidjson#211]
To save packet size transmission costs, it would be nice to have support for JSONB  (binary JSON)

**Comment by patlecat** [comment]
It seems that this implementation offers a C++ 03 header-only file. Would that be an option?
https://github.com/msgpack/msgpack-c

**Comment by miloyip** [comment]
For bridging between RapidJSON and msgpack-c, @xpol has provided https://github.com/xpol/xchange
RapidJSON shall not support other formats directly. But recently, an example of [jsonx](https://github.com/miloyip/rapidjson/blob/master/example/jsonx/jsonx.cpp) (JSON to a XML format) is provided. Similar things may be provided as examples also.
I close this anyway.
