### ISSUE TITLE
c++11 integration

### ISSUE THREAD

**Issue by reuk** [miloyip/rapidjson#212]
At the moment, if I try to use a c++11 style for loop (for each key in an object, or for each item in an array) on a rapidjson Value, I get a compiler error telling me that there's no viable 'begin' function:

    /Users/reuben/dev/parallel_raytrace/cmd/main.cpp:244:29: error: invalid range expression of type 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >'; no viable 'begin' function available
        for (const auto & i : v)

How simple would it be to make this work? Seems to me it'd just be a case of adding `begin` and `end` members which inline down to the existing `Begin` and `End` ones.

Is C++11 compatibility one of the goals of this library? That is, can I ever expect this to work, or should I just use old-style `for (auto i = v.Begin(); i != v.End(); ++i)`?

**Comment by miloyip** [comment]
Done in #542
