### ISSUE TITLE
Add AppVeyor CI support to continuously test RapidJSON on Windows

### ISSUE THREAD

**Issue by pah** [miloyip/rapidjson#225]
Similar to Travis CI, [AppVeyor](http://ci.appveyor.com) allows running CI tests integrated with GitHub repositories on MS Visual Studio on Windows for free (for open-source projects).

We should consider adding a configuration to RapidJSON as well in order to cover this platform, too.

**Comment by miloyip** [comment]
This sounds great. Do you have experienced on that as well?

**Comment by pah** [comment]
I've not yet used the service, but according to their documentation, it looks quite similar to the Travis CI setup. As we don't need to generate the documentation there, it may be quite simple to set this up.

**Comment by pah** [comment]
See pull-request #242 for an integration proposal.
