### ISSUE TITLE
Xlib messes up rapidjson

### ISSUE THREAD

**Issue by alexpana** [miloyip/rapidjson#231]
Hello,

Xlib.h uses ``#define Bool int`` which messes up all methods called Bool. I can only avoid this by carefully including rapidjson headers before Xlib.h

Any tips for a better solution?

**Comment by miloyip** [comment]
I can just think of:

~~~cpp
#pragma push_macro("Bool")
#undef Bool
#include "rapidjson/..."
#pragma pop_macro("Bool")
~~~

Ideally, it would be better to compile .cpp that include rapidjson and not mix with other libraries.
