### ISSUE TITLE
warning : comparison is always true

### ISSUE THREAD

**Issue by MrLonko** [miloyip/rapidjson#243]
there are three locations that produce this in gcc 3.3.4 with -Wall.

We solved it simply by replacing:
        if (sizeof(Ch) == 1 || unsigned(c) < 256)
            return (Token)tokenMap[(unsigned char)c];
        else
            return NumberToken;

To:

	const unsigned long warningResolver = static_cast<unsigned long> (c);
	if (sizeof(Ch) == 1 || warningResolver < 256)
            return (Token)tokenMap[(unsigned char)c];
        else
            return NumberToken;

Can you please add this to the source, so that the anoying warning goes away...

Otherwise EXCELENT UTILITY!

BR,

**Comment by miloyip** [comment]
Have you checked that if this would incur overhead? (e.g. checking the generated assembly)
I can think of using template, or just using pragma to solve it.

**Comment by MrLonko** [comment]
What do you mean by overhead?

Br,

**Comment by miloyip** [comment]
By using optimization, the whole `if()` should have been eliminated  in compile-time if `sizeof(Ch) == 1`. I think your changes should be OK, not affecting this situation.

**Comment by MrLonko** [comment]
Excelent, leaving it in.

Do have another question. Would insitu parsing be possible and safe on std::string without copying it into a temp buffer? 

Otherwise GOOD JOB! On our ARMv5 embedded device rapidjson works instant, where others like jsoncpp needed 500ms+ or more...

**Comment by drewnoakes** [comment]
I believe in situ parsing of a std::string's .data() char* is fine (I
certainly do it). Obviously the string must not be freed so long as the
Document and its contents remain in use.

**Comment by miloyip** [comment]
However, `data()` returns `const char*` which cannot be used for writing directly. According to the standard, writing into that buffer results in undefined behavior.

**Comment by MrLonko** [comment]
Hmm... Why is there a need to write into the buffer at all ?
I mean most of people probably do:
		char* charcast = const_cast<char*>(response.c_str());
		rapidjson::Document d;
		if(d.ParseInsitu(charcast).HasParseError())
		{
			//handle error;
		}
now the question would be is this really a bad thing? 
miloyip, do you have somewhere some test suite, so i can test on our board, to see the speeds:
1. direct parse
2. insitu
3. copy to temp buff and insitu.
4. asign to vector and insitu.

I have an armv5 board which is excelent for this as it really shows the difference in small changes.

BR,

**Comment by miloyip** [comment]
Insitu-parsing needs to write to the buffer for:
1. Appending '\0' at the end
2. Replacing escape characters

For doing performance tests, you may try to run https://github.com/miloyip/nativejson-benchmark
