### ISSUE TITLE
how could I add value to document in rapidjson

### ISSUE THREAD

**Issue by yangaiche** [miloyip/rapidjson#253]
please check this link
http://stackoverflow.com/questions/28856978/how-could-i-add-value-to-document-in-rapidjson

**Comment by pah** [comment]
You need to do an explicit copy:
````cpp
 rapidjson::Document car,cars;
 loadJson(car, "template.json");   //load the json file from disk
 loadJson(cars,"cars.json");
 auto & allocator=cars.GetAllocator();
 rapidjson::Value carCopy(car, allocator); // copy with correct allocator
 cars.PushBack(carCopy, allocator);
````
Alternatively, you can use the `MemoryPoolAllocator` from `cars` also for `car or use a `CrtAllocator` for both.

**Comment by yangaiche** [comment]
hi, pah.That`s very helpful!  Could you give me more details about MemoryPoolAllocator && CrtAllocator.I am using version 0.11.

**Comment by pah** [comment]
The original version 0.11 (from Google code) is quite old and has many issues that have been fixed in the current GitHub `master` branch.  You can find some information on the allocator support in the [RapidJSON documentation][1].

[1]: https://miloyip.github.io/rapidjson/
