### ISSUE TITLE
Embedded JSON objects issue in Linux

### ISSUE THREAD

**Issue by felipegb94** [miloyip/rapidjson#254]
Has anybody have trouble creating embedded json files? I am trying to create something like this:
```
{
"test_name": "sampleName", 
"passed": true
"metrics": { "metric1_name": 12, "metric2_name": 10}
}
```
and then write that to a file. It currently works on my mac but when I try it out on a linux machine it screws up the information in the embedded json (the "metrics" portion). More specifically it writes the wrong string in the metric_names. 

Has anybody stumbled into this issue?

Currently the build status says that it is not correctly building in linux. But rapidjson I am using is from like 6 months ago, if that makes any difference.

Thanks!

**Comment by crespo2014** [comment]
Hi Felipe.
It seems to me a missing comma after -- "passed": true --

**Comment by felipegb94** [comment]
That was just an example of what I want to do. I am successfully creating a json file using rapidjson in my mac osx but I am not able to create a json file with rapidjson in linux. And the problems only come up when I have an embedded json object..

Thanks !

**Comment by pah** [comment]
RapidJSON is well tested on Linux. Can you show some code?
If it is related to string contents, are you sure, your strings have the correct lifetime? Maybe their memory is freed prematurely and reused differently on different platforms.

**Comment by felipegb94** [comment]
This is the link to the code: https://github.com/felipegb94/BaseTest

Basically I have  BaseTest class from which all tests are derived from. The BaseTest class has a function called addMetric(String NameOfMetric, double ValueOfMetric) which looks like this:

```
  void addMetric(const std::string& metricName,
                 double             metricValue) {

    rapidjson::Document::AllocatorType& allocator = m_testJson.GetAllocator(); ///< Allocates space in m_testjson.
    m_jsonMetrics.AddMember(rapidjson::StringRef(metricName.c_str()), metricValue, allocator);

  }
```

This is supposed to add a key value pair to a json object which I declar in the following way :
```
  m_jsonMetrics.SetObject();
```

The addMetric function is called many times throughout a test. Then after the test is done, this m_jsonMetrics is added to another json object call m_testJson. This is done in the following way: 

```
    m_testJson.AddMember("metrics", m_jsonMetrics, allocator);
```

Finally after I have finished adding members to m_testJson I write it to a file in the following way:

```
    // Write Json to file
    std::string filename =  m_name + ".json";
    char writeBuffer[65536];
    FILE* fp = fopen(filename.c_str(), "w"); // non-Windows use "w"

    rapidjson::FileWriteStream os(fp, writeBuffer, sizeof(writeBuffer));
    rapidjson::Writer<rapidjson::FileWriteStream> writer(os);

    m_testJson.Accept(writer);

    fclose(fp);
```

I don't know where I can be making a mistake. I believe that maybe it is in the addMetric function. But what I don't understand is that it works in my mac osx but it doesn't in linux.

Thank you very much for responding to this post!
Felipe

**Comment by pah** [comment]
I think, I see the issue in your code. The following is wrong, you need to make a _copy_ of the string as it may go out of scope before you stop using it:
````cpp
rapidjson::StringRef(metricName.c_str())
````
For convenience, you may want to enable the `std::string` support in RapidJSON by defining [`RAPIDJSON_HAS_STDSTRING=1`][1] before including RapidJSON.

The code in question should then look like:
````cpp
    rapidjson::Document::AllocatorType& allocator = m_testJson.GetAllocator(); ///< Allocates space in m_testjson.
    rapidjson::Value metricNameV(metricName, allocator);
    m_jsonMetrics.AddMember(metricNameV, metricValue, allocator);
````
If you prefer a single line, you can use:
````cpp
    m_jsonMetrics.AddMember(rapidjson::Value(metricName, allocator).Move(), metricValue, allocator);
````

On Mac OS X, the memory of the string may not have been reused, yet. That's why you seem to get away with this. It's still wrong on there as well.

Hope that helps,
  Philipp

[1]: https://miloyip.github.io/rapidjson/group___r_a_p_i_d_j_s_o_n___c_o_n_f_i_g.html#ga2f2eef0ee4477f3fe5874703a66e997f

**Comment by felipegb94** [comment]
Hi Phillip,
Thank you so much for your help. I tried your solution but I get the following error:

```
/Users/felipegb94/repos/chrono/src/unit_TESTING/benchmark/../include/rapidjson/document.h:1022:5: note: candidate function [with T = double] not viable: no known conversion from
      'rapidjson::Value' (aka 'GenericValue<UTF8<> >') to 'StringRefType' (aka 'GenericStringRef<Ch>') for 1st argument
    AddMember(StringRefType name, T value, Allocator& allocator) {
    ^
```

After this error there are a couple others referring to the same comment that the is not known conversion from Value to StringRefType. How can I make sure that the string does not go out of scope? I tried this but it gives me the same problem:

```
    rapidjson::Value metricNameV;
    metricNameV.SetString(metricName.c_str(), metricName.size());
    m_jsonMetrics.AddMember(rapidjson::StringRef(metricNameV.GetString()), metricValue, allocator);

```

**Comment by pah** [comment]
Ok, this is unexpected. The above code should work™, but there is a missing overload of `AddMember<T>` to take the "name" of a new member as explicit RapidJSON `Value` reference and accepting the "value" as a templated type (here: `double`).

Instead of fiddling with the string, you need to explicitly convert the "value" to a RapidJSON `Value` to avoid the problem:
````cpp
    rapidjson::Document::AllocatorType& allocator = m_testJson.GetAllocator(); ///< Allocates space in m_testjson.
    rapidjson::Value metricNameV(metricName, allocator);
    rapidjson::Value metricValueV(metricValue);
    m_jsonMetrics.AddMember(metricNameV, metricValueV, allocator);
````

I'll send a pull-request to fix this inconvenience.

**Comment by felipegb94** [comment]
Hi Phillip,

I actually just figure it out and it is the exact solution you just brought up. I don't know if it is possible but it might be useful to have an AddMember function that looks like this:

GenericValue & 	AddMember (GenericValue &name name, T value, Allocator &allocator)

Thanks for your help!
Felipe

**Comment by pah** [comment]
See #257.
