### ISSUE TITLE
Build failure on OS X using libstdc++ (Clang, 10.6 deployment target)

### ISSUE THREAD

**Issue by sswires** [miloyip/rapidjson#255]
When building on Mac OS X, including stringbuffer.h or document.h will result in build errors pertaining to std::move. std::move is not a part of libstdc++ on OS X and using libc++ requires 10.7 as the minimum deployment target.

The error shows as follows:

    /path/to/source/rapidjson/stringbuffer.h:51:27: error: 
          no member named 'move' in namespace 'std'
                stack_ = std::move(rhs.stack_);
                         ~~~~~^

A quick workaround is to comment out the line that defines RAPIDJSON_HAS_CXX11_RVALUE_REFS for Clang. While the compiler does support the language feature, the libstdc++ version of STL does not have an implementation for std::move.

**Comment by pah** [comment]
A better solution is to add `-DRAPIDJSON_HAS_CXX11_RVALUE_REFS=0` to your compiler flags. This applies to all cases, where the automatic detection of the correct values for the configuration switches fails on a specific platform.

**Comment by pah** [comment]
@miloyip: I'm not sure, if need to add a special case for this platform combination. It's a rather rare combination to use a compiler with rvalue-ref support together with a C++ library without `std::move`.

**Comment by thebusytypist** [comment]
I second @pah's solution that use `-DRAPIDJSON_HAS_CXX11_RVALUE_REFS=0` to override current problematic language feature detection.

People from other projects report this kind of problem as well, for example this one:
https://svn.boost.org/trac/boost/ticket/8092

We can add some more `#ifdef`s to refine current language feature detection:
```
#ifndef RAPIDJSON_HAS_CXX11_RVALUE_REFS
#if defined(__clang__)
#define RAPIDJSON_HAS_CXX11_RVALUE_REFS __has_feature(cxx_rvalue_references) && \
    (defined(_LIBCPP_VERSION) || defined(__GLIBCXX__) && __GLIBCXX__ >= 20080306)
#elif (defined(RAPIDJSON_GNUC) && (RAPIDJSON_GNUC >= RAPIDJSON_VERSION_CODE(4,3,0)) && defined(__GXX_EXPERIMENTAL_CXX0X__)) || \
      (defined(_MSC_VER) && _MSC_VER >= 1600)

#define RAPIDJSON_HAS_CXX11_RVALUE_REFS 1
#else
#define RAPIDJSON_HAS_CXX11_RVALUE_REFS 0
#endif
#endif // RAPIDJSON_HAS_CXX11_RVALUE_REFS
```

The new `    (defined(_LIBCPP_VERSION)` line is for the libc++/libstdc++ version check.
The relation between `__GLIBCXX__` and GCC release number can be found here:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html

This can detect rvalue ref support correctly for a configuration of `-std=c++11 -stdlib=libstdc++`.
