### ISSUE TITLE
Is there any fast way move one DOM to another DOM

### ISSUE THREAD

**Issue by yangaiche** [miloyip/rapidjson#256]
say we have two  rapidjson instances, json_data1,json_data2. the struct is like this:
json_data1
 ```json
{
"a":{}
}
```
json_data2
```json
{
"b":[1,2],
"c":2

}
```
how could I move "b" object to json_data1 "a"  in a fast way. the result is like this : 
json_data1
```json
{
"a":[1,2]
}
```
json_data2
```json
{
"c":2
}
```

**Comment by pah** [comment]
RapidJSON uses (fast) [move semantics][1] by default.
Provided that you have used the same allocator for the two objects, you can simply do a:
````cpp
rapidjson::Value::MemberIterator b = json_data2.FindMember("b");
json_data1["a"] = b->value;
RAPIDJSON_ASSERT( json_data2["b"].IsNull() ); // "b" is empty now
json_data2.EraseMember(b);
````

[1]: https://miloyip.github.io/rapidjson/md_doc_tutorial.html#MoveSemantics

**Comment by yangaiche** [comment]
that`s the one .thanks~
