### ISSUE TITLE
No need to install object files and other temporary files under examples

### ISSUE THREAD

**Issue by yurivict** [miloyip/rapidjson#259]
Currently it installs files like these:

    share/doc/RapidJSON/examples/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o
    share/doc/RapidJSON/examples/CMakeFiles/condense.dir/link.txt

These should never be installed, only true sources should get installed.

**Comment by thebusytypist** [comment]
Hi @yurivict ,

I failed to reproduce your problems using CMake(version 3.0.0+) with generators "Visual Studio 12 2013" and "Unit makefiles"(Mac OS X 10.10).

Can you supply more information, like

* Revision of RapidJSON
* Your platform, and the version of CMake you were using
* Generator
* Your directory structure(RapidJSON source folder, build folder(if you were using out-source building))

**Comment by yurivict** [comment]
I build on FreeBSD. From the project root:
$ cmake .
$ gmake
$ gmake install

Problem: it installs object files, ex. capitalize.cpp.o. Object files should never be installed. Another problem: object files are commonly named without .cpp in them.

I never heard of "generators". I don't think you need them, generally speaking.

**Comment by thebusytypist** [comment]
I successfully reproduce your problems.
This happens in a in-source build, i.e. by calling `cmake .` from the project root. Those intermediate files are mixed with original source files.

As a quick solution while I am trying to find a way to filter those intermediate files, you can try an out-source build:
(Assume you are in the project root)
```
$ mkdir build
$ cd build
$ cmake ..
```
