### ISSUE TITLE
How can i read some data from the object json array string ?

### ISSUE THREAD

**Issue by chinaestone** [miloyip/rapidjson#260]
How can i read some data from the object json array string ?

Here is what i need to parse :

" [
{ "Big Key": "Key Value 1", "Child Key": "Key Value 1", "Values": 1, 3, 4, 1, 2, 3 }, { "Big Key": "Key Value 2", "Child Key": "Key Value 2", "Values": 17, 18, 5, 4, 17 }
]"

**Comment by pah** [comment]
You may want to have a look at the [tutorial](https://miloyip.github.io/rapidjson/md_doc_tutorial.html#QueryValue).
