### ISSUE TITLE
AddMember can`t   set string as key

### ISSUE THREAD

**Issue by yangaiche** [miloyip/rapidjson#261]
```cpp
string key="hello";
Value v;
json_temp.AddMember(key.c_str(), v, json_temp.GetAllocator());  //compile error

json_temp.AddMember("hello", v, json_temp.GetAllocator());  //compile OK
```

how could I solve this problem?

**Comment by pah** [comment]
You need to construct a temporary `Value`, creating a _copy_ of the string in case of a dynamic name:
````cpp
Value n(key.c_str(), json_temp.GetAllocator());
json_temp.AddMember(n, v);
````
See also the example in the [tutorial][1].

[1]: https://miloyip.github.io/rapidjson/md_doc_tutorial.html#ModifyObject

**Comment by D-r-P-3-p-p-3-r** [comment]
And what sense does it make that you have to create a temporary?

**Comment by heavyair** [comment]
Could we add a helper method like AddMemberCopyString(std::string p_sName, std::string p_sValue)? This would internally handle the allocator and explicitly perform a copy, so users don’t have to manually manage the pointer, size, and allocator every time.
