### ISSUE TITLE
I wonder how to build doc like rapidjson in github ,so cool 

### ISSUE THREAD

**Issue by yangaiche** [miloyip/rapidjson#262]
https://miloyip.github.io/rapidjson/index.html

Is there any template  to to do this ?

**Comment by rotanov** [comment]
Is that an issue? I think there's other ways to communicate with developer rather than filing an issue for each question.

**Comment by miloyip** [comment]
You can check https://github.com/miloyip/rapidjson/tree/master/doc
and https://github.com/miloyip/rapidjson/tree/master/doc/misc

**Comment by yangaiche** [comment]
thanks, miloyip.
