### ISSUE TITLE
RAPIDJSON_ASSERT(IsObject()) fails randomly

### ISSUE THREAD

**Issue by PaulKeefe** [miloyip/rapidjson#264]
I had been randomly (about every second or third time running my c++ app) getting the assertion error for RAPIDJSON_ASSERT(IsObject()) on my JSON in cocos2d-x v3.4.

After some research I solved it by changing line 420 of the reader.h file like this:

//if (stream.Peek() != '\0')
if (stream.Peek() != '\0' && stream.Peek() != static_cast<Ch>(std::char_traits<Ch>::eof()))

I got the fix from this page: https://github.com/USCiLab/cereal/blob/24ce678c74e29309149359e5af9e40d39ac2162e/include/cereal/external/rapidjson/reader.h#L253

As you can see it is an eof that causes the problem. I am trying to see if I can get someone to update the version in included in cocos2d-x as well (it is at line 249 in their version of rapidjson).

**Comment by pah** [comment]
In RapidJSON, streams are currently expected to return `'\0'` upon EOF. The proposed fix is likely not the only place that would require changes for streams behaving differently. Which stream implementation is used in the problematic case?

Secondly, the embedded RapidJSON copy seems to be very old. I would recommend to update to a recent snapshot, which includes a _many_ bug fixes and improvements.

**Comment by PaulKeefe** [comment]
Not sure how to determine that, I am using Document from document.h if that tells you which stream type is used. Also, I think I left off that this happens when calling HasMember.

I think you're right anyway, updating to a newer snapshot would be worthwhile. Then if the problem persists it will be easier to debug as well.

**Comment by PaulKeefe** [comment]
I apologize, this fix seemed to work for many iterations but just failed on me. At this point I think I will replace the cocos2d-x version with the latest snapshot and see how it goes.

**Comment by PaulKeefe** [comment]
I updated to the latest snapshot but I am still getting the same error on HasMember. Here is the data from the error:

Assertion failed: (IsObject()), function FindMember, file /Users/INDEMac/Documents/cocosx/Beeme/proj.ios_mac/../cocos2d/external/json/document.h, line 915.
Printing description of name:
(const rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > &) name = 0x000000016fda8968: {
  data_ = {
    s = (str = "garden", length = 6, hashcode = 0)
    ss = {
      str = {
        [0] = '\x88'
        [1] = '\x8b'
        [2] = '<'
        [3] = '\0'
        [4] = '\x01'
        [5] = '\0'
        [6] = '\0'
        [7] = '\0'
        [8] = '\x06'
        [9] = '\0'
        [10] = '\0'
        [11] = '\0'
        [12] = '\0'
        [13] = '\0'
        [14] = '\0'
        [15] = '\0'
      }
    }
    n = {
      i = (i = 3967880, padding = "\x01")
      u = (u = 3967880, padding2 = "\x01")
      i64 = 4298935176
      u64 = 4298935176
      d = 2.1239561841600929E-314
    }
    o = {
      members = 0x00000001003c8b88
      size = 6
      capacity = 0
    }
    a = {
      elements = 0x00000001003c8b88
      size = 6
      capacity = 0
    }
  }
  flags_ = 1048581
}


Is this telling? Do you need to see the actual JSON?

**Comment by pah** [comment]
I don't know "cocos2d" at all. And the usage of `rapidjson::Document` doesn't tell much about the streams involved, unless you only use it to parse from plain strings (not files or other sources).

Can you show the code (maybe in cocos2d) that is used to read/parse the JSON data?  Is there a check for the result of the parsing? If the parsing fails, which error is detected?

Regarding the debug dump you pasted: The content of `name` (the parameter) is not really helpful. It would have been more interesting to see the contents of `*this`, i.e. the object on which the assertions fails.

**Comment by PaulKeefe** [comment]
The whole issue of streams got me thinking and after some testing I have found the actual problem is that cocos2d file utility is (randomly) adding erroneous data to the end of the string I am loading. So, when I try and parse the json it looks like {"garden":{...}}\354\356\358  ... etc. The numbers at the end appear to be random characters in the stream.

Thanks so much for spending your time on this, it looks like rapidjson is not at fault. Which is great because I love using it!

**Comment by pah** [comment]
Ok, thanks for confirming. You may want to use the [`kParseStopWhenDone`][1] flag to ignore garbage after the first complete JSON object in the stream to work around this bug(?) in cocos2d.

[1]: https://miloyip.github.io/rapidjson/namespacerapidjson.html#a81379eb4e94a0386d71d15fda882ebc9

**Comment by miloyip** [comment]
If the input stream may contain undetermined characters beyond a valid JSON value, as @pah mentioned `kParseStopWhenDone` could be used. 

Note that this is not *always* a correct solution. For example, if a JSON contains only a number 123 (which is possible in RFC7159), adding random characters beyond the number in stream may cause undesired result.

Besides, I don't think the EOF character should be handled in stream. If there is really a requirement for this, please file a separate issue and we can discuss on it.

I think the current issue has been resolved. So I close this.

**Comment by JohnKavanagh1050** [comment]
Thank you so much was stuck on this problem for hours :+1:
