### ISSUE TITLE
RapidJSON does not report error when json content only a string or number.

### ISSUE THREAD

**Issue by xpol** [miloyip/rapidjson#265]
The test file `rapidjson/bin/jsonchecker/fail1.json` does not cause RapidJSON report error.

That is:

```C++
Document d;
d.Parse("\"A JSON payload should be an object or array, not a string.\"");
```

And the follow for just a number:

```C++
Document d;
d.Parse("1");
```

```C++
Document d;
d.Parse("12.3");
```

will not report error neither.

**Comment by pah** [comment]
This is on purpose, as the restrictions of forcing an array/object at top-level have been lifted in the recent JSON [RFC 7159][1]. It seems, the jsonchecker files have not been updated, though. 

[1]: http://www.ietf.org/rfc/rfc7159.txt

**Comment by xpol** [comment]
@pah Got it. Thank you for your information.
