### ISSUE TITLE
Fix Travis failing

### ISSUE THREAD

**Issue by miloyip** [miloyip/rapidjson#266]
Travis failed on x86 clang debug/release configurations. It was reported by Valgrind:
~~~
2: [ RUN      ] JsonChecker.Reader
2: vex x86->IR: unhandled instruction bytes: 0x66 0xF 0x3A 0x22
2: ==16242== valgrind: Unrecognised instruction at address 0x8134dd7.
~~~
If this cannot be directly tackled, is it possible to track the history? Or it may be related to Valgrind version or other environment change?

**Comment by miloyip** [comment]
In 553dc0a8b09e883e2fe6dd6faa2fa341e021f056, it replaces `march=native` by `msse4.2` to attempt to solve the valgrind bug issue. But it seems that is still not working for the clang compilation output.

According to this [reference](http://ref.x86asm.net/coder64.html#two-byte), 0x66 0xF 0x3A 0x22 is a PINSRD/PINSRQ (SSE4.2) instruction.

According to https://bugs.kde.org/show_bug.cgi?id=276780, PINSRD was not supported on x86 at that time.

Any idea how to workaround this?

**Comment by pah** [comment]
We could downgrade the SSE support on X86 to version 2 (or disable it completely).
This would also add additional code paths to the tests.
