### ISSUE TITLE
output "o Yip" instead of "hello" after build tutorial.cpp and execute it

### ISSUE THREAD

**Issue by duanmeng** [miloyip/rapidjson#273]
It should be "hello":"rapidjson" not "o Yip": "rapidjson"
Modified JSON with reformatting:
{
    "o Yip": "rapidjson",

--------------------------------------------------log--------------------------------------------------
duanmeng@ubuntu:~/work/rapidjson/mycodes/example/tutorial$ uname -a
Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:08:14 UTC 2014 i686 i686 i686 GNU/Linux
duanmeng@ubuntu:~/work/rapidjson/example/tutorial$ g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

duanmeng@ubuntu:~/work/rapidjson/example/tutorial$ g++ -Wall tutorial.cpp -o tutorial
duanmeng@ubuntu:~/work/rapidjson/example/tutorial$ ./tutorial 
Original JSON:
  { "hello" : "world", "t" : true , "f" : false, "n": null, "i":123, "pi": 3.1416, "a":[1, 2, 3, 4] } 

Parsing to document succeeded.

Access values in document:
hello = world
t = true
f = false
n = null
i = 123
pi = 3.1416
a[0] = 1
a[1] = 2
a[2] = 3
a[3] = 4
a = 1 2 3 4 
Type of member hello is String
Type of member t is True
Type of member f is False
Type of member n is Null
Type of member i is Number
Type of member pi is Number
Type of member a is Array

Modified JSON with reformatting:
{
    "o Yip": "rapidjson",
    "t": true,
    "f": false,
    "n": null,
    "i": 2432902008176640000,
    "pi": 3.1416,
    "a": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        "Lua",
        "Mio"
    ],
    "author": "Milo Yip"
}

**Comment by pah** [comment]
It's a bug in the tutorial code, invalidating the insitu buffer too early.
See #274 for a fix.

Thanks for reporting!

**Comment by duanmeng** [comment]
Thanks pah, I've patch your diff and it works well.
