### ISSUE TITLE
When will have a stable release?

### ISSUE THREAD

**Issue by dawnlucky** [miloyip/rapidjson#277]
Hey guys,

Do we have a plan?

Mack

**Comment by miloyip** [comment]
A 1.0 beta shall be released this week, if not next week.

**Comment by dawnlucky** [comment]
Great!, Thanks.

**Comment by patlecat** [comment]
Awesome news! Thanks @miloyip

**Comment by miloyip** [comment]
Please help testing https://github.com/miloyip/rapidjson/releases/tag/v1.0-beta
It is planned to release the official v1.0 at 15 April 2015.

**Comment by dawnlucky** [comment]
Sure, I will add this branch code to the project and test it.

**Comment by miloyip** [comment]
Done! Finally!
https://github.com/miloyip/rapidjson/releases/tag/v1.0.0

**Comment by pah** [comment]
Great! Kudos for your hard work! :+1:

**Comment by spl** [comment]
Congrats! :clap:

**Comment by patlecat** [comment]
@miloyip Thanks a lot mate! And now comes the XML reader/Writer? ;)
