### ISSUE TITLE
performance vs json11

### ISSUE THREAD

**Issue by weepy** [miloyip/rapidjson#278]
Do you know how well rapidjson performs compared to json11 by dropbox ?

**Comment by pah** [comment]
You can try @miloyip's [nativejson-benchmark](https://github.com/miloyip/nativejson-benchmark) to compare the performance of various JSON implementations (including dropbox/json11) on your platform.

I just ran the benchmark locally against the latest versions of both libraries (make sure to apply miloyip/nativejson-benchmark#8 first) on my Core i7 3520M on x86-64 Linux with GCC 5.0 and saw roughly 2.5-5x performance benefit of RapidJSON, depending on the scenario.

Your mileage may vary.

**Comment by weepy** [comment]
Great stuff will investigate further ...
