### ISSUE TITLE
Using library: can't get AddMember call to compile

### ISSUE THREAD

**Issue by vnovytskyy** [miloyip/rapidjson#282]
I am using rapidjson::GenericDocument<<rapidjson::UTF8<wchar_t>>>. When calling AddMember to add a Unicode string, the compiler says template doesn't match arguments:

doc.AddMember(L"hello", rapidjson::GenericValue<<rapidjson::UTF8<wchar_t>>>(L"world"));

The error is:

no instance of overloaded function rapidjson::GenericValue<<Encoding, Allocator>>::AddMember [with Encoding=rapidjson::UTF8<<wchar_t>>, Allocator=rapidjson::MemoryPoolAllocator<<rapidjson::CrtAllocator>>] matches the argument list
            argument types are: (const wchar_t [7], rapidjson::GenericValue<<rapidjson::UTF8<<wchar_t>>, rapidjson::MemoryPoolAllocator<<rapidjson::CrtAllocator>>>)
            object type is: JsonValue

I also tried this:

doc.AddMember(L"hello", L"world");

and this:

doc.AddMember(L"hello", rapidjson::GenericValue<<rapidjson::UTF8<wchar_t>>>(L"world").Move());

and this:

doc.AddMember(L"hello", rapidjson::GenericValue<<rapidjson::UTF8<wchar_t>>>(L"world").Move(), doc.GetAllocator());

and this:

doc.AddMember(L"hello", rapidjson::GenericValue<<rapidjson::UTF8<wchar_t>>>(L"world"), doc.GetAllocator());

Sorry, I can't understand the API interface. What am I supposed to do to have a Document with wide strings used for keys and string values, that serializes to non-wide UTF8 string, and being able to add members to it?

Thank you.

**Comment by vnovytskyy** [comment]
A friend helped me with this. The constant I was using for L"world" was actuall const wchar_t* worldconst = L"world", which gets interpreted as a string requiring a StringRef. When changing constant declaration to const wchar_t worldconst[] = L"world" it got interpreted as a string literal.

**Comment by miloyip** [comment]
By the way, `UTF8<wchar_t>` seems quite strange to me. Are you using UTF16 in memory actually?

**Comment by vnovytskyy** [comment]
I am working on a legacy C++ library previously using System::Data::Json with Platform::String - changing it over to rapidJson and std::wstring. As you know Platform::String represents OLESTR/BSTR so it's always wchar_t, which corresponds to std::wstring.

Everywhere in the public interface of this library, we are using wchar_t for keys, so all functions that set values, get values, and check if values exist take const wchar_t*. Therefore I need wchar_t to be used internally by rapidJson to store keys and any string values.

However, the rapidjson::GenericDocument must get serialized to char* with UTF-8 encoding because we are sending that over a socket as bytes, and want to save space. Does this sound like something this library can do directly, or do I need to use UTF16/wchar_t and then transcode to UTF8/char just before sending over the wire?

**Comment by miloyip** [comment]
RapidJSON supports transcoding internally. You can use `UTF16<>` in `GenericDocument`, and then write it out by `Writer<OutputStream, UTF16<>, UTF8<> >`.
You can find an example in http://miloyip.github.io/rapidjson/md_doc_stream.html
