### ISSUE TITLE
Linker error GenericValue::GenericValue(const GenericValue& rhs) not defined

### ISSUE THREAD

**Issue by vnovytskyy** [miloyip/rapidjson#284]
I am getting a linker error (VS2012) when building a program that uses rapidjson. It says GenericValue copy constructor (document.h @ 453) is not defined. Linker appears to be justified, because it's only a function prototype with no definition. Commenting out the function or giving it a body with __ASSERT(false) appears to fix this issue... Although I haven't debugged yet so maybe that will break my program. But it fixes the linker error :)

I am guessing you used this trick to prevent the compiler from generating a copy constructor itself, but I can't imagine how it worked, since it has to be defined as well. Maybe I didn't include a file where it was defined?

**Comment by pah** [comment]
As you can see on [Appveyor] [1], RapidJSON generally works fine on VS2012, even with the deliberately omitted definition of the copy constructor.

The idea is not only to prevent the generation of a copy constructor but to really explicitly prohibit its use (i.e. by declaring it *private* and omitting the definition to generate a linker error as a last resort).

Can you try to isolate the problem and provide a minimal example? Do you use explicit template instantiation of `GenericValue`/`GenericDocument`? It's a bit surprising that the compiler does not complain about the privacy of the copy constructor already.



[1]: https://ci.appveyor.com/project/miloyip/rapidjson

**Comment by vnovytskyy** [comment]
Solved. Linker dumped a file name where it thought the [copy constructor] symbol was referenced, but turns out I accidentally used the copy constructor in a completely different file deep within the program. Haven't thought to look there as I was busy commenting out sections of the file linker was complaining about to isolate the issue.

Finally found this out by hitting that assert I put in place of the missing copy constructor body. Took a while to hit it because it was a rarely-used code path.

The compiler error was very cryptic because template arguments were involved and took forever to understand, but I can no longer reproduce it for some reason... Doing the obvious GenericValue value = anothervalue is producing what you expected (compiler error saying the function is private). I would recommend still giving it a body with assert. If I manage to repro again, I will post the code that produces the issue.
