### ISSUE TITLE
how could I assign rapidJson::Value to rapidJson::Document as root?

### ISSUE THREAD

**Issue by yangaiche** [miloyip/rapidjson#285]
how could I assign rapidJson::Value to rapidJson::Document as root?

**Comment by miloyip** [comment]
Currently `Swap()` can do the trick:

~~~cpp
// test/unittest/documenttest.cpp
TEST(Document, Swap) {
    Document d1;
    Document::AllocatorType& a = d1.GetAllocator();

    d1.SetArray().PushBack(1, a).PushBack(2, a);

    Value o;
    o.SetObject().AddMember("a", 1, a);

    // Swap between Document and Value
    d1.Swap(o);
    EXPECT_TRUE(d1.IsObject());
    EXPECT_TRUE(o.IsArray());
    // ...
}
~~~

Or using C++11 move assignment:
~~~cpp
// test/unittest/documenttest.cpp
TYPED_TEST(DocumentMove, MoveAssignment) {
    typedef TypeParam Allocator;
    typedef GenericDocument<UTF8<>, Allocator> Document;
    Allocator allocator;

    Document a(&allocator);
    a.Parse("[\"one\", \"two\", \"three\"]");

    // Document b; b = a; // does not compile (!is_copy_assignable)
    Document b;
    b = std::move(a);
    // ...
}
~~~

**Comment by yangaiche** [comment]
Maybe My problem is more complicated.
a.json  is like this:
{
"data":
 {
    "id" : 1 
 }
}

b.json is like this:
{
"data":
 {
    "id" : 2 
 }
}


Document    a ;
loadJson(a,"a.json"); //get a.json
{
   Document b;
   loadJson(b,"b.json);
   a.Swap(b["data"]);
}
a.AddMember(("part_type",Value(1),a.GetAllocator());  //crash !!!

I think there`s something wrong with a.GetAllocator(),is that right? how could I solve this problem? thanks!

**Comment by miloyip** [comment]
As shown in the unit tests above, you need to use the same allocator.

**Comment by cswuyg** [comment]
update:
`    Document d1;
    Document::AllocatorType& a = d1.GetAllocator();

    d1.SetArray().PushBack(1, a).PushBack(2, a);

    Value o;
    o.SetObject().AddMember("a", 1, a);

    // Swap between Document and Value
    // d1.Swap(o); // doesn't compile
    o.Swap(d1);`
https://github.com/miloyip/rapidjson/blob/master/test/unittest/documenttest.cpp
