### ISSUE TITLE
Is there any easier way to do this?

### ISSUE THREAD

**Issue by yangaiche** [miloyip/rapidjson#286]
I just want to set user_id..... and I write a bunch of code like this...
  
if(json_user_info.HasMember("user_id"))
                            {
                               json_user_info["user_id"]=d["data"]["user_id"].GetInt();
                            }else
                               json_user_info.AddMember("user_id", Value(d["data"]["user_id"].GetInt()),>json_user_info.GetAllocator()  );

**Comment by miloyip** [comment]
This seems similar to #151.
You may create a helper function, which adds a member with default value if it is non-exist. And the function returns the member's value as reference.
But this can does one level depth in the DOM tree. So recently I have worked on #297, which gives a more general, easy way.

**Comment by jblazquez** [comment]
@miloyip, I was thinking about this today as well. Currently rapidjson is very strict about types when using the DOM read API. For example, if you have a `GenericValue` of type `Int64` it will assert if you ask for an `Uint64` or an `Int`. Being strict is a good thing for performance and should be the default behavior, but it would be _very_ useful to have a higher-level DOM read API that allows you to be more lax about types, object members, and so on.

Something like TinyXML's [`TiXmlHandle`](http://www.grinninglizard.com/tinyxmldocs/classTiXmlHandle.html) class would be great.

Would you be open to an addition like this for rapidjson? I would be willing to contribute it, and we can discuss the design beforehand.

**Comment by miloyip** [comment]
>  if you have a `GenericValue` of type `Int64` it will assert if you ask for an `Uint64` or an `Int`

Not really, these types are not exclusive to each other. If the data is within a certain range, it can be at the same time retrieved as `uint64_t`, `int64_t`, `unsigned`, `int` without any runtime overhead or losing precision. `double` is a special case that all integer types can be obtained as double but precision may be lost if more than 53bit is used.

> Something like TinyXML's TiXmlHandle class would be great.

JSON Pointer has some similarity but it cannot traverse the DOM tree after applying to a DOM tree. Do you have some functionality in mind that you would like to have?

> Would you be open to an addition like this for rapidjson? I would be willing to contribute it, and we can discuss the design beforehand.

I am open on this. Currently I am planning for v1.1 features. Yes, I am very glad to discuss. You may create an separate issue, write down some ideas for discussion.

**Comment by jblazquez** [comment]
> If the data is within a certain range, it can be at the same time retrieved as uint64_t, int64_t, unsigned, int without any runtime overhead or losing precision.

You're right, I misread [these asserts](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/document.h#L1345-1348) because I thought only one flag (either `kNumberIntFlag`, `kNumberUintFlag`, `kNumberInt64Flag` or `kNumberUint64Flag`) would be set at one time, but they're all set at the same time. My comment still applies to `double` vs `int` values as you mention though.

> Do you have some functionality in mind that you would like to have?

My main use case is simplifying code that uses the DOM read API and doesn't need to be super high performance, but rather be more readable. I like being able to choose whether I want to have the highest performance (thus choosing the lowest level rapidjson API) or have lower performance but greater convenience (thus choosing a higher-level API that is lax about value types, returns default values for non-existent members, and maybe performs some type conversions on demand).

I think the `TiXmlHandle` example illustrates this point very well:

```
Assuming you want the value of "attributeB" in the 2nd "Child" element, it's very easy to write a *lot* of code that looks like:

	TiXmlElement* root = document.FirstChildElement( "Document" );
	if ( root )
	{
		TiXmlElement* element = root->FirstChildElement( "Element" );
		if ( element )
		{
			TiXmlElement* child = element->FirstChildElement( "Child" );
			if ( child )
			{
				TiXmlElement* child2 = child->NextSiblingElement( "Child" );
				if ( child2 )
				{
					// Finally do something useful.
```

```	
And that doesn't even cover "else" cases. TiXmlHandle addresses the verbosity of such code. A TiXmlHandle checks for null pointers so it is perfectly safe and correct to use:

	TiXmlHandle docHandle( &document );
	TiXmlElement* child2 = docHandle.FirstChild( "Document" ).FirstChild( "Element" ).Child( "Child", 1 ).ToElement();
	if ( child2 )
	{
		// do something useful
```

> Currently I am planning for v1.1 features. Yes, I am very glad to discuss. You may create an separate issue, write down some ideas for discussion.

I'll open a new issue with my ideas and we'll discuss it there. Thank you!

**Comment by miloyip** [comment]
I think #297 can do similar thing as in your `TiXmlHandle` example, such as:
~~~cpp
if (Value* child2 = GetByPointer(d, "/Document/Element/Child/Child")) {
}
~~~

**Comment by jblazquez** [comment]
Yes, I'll definitely look very hard at the JSON Pointer API before proposing anything new. Maybe the pointer API is powerful enough for all I want to do.

**Comment by olexiyb** [comment]
To cover example above why not provide next function?
json_user_info["user_id"]=d["data"].GetInt("user_id", default_value); //will return default_value if user_id is null or does not exists.

**Comment by miloyip** [comment]
There are `Pointer::GetWithDefault()` and `GetValueByPointerWithDefault()` family of functions provided by [JSON Pointer API](http://rapidjson.org/md_doc_pointer.html). This should be more easier to work with.
