### ISSUE TITLE
Writer test segfaulted under valgrind

### ISSUE THREAD

**Issue by shindo** [miloyip/rapidjson#294]
Valgrind version: valgrind-3.10.1
gcc version 4.9.2 20150304 (prerelease) (GCC) 

RapidJSON was built with `cmake -DRAPIDJSON_HAS_STDSTRING=ON -DRAPIDJSON_BUILD_DOC=OFF`.

Valgrind output (error only): http://pastebin.com/ritSZcrq

**Comment by miloyip** [comment]
I think this may be the same issue as https://github.com/miloyip/itoa-benchmark/issues/8
I will merge that fix here.

**Comment by miloyip** [comment]
I have merged the code to master. Can you help verifying it in your platform? Thank you.

**Comment by shindo** [comment]
Yes, this fixes the problem. Thanks.

**Comment by miloyip** [comment]
Thank you for your report and verification.
