### ISSUE TITLE
PrettyWriter: add support for fixed extra indentation

### ISSUE THREAD

**Issue by JamesOldfield** [miloyip/rapidjson#299]
Currently `PrettyWriter` has support for customising the amount of indentation per level. But it would be useful if it could also support a fixed amount of extra indentation that is independent of level. (I've come across the need for this in two contexts: adding some indentation for logging, and where I'm only recording a fragment of JSON in RapidJSON, so the true level is greater than `PrettyWriter` is aware of.)

There would probably need to be the following changes, all in `prettywriter.h`:
* Storage: A new private member to store the setting, which is set to zero in the constructor.
* Interface: A new set method to alter this member, and perhaps also a getter for symmetry. (Adding a new constructor parameter is also an option, but the constructor already has quite a few parameters so I suggest against this.)
* Implementation: Update the `WriteIndent()` method so that the `count` variable includes this extra amount.
* Implementation extra: The `WriteIndent()` method is currently not called when the level is zero, so to ensure the first line of output has this extra indentation it would need to be called from the top-level `else` clause in `PrettyPrefix()`. (Since that `else` clause would no longer be trivial, it might then make sense to reverse the polarity of the `if (...GetSize() != 0)` test to the more natural `if (...GetSize() == 0)`.)

The setting could potentially be either be "number of extra spaces" (added directly to `count`) or "number of extra levels" (included in the multiplication by `indentCharCount_`). I don't have any preference about this.

Many thanks to everyone for the hard work on RapidJSON!

**Comment by miloyip** [comment]
I am not sure whether this is a common feature. But this seem adding a little bit overhead if this option is not used (in the normal way).
I can think of two ways to implement this without changing `PrettyWriter`:
1. Just clone another copy of `PrettyWriter` with this feature.
2. Create a custom output stream, which add those fixed indents. This may be also useful for you to write directly to the log via streaming, instead of creating a string first, and then dump to the log.

**Comment by JamesOldfield** [comment]
I would imagine the overhead is trivial if the option isn't used (though I haven't checked) since the only thing happening in a loop is the addition of zero to an integer in the WriteIndent() method. 

I'd assumed this would be quite popular, but in a quick Google of other pretty printers (for other languages etc) I didn't find any with those feature. I'm rather surprised but perhaps it's just me that needs it.

So far I've directly customised PrettyWriter. Creating a custom output stream is a great idea, thanks! I'll give that a go.
