### ISSUE TITLE
Version policy

### ISSUE THREAD

**Issue by miloyip** [miloyip/rapidjson#315]
Fortunately (or unfortunately), a bug #313 is discovered after v1.0.0 just released. And I think that it is quite a serious one.

For this kind of situations, I think it should be better releasing a new patch version *immediately* when the bug is resolved. And in this moment, it will be v1.0.1.

Or should we set a date for v1.0.1, releasing it if no more bugs are found?

**Comment by spl** [comment]
I agree: release a bug-fix version when it is ready. The only reasons I can think to delay are (a) it takes a lot of effort to cut a new release (it doesn't, right?) and (b) you expect more code changes (you don't).

**Comment by spl** [comment]
Also, perhaps this would be a good time to start a change log with a entry that links to the issue.

**Comment by miloyip** [comment]
Good idea for changelog.
Any format of changelog would you suggest? An example would be great for me.

**Comment by miloyip** [comment]
I found this one: https://github.com/olivierlacan/keep-a-changelog .
Looks good for me.

**Comment by spl** [comment]
Looks good to me, too.

**Comment by miloyip** [comment]
Done https://github.com/miloyip/rapidjson/releases/tag/v1.0.1
