### ISSUE TITLE
CMAKE_BUILD_TYPE didn't set by default 

### ISSUE THREAD

**Issue by RustJason** [miloyip/rapidjson#319]
```
cmake ../ && cmake -L
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
BUILD_TESTING:BOOL=ON
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_DIR:PATH=/usr/local/lib/cmake/RapidJSON
CMAKE_INSTALL_PREFIX:PATH=/usr/local
DOC_INSTALL_DIR:PATH=/usr/local/share/doc/RapidJSON
GTEST_INCLUDE_DIR:PATH=GTEST_INCLUDE_DIR-NOTFOUND
GTEST_SOURCE_DIR:PATH=GTEST_SOURCE_DIR-NOTFOUND
INCLUDE_INSTALL_DIR:PATH=/usr/local/include
LIB_INSTALL_DIR:STRING=/usr/local/lib
RAPIDJSON_BUILD_DOC:BOOL=ON
RAPIDJSON_BUILD_EXAMPLES:BOOL=ON
RAPIDJSON_BUILD_TESTS:BOOL=ON
RAPIDJSON_BUILD_THIRDPARTY_GTEST:BOOL=OFF
RAPIDJSON_HAS_STDSTRING:BOOL=OFF
```
But this works fine:
```
cmake -DCMAKE_BUILD_TYPE=Debug ../ && cmake -L
-- Cache values
BUILD_TESTING:BOOL=ON
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_DIR:PATH=/usr/local/lib/cmake/RapidJSON
CMAKE_INSTALL_PREFIX:PATH=/usr/local
......
```

**Comment by Red-wolf-s-husband** [comment]
I think It should display RelWithDebInfo by default, because this:
```
///CMakeLists.txt

SET(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "Build Type")
```

**Comment by miloyip** [comment]
@jollyroger, what you do think?

**Comment by jollyroger** [comment]
according to this thread
http://www.cmake.org/pipermail/cmake/2009-June/030311.html, setting
CMAKE_BUILD_TYPE is just not enough. In the latter messages the proposed
way to set default build type is:

    if(NOT CMAKE_BUILD_TYPE)
      set(CMAKE_BUILD_TYPE "Release" CACHE STRING
          "Choose the type of build, options are: Debug Release
RelWithDebInfo MinSizeRel." FORCE)
    endif(NOT CMAKE_BUILD_TYPE)

Note that in this case using FORCE is mandatory.


2015-04-28 6:05 GMT+03:00 Milo Yip <notifications@github.com>:

> @jollyroger <https://github.com/jollyroger>, what you do think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miloyip/rapidjson/issues/319#issuecomment-96893792>.
>



-- 
WBR, Andrii Senkovych

**Comment by Red-wolf-s-husband** [comment]
@jollyroger This works. But that thread didn't explan why we need to use "FORCE". can you ?

**Comment by jollyroger** [comment]
@Red-wolf-s-husband, AFAIR, it just doesn't work without `FORCE` option, this is easy to try. This has no any side effects since we check beforehand if this option is defined.
