### ISSUE TITLE
Assertion 'flags_ & kUintFlag' failes when reading timestamp

### ISSUE THREAD

**Issue by ligouras** [miloyip/rapidjson#324]
On v1.0.0 I'm getting into some trouble when trying to read a timestamp from a JSON with `GetUint()`

`unsigned int rapidjson::GenericValue<Encoding, Allocator>::GetUint() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion 'flags_ & kUintFlag' failed.`

This is the value i'm trying to read, `IsNumber()` and `IsUint64()` return true:

```
{
    statickDefaultArrayCapacity=<optimizedout>,
    statickDefaultObjectCapacity=<optimizedout>,
    data_={
        s={
            str=0x14aecb43a9d<error: Cannotaccessmemoryataddress0x14aecb43a9d>,
            length=0,
            hashcode=0
        },
        ss={
            str="\235:\264\354J\001\000\000\000\000\000\000\000\000\000"
        },
        n={
            i={
                i=-323732835,
                padding="J\001\000"
            },
            u={
                u=3971234461,
                padding2="J\001\000"
            },
            i64=1421310442141,
            u64=1421310442141,
            d=7.0222066153730084e-312
        },
        o={
            members=0x14aecb43a9d,
            size=0,
            capacity=0
        },
        a={
            elements=0x14aecb43a9d,
            size=0,
            capacity=0
        }
    },
    flags_=12806
}
```

any hints on what might be wrong ?

**Comment by miloyip** [comment]
When RapidJSON parse the JSON value, it will detect whether it can be converted to an `unsigned`, or must be `uint64_t`.

In your case, since the number `1421310442141` is bigger than what `unsigned` can hold, and as `IsUint64() == true`,  you should use `GetUint64()` instead of `GetUint()`. The assertion should clearly state the problem, isn't it?

**Comment by ligouras** [comment]
I see, thanks for the quick reply. I was misled by the table in http://miloyip.github.io/rapidjson/md_doc_tutorial.html#QueryNumber where `GetUint()` is referenced as the function to obtain `uint64_t`. `GetUint64()` worked as intended.

**Comment by miloyip** [comment]
Oh. Thank you for your feedback. It was a mistake in the tutorial.
