### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by miloyip** [miloyip/rapidjson#326]
I am attempting to implement a [JSON Schema Draft 4](http://json-schema.org/documentation.html) validator. It is now at the [schema](https://github.com/miloyip/rapidjson/tree/schema) branch:

* [schema.h](https://github.com/miloyip/rapidjson/blob/schema/include/rapidjson/schema.h)
* [schematest.cpp](https://github.com/miloyip/rapidjson/blob/schema/test/unittest/schematest.cpp)

A very good e-book [Understanding JSON Schema](http://spacetelescope.github.io/understanding-json-schema/) is available. The current implementation simply uses the test cases in this e-book. (More extensive test cases are necessary.)

## Stream Validator
 I tried to implement it as a stream validator, i.e. it validates the SAX events against a schema. I suspect all available validators are DOM-based.

The major advantage of this design is that you can:

1. Validate a JSON stream without parsing it to a DOM. Imagine you can validate a 10GB JSON file without loading or parsing the whole JSON into memory.
2. Insert the validator between `Reader` and `Document`, so it can validate the events from `Reader` and delegate the validated events to `Document`. The parsing can be terminated if any event does not conform to the schema.
3. Validate a DOM. This can be simply implemented by `bool valid = document.Accept(schemaValidator)`.
4. Insert the validator between `Document` and `Writer`, so it can validate the events when writing the JSON. This removes a separated validation pass as by 3.

There are some difficulties/drawbacks that will be mentioned in the next section.

## Conformance

* [x] `enum`
   * [x] primitive types
   * [x] compound types
* [x] `type`
  * [x] type-less
  * [x] single type (string)
  * [x] multiple type (array)
* [x] `string`
  * [x] `minLength`, `maxLength`
  * [x] `pattern`
  * [ ] `format`
* [x] `integer`
  * [x] `minimum`, `maximum`, `exclusiveMinimum`, `exclusiveMaximum`
  * [x] `multipleOf`
* [x] `number`
  * [x] `minimum`, `maximum`, `exclusiveMinimum`, `exclusiveMaximum`
  * [x] `multipleOf`
* [x] `object`
  * [x] `properties`
  * [x] `additionalProperties` (boolean)
  * [x] `additionalProperties` (object)
  * [x] `required`
  * [x] `minProperties`, `maxProperties`
  * [x] `dependencies` (property dependencies)
  * [x] `dependencies` (schema dependencies)
  * [x] `patternProperties`
* [x] `array`
  * [x] `items` (object)
  * [x] `items` (array)
  * [x] `additionalItems`
  * [x] `minItems`, `maxItems`
  * [x] `uniqueItems`
* [x] `boolean`
* [x] `null`
* [x] combinations
  * [x] `allOf`
  * [x] `anyOf`
  * [x] `oneOf`
  * [x] `not`
* [x] `definitions`
* [x] `$ref`
  * [x] remote `$ref`
  * [ ] `id`
* [ ] metadata
  * [ ] `title`
  * [ ] `description`
  * [ ] `default`
  * [ ] `$schema`

A major difficulty is that, the schema validator can only process a single event at a time. The current design uses a stack to store the state of schema (path to current schema), and use the schema at the top of the stack to validate the incoming event. This cannot handle compound `enum`, combinations (`allOf`, etc.). and `depenencies`. Another design is needed for validating a event with multiple schema states in parallel. This will create a tree structure instead of a linear stack.

Another difficulty is the support of regular expression. A simple workaround is to use C++11 `regex`. Otherwise a header-only implementation is needed.

## Infrastructure

* <strike>Report errors in converting a JSON document to schema</strike>
* [x] Report error during validation
* [x] Supports Non-UTF8 encodings
* [x] Customizable allocators
* [ ] Remove `<cmath>` dependency
* <strike>Simplify schema conversion with JSON Pointer</strike>

**Comment by justgook** [comment]
nice work, i will check it and try to find some more cases..

**Comment by lumpidu** [comment]
Hi,

I was trying this out today with one of our schemas and a json document. It won't bulp it down, though e.g. the json-schema ruby gem does.

It would be good if there'd be better debugging why a d.Accept(validator) returns false.

Any ideas where I should dig further?

**Comment by miloyip** [comment]
Currently the `schematest.cpp` uses the following code to get more information about validation failure:
~~~cpp
#define VALIDATE(schema, json, expected) \
{\
    SchemaValidator validator(schema);\
    Document d;\
    printf("\n%s\n", json);\
    d.Parse(json);\
    EXPECT_FALSE(d.HasParseError());\
    EXPECT_TRUE(expected == d.Accept(validator));\
    EXPECT_TRUE(expected == validator.IsValid());\
    if (expected && !validator.IsValid()) {\
        StringBuffer sb;\
        validator.GetInvalidSchemaPointer().StringifyUriFragment(sb);\
        printf("Invalid schema: %s\n", sb.GetString());\
        printf("Invalid keyword: %s\n", validator.GetInvalidSchemaKeyword());\
        sb.Clear();\
        validator.GetInvalidDocumentPointer().StringifyUriFragment(sb);\
        printf("Invalid document: %s\n", sb.GetString());\
    }\
}
~~~

You can obtain the schema keyword, and the 2 JSON pointers for the document and schema, pointing to where the validation failure.

Some unit tests also explicitly tests the failure cases.

Please report to us when there is something wrong in the validation process. You may also send the files to me via miloyip@gmail.com if you do not want to make the files public.

**Comment by patrickjwhite** [comment]
I just found this issue, and haven't looked at the schema branch yet, but am wondering if there has been any thought of code generation for rapidjson from schema into basic C++ classes, including serialization and deserialization code?

**Comment by miloyip** [comment]
I have not thought of that before. Thank you for your idea. I may investigate some available generators for other languages.

**Comment by patrickjwhite** [comment]
No problem. I have seen generators based on 2 "schemas", one being the standard schema "draft 4", and the other being an example JSON file perfectly filled out.

However, the examples I have seen are either incomplete or part of a huge library and target their own infrastructure. I was thinking something more like a python script, though if the utilities are there (ie. parsing the schema) then c++ could be OK too.

**Comment by cviebig** [comment]
Hello,

I'm working on a project that has recently introduced `rapidjson` for JSON parsing. In order to improve the error handling we would like to implement JSON schema validation before further processing the input.  That's why I wondered about the current state of the feature branch `schema`. Is there any news on this issue or plans to merge the results? The checklist already looks pretty complete and maybe it's totally fine to add it as an experimental feature to `master`?

Best
christoph

**Comment by miloyip** [comment]
Yes. I think it should be merged to master as experimental feature.
The main thing I was stuck is about URL parsing in remote ref, but I think it should not be important for most people.
Another thing is to review the APIs and do some documentation.
I would really want to see others trying to use it and give me feedback as well.

**Comment by purukaushik** [comment]
Hey @miloyip 
I was wondering how rapidjson schema validation works with $refs and $ids pointed to local files as in 
```
{
    "id":"file://test_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type" : "object",
    "properties" : {
	"billing_address" : { "$ref" : "ref_schema.json#/definitions/address"}
    },
    "required":["billing_address"]
}
```
and a ref_schema.json under the same folder as test_schema.json:
```
{
    "id":"file://ref_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
	"address": {
	    "type": "object",
	    "properties": {
		"street_address": { "type": "string" },
		"city":           { "type": "string" },
		"state":          { "type": "string" }
	    },
	    "required": ["street_address", "city", "state"]
	}
    }
}

```
I find that if I try validating the json with schemavalidator.cpp, it passes the validation despite the fact that the required properties(from ref_schema.json#/definitions/address") street_address, city and state are missing:
```
{
 "billing address" : ""
}
```

What am I missing in my understanding here?

**Comment by miloyip** [comment]
For simplicity, `schemavalidator.cpp` does not handle remote schema.
Please refer to the "Remote Schema" section in [user guide](http://rapidjson.org/md_doc_schema.html).

**Comment by purukaushik** [comment]
Oh. Thanks. 👍

**Comment by horanoff** [comment]
Hi Miloyip,

I understand from your comments above that schemavalidator.cpp doesn't handle remote schema references, but it should work with embedded references, is that right?

I'm having trouble validating against this schema:
```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://www.litterloo.com/schemas/test-schema.json",
    "title": "Test Schema for RapidJSON.",
    "type": "object",
    "properties":
    {
        "test":
        {
            "type": "array",
            "items":
            {
                "$ref": "#/$defs/testItem"
            }
        }
    },
    "additionalProperties": false,
    "$defs":
    {
        "testItem":
        {
            "type": "object",
            "required":
            [
                "target"
            ],
            "properties":
            {
                "target":
                {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }
    }
}
```
... using this data:
```
{
    "test":
    [
        {
        }
    ]
}
```
This should fail validation as this validator demonstrates: https://jsonschemalint.com/#!/version/draft-07/markup/json
It should fail because the required "target" element is missing.  If you insert the required target element as shown below, it should then succeed...
```
{
    "test":
    [
        {
            "target": "test"
        }
    ]
}
```
Do you know the reason why the JSON that should fail validation is succeeding?

Thank you!

**Comment by emnkoksal** [comment]
@horanoff

rapidjson supportsonly draft 4! So, you should verify it against 4.
But still yes, your example returns "valid".
Replacing "$defs" with "definitions" resolves your problem.
I do not know exactly why.
Maybe "$defs" was introduced later than draft 4?

**Comment by arghness** [comment]
> @horanoff
> 
> rapidjson supports only **draft 4**! So, you should verify it against 4. But still yes, your example returns "valid". Replacing `$defs` with `definitions` resolves your problem. I do not know exactly why. Maybe `$defs` was introduced later than draft 4?

Yes, this is odd and I've just run in to the same issue. $defs is an official property in a later schema version, but similarly "definitions" isn't part of JSON schema at all. There must be something in the resolver that stops it resolving $defs as a generic property name in the path. Invalid $ref values seem to be silently ignored, so you end up with a bad schema without realising it.

**Comment by horanoff** [comment]
Now that I am more experienced with JSON-Schema, I'm not convinced my example should fail validation because _required[ "test" ]_ wasn't specified in my example.  Moving on from the _$defs / definitions_ thing, I'm wondering if the link I provided to https://jsonschemalint.com/#!/version/draft-07/markup/json isn't 100% correct in how it validates.
