### ISSUE TITLE
weird problems when add RapidJSON 1.0.1 to cocos2dx projects

### ISSUE THREAD

**Issue by laoyur** [miloyip/rapidjson#331]
I decide to add 1.0.1 to my cocos2dx projects as the built-in rapidjson within the cocos2dx framework is quite old.

However, my game runs into weird problems which look like memory issues.
Here is my environment and test code:
(NOTE: **the code runs ok in non-cocos2dx projects**)

**XCode 6.2 + cocos2dx 3.3 + rapidjson 1.0.1**

```
Document doc;
doc.SetObject();

Value v;
doc.AddMember("array1", v, doc.GetAllocator());
doc["array1"].SetArray();

for (int i = 0; i < 2; i++) {

    Value obj;

    doc["array1"].PushBack(obj, doc.GetAllocator());
    doc["array1"][i].SetObject();

    Value arrayOfObj;

    doc["array1"][i].AddMember("array2", arrayOfObj, doc.GetAllocator());
    doc["array1"][i]["array2"].SetArray();

    for (int j = 0; j < 2; j++) {

        Value obj1;

        doc["array1"][i]["array2"].PushBack(obj1, doc.GetAllocator());
        doc["array1"][i]["array2"][j].SetObject();
    }
}

StringBuffer buffer;
PrettyWriter<StringBuffer> writer(buffer);
doc.Accept(writer);

std::cout << buffer.GetString() << std::endl;
```

**output:**
```
{
    "array1":
    [
        {
            "array2":
                [
                    {},
                    null
                ]
        },
        null
    ]
}
```

**expected output:**
```
{
    "array1":
    [
        {
            "array2":
                [
                    {},
                    {}
                ]
        },
        {
            "array2":
                [
                    {},
                    {}
                ]
        },
    ]
}
```

**Comment by miloyip** [comment]
Do the game run on OS X or iOS? Do both have the same problem?
32-bit or 64-bit?

**Comment by laoyur** [comment]
Maybe it's a stupid decision to mix two copies of rapidjson source in one project.
I end up with using the built-in old version from cocos2dx and everything runs well.

**Comment by pah** [comment]
You can try to define your own `RAPIDJSON_NAMESPACE` macros to embed RapidJSON 1.0.1 next to the old RapidJSON library in the application. See [here][1].

[1]: https://miloyip.github.io/rapidjson/group___r_a_p_i_d_j_s_o_n___c_o_n_f_i_g.html#ga743a79d3af927391fe3eb5c979136899
