### ISSUE TITLE
Parsing nested objects

### ISSUE THREAD

**Issue by kartikkumar** [miloyip/rapidjson#336]
Hi all,

I'm struggling to parse a JSON file that has nested objects. Below is a short example of the type of input file that I'm trying to parse:

```json
{
"parameterA" : "valueA",
"parameterB" : [{"status": true, "B_1": 2.116, "B_2": 3}],
"parameterC" : 1.23456
}
```

At the moment, to parse a simple file, I read the whole input into a string and parse it using the `Parse()` function in the `Document` class.

I can access the top level parameters as `document["parameterA"]` or using the `FindMember()` function without any problems, but I haven't found a simple way to parse and access the parameters in the nested object in `parameterB`.

I've found these two threads that discuss this topic:
 
- http://stackoverflow.com/questions/12742840/retrieving-a-nested-object-inside-a-json-string-using-rapidjson
- http://stackoverflow.com/questions/10037778/rapidjson-library-getting-a-value-inside-an-array-by-its-index

I can't really seem to decipher what I need to do. I was presuming that the `Parse()` function would parse the input so that I could access parameters as `document["parameterB"]["status"]`, but that doesn't seem to be the case.

Does anyone have a succinct way of parsing and accessing data in nested objects?

Thanks in advance!

**Comment by miloyip** [comment]
By using `Document::Parse()`, the whole JSON is fully parsed and stored it into `Document`.

Since `parameterB`'s value is an array (note the `[...]`), querying `status` require accessing the first element of it, e.g.
~~~cpp
assert(document["parameterB"][0]["status"].GetBool() == true);
~~~

For this JSON, I think it may have multiple elements in `parameterB`, otherwise it don't need to be an array. If this is the case, you can traverse the array:
~~~cpp
Value& parameterB = document["parameterB"];
assert(parameterB.IsArray());
for (SizeType i = 0; i < parameterB.Size(); i++) {
    // work with parameterB[i]["status"], parameterB[i]["B_1"], etc.
}
~~~

Another syntax is to use iterator:
~~~
for (Value::ConstValueIterator itr = parameterB.Begin(); itr = parameterB.End(); ++itr) {
    // work with (*itr)["status"], etc.
}
~~~

**Comment by kartikkumar** [comment]
Great, thanks! 

One last question, the way that I ascertain that `parameterB` exists at the moment is that I have a `find()` function that wraps `FindMember()`:

```c
//! Find parameter.
ConfigIterator find( const rapidjson::Document& config, const std::string& parameterName )
{
    const ConfigIterator iterator = config.FindMember( parameterName.c_str( ) );
    if ( iterator == config.MemberEnd( ) )
    {
        std::ostringstream error;
        error << "ERROR: \"" << parameterName << "\" missing from config file!";
        throw std::runtime_error( error.str( ) );
    }
    return iterator;
}
```
 If the key is found, the function returns an iterator to it and otherwise it throws an exception.

In this case, after running `find( document, "parameterB")`, I'd like to then run something like `find( parameterBIterator, "status")`.

Is there a way that I can set up my code to use the same/similar `find()` function for `status`?

**Comment by miloyip** [comment]
You can do something like `find(parameterBIterator->value, "status")`. But be aware that `parameterB` is an array, not an object.

Besides, you may be interested in our newly developed feature: JSON Pointer. http://miloyip.github.io/rapidjson/md_doc_pointer.html

**Comment by kartikkumar** [comment]
Ah yes, very cool. I just realised that for my current input file `parameterB` doesn't have to be an array indeed. So I've just set the value to the object directly. I'll try to figure out if I can use the JSON Pointer feature instead. I just need to figure out how to throw an appropriate exception if the key can't be found in the document.

Thanks for all your help!

**Comment by samunns** [comment]
What if you do not know what is in the JSON.  Example below contains a nested JSON (from a file):
{
    "parameter1": {
        "parameter2": {
            "parameterA": "valueA",
            "parameterB": "valueB",
            "parameterC": "valueC"
        }
    }
}

How do I retrieve each member independently whether I know it is nested or not?  The example above assumes you know "parameterB" as you have used "assert" to 

Value& parameterB = document["parameterB"];
assert(parameterB.IsArray());

But with my example code when you use the "ConstValueIterator" to loop through you will only get the first object, then it will stop as you hit another object.  Am I correct in stating that?  Or am I missing something?

**Comment by miloyip** [comment]
You can use `Begin()` and `End()` for iterating arrays.
Similarly, use `MemberBegin() and `MemberEnd()` for iterating objects.
You  can refer to the [Tutorial](http://rapidjson.org/md_doc_tutorial.html#QueryObject).

**Comment by samunns** [comment]
I have used the tutorial and the code in there as well:

static const char* kTypeNames[] = { "Null", "False", "True", "Object",
"Array", "String", "Number" };
for (Value::ConstMemberIterator itr = document.MemberBegin(); itr !=
document.MemberEnd(); ++itr)
{
printf("Type of member %s is %s\n",itr->name.GetString(),
kTypeNames[itr->value.GetType()]);


I have a file that contains nested objects.  The problem is that it prints
out the first object but nothing else (I thought it would print out
everything cause even the nested objects are part of the first object).
I have also used the "reader" and the "handler" to print our the key-string
pairs.  What I am trying to do is convert JSON to XML, but my c++ skills
are lacking.  I was trying to Parse the JSON to a DOM, then have access to
the items to convert to XML.  I have also thought about a custom handler.

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
This is pretty amazing that while the essence of JSON is to be hierarchical and support nesting, this _library for parsing JSON_ _**does not**_ have the hierarchy and nesting in its abstractions. It is a pretty unique decision to do it in this way, I think. How does one even come with such a decision.

**Comment by xhuvom** [comment]
I am trying to parse a JSON value within multiple nested array, i.e. the string value of `"description"` within `"textAnnotations"` in `"responses"` array. Looking for suggestions in this regard.
`{
  "responses": [
    {
      "textAnnotations": [
        {
          "locale": "bn",
          "description": "টিকা\n",
          "boundingPoly": {
            "vertices": [
              {
                "x": 88,
                "y": 58
              },
              {
                "x": 160,
                "y": 58
              },
              {
                "x": 160,
                "y": 93
              },
              {
                "x": 88,
                "y": 93
              }
            ]
          }
        },
        {
          "description": "টিকা",
          "boundingPoly": {
            "vertices": [
              {
                "x": 91,
                "y": 58
              },
              {
                "x": 160,
                "y": 65
              },
              {
                "x": 157,
                "y": 93
              },
              {
                "x": 88,
                "y": 86
              }
            ]
          }
        }
      ],
      "fullTextAnnotation": {
        "pages": [
          {
            "property": {
              "detectedLanguages": [
                {
                  "languageCode": "bn"
                }
              ]
            },
            "width": 280,
            "height": 124,
            "blocks": [
              {
                "property": {
                  "detectedLanguages": [
                    {
                      "languageCode": "bn"
                    }
                  ]
                },
                "boundingBox": {
                  "vertices": [
                    {
                      "x": 91,
                      "y": 58
                    },
                    {
                      "x": 160,
                      "y": 65
                    },
                    {
                      "x": 157,
                      "y": 93
                    },
                    {
                      "x": 88,
                      "y": 86
                    }
                  ]
                },
                "paragraphs": [
                  {
                    "property": {
                      "detectedLanguages": [
                        {
                          "languageCode": "bn"
                        }
                      ]
                    },
                    "boundingBox": {
                      "vertices": [
                        {
                          "x": 91,
                          "y": 58
                        },
                        {
                          "x": 160,
                          "y": 65
                        },
                        {
                          "x": 157,
                          "y": 93
                        },
                        {
                          "x": 88,
                          "y": 86
                        }
                      ]
                    },
                    "words": [
                      {
                        "property": {
                          "detectedLanguages": [
                            {
                              "languageCode": "bn"
                            }
                          ]
                        },
                        "boundingBox": {
                          "vertices": [
                            {
                              "x": 91,
                              "y": 58
                            },
                            {
                              "x": 160,
                              "y": 65
                            },
                            {
                              "x": 157,
                              "y": 93
                            },
                            {
                              "x": 88,
                              "y": 86
                            }
                          ]
                        },
                        "symbols": [
                          {
                            "property": {
                              "detectedLanguages": [
                                {
                                  "languageCode": "bn"
                                }
                              ]
                            },
                            "boundingBox": {
                              "vertices": [
                                {
                                  "x": 91,
                                  "y": 58
                                },
                                {
                                  "x": 117,
                                  "y": 61
                                },
                                {
                                  "x": 114,
                                  "y": 89
                                },
                                {
                                  "x": 88,
                                  "y": 86
                                }
                              ]
                            },
                            "text": "ট"
                          },
                          {
                            "property": {
                              "detectedLanguages": [
                                {
                                  "languageCode": "bn"
                                }
                              ]
                            },
                            "boundingBox": {
                              "vertices": [
                                {
                                  "x": 91,
                                  "y": 58
                                },
                                {
                                  "x": 117,
                                  "y": 61
                                },
                                {
                                  "x": 114,
                                  "y": 89
                                },
                                {
                                  "x": 88,
                                  "y": 86
                                }
                              ]
                            },
                            "text": "ি"
                          },
                          {
                            "property": {
                              "detectedLanguages": [
                                {
                                  "languageCode": "bn"
                                }
                              ]
                            },
                            "boundingBox": {
                              "vertices": [
                                {
                                  "x": 122,
                                  "y": 61
                                },
                                {
                                  "x": 160,
                                  "y": 65
                                },
                                {
                                  "x": 157,
                                  "y": 93
                                },
                                {
                                  "x": 119,
                                  "y": 89
                                }
                              ]
                            },
                            "text": "ক"
                          },
                          {
                            "property": {
                              "detectedLanguages": [
                                {
                                  "languageCode": "bn"
                                }
                              ],
                              "detectedBreak": {
                                "type": "LINE_BREAK"
                              }
                            },
                            "boundingBox": {
                              "vertices": [
                                {
                                  "x": 122,
                                  "y": 61
                                },
                                {
                                  "x": 160,
                                  "y": 65
                                },
                                {
                                  "x": 157,
                                  "y": 93
                                },
                                {
                                  "x": 119,
                                  "y": 89
                                }
                              ]
                            },
                            "text": "া"
                          }
                        ]
                      }
                    ]
                  }
                ],
                "blockType": "TEXT"
              }
            ]
          }
        ],
        "text": "টিকা\n"
      }
    }
  ]
}`

**Comment by R-K-1** [comment]
Here is what ended up working

    const Value& prog = d["prog"];
    for (Value::ConstValueIterator p = prog.Begin(); p != prog.End(); ++p) {
        std:cout << (*p)["iUniqueID"].GetInt();
        const Value& inFiles = (*p)["inFiles"];
        for (Value::ConstValueIterator inFile = inFiles.Begin(); inFile != prog.End(); ++inFile) {
            std::cout << (*inFile)["sFileType"].GetString() << std::endl;
            std::cout << (*inFile)["pos"]["x1"].GetInt() << std::endl;
        }
    }

The post [here][1] helped tremendously.


  [1]: https://github.com/Tencent/rapidjson/issues/336
