### ISSUE TITLE
Update examples and docs or add support VS

### ISSUE THREAD

**Issue by vladkens** [miloyip/rapidjson#338]
In https://github.com/miloyip/rapidjson/blob/master/example/simpledom/simpledom.cpp i got error:

    error C2783: 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::Parse(const char *)': could not deduce template argument for 'parseFlags'

To fix this need add call Document::Parse with template argument `d.Parse<0>(json)` or add default values on template arguments:

    // document.h, line 741
    template <unsigned parseFlags = 0>
    GenericDocument& Parse(const Ch* str) { ... }

The second solution is prefer and there is no need change examples and docs in this case.

**Comment by miloyip** [comment]
https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/document.h#L1826

It looks strange, as `Document::Parse(const Ch* str)` (without template argument) is exist. And all examples can be compiled correctly as in [Travis-CI](https://travis-ci.org/miloyip/rapidjson). 

Is it possible that you are using a very old version of RapidJSON (0.1x)? Or that was in the include path so the examples include those old headers?

From v1.0, there are version macros (`RAPIDJSON_MAJOR_VERSION`, etc.) in the `rapidjson.h`. You can print out the macros if you are unsure which header has been included.

**Comment by vladkens** [comment]
Hmm, sorry. I download lib from NuGet and there really old version.
