### ISSUE TITLE
encode do not meet expectations when string has U+0000

### ISSUE THREAD

**Issue by redfoxli** [miloyip/rapidjson#344]
I write a php extension base rapidjson, but has some problem

If the string own  U+0000, the result will be  truncation.

such as use writer->String to deal data ： \u047eJ\u0000S\u0000\u3a44\u625c

I read the code of rapidjson, I find get the len of string by function: internal::StrLen(str) 

but StrLen treats `\0' as the terminator symbol

so the len of string is not right, then the result is not meet expectations

Whether it is in accordance with the design?

I think it can provide length as a parameter to solve this problem

```
bool String(const Ch* str) { return String(str, internal::StrLen(str)); }  

template <typename Ch>
inline SizeType StrLen(const Ch* s) { 
    const Ch* p = s;
    while (*p) ++p;
    return SizeType(p - s);
}

```

**Comment by redfoxli** [comment]
sorry, my mistake
It can call other function of String to solve this problem

```
    bool String(const Ch* str, SizeType length, bool copy = false) {
        (void)copy;
        Prefix(kStringType);  
        return WriteString(str, length);
    } 

```

**Comment by miloyip** [comment]
It will be great if your extension will be open sourced.
Please tell us if someday it happens :smile:
