### ISSUE TITLE
Escaped solidus not supported by parser

### ISSUE THREAD

**Issue by sleso** [miloyip/rapidjson#347]
A string value that contains an escaped solidus, e.g. "ABC\/DEF" should be interpreted as "ABC/DEF" when parsed, according to the JSON standard:

http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

9 String
A string is a sequence of Unicode code points wrapped with quotation marks (U+0022). All characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark (U+0022), reverse solidus (U+005C), and the control characters U+0000 to U+001F. There are two-character escape sequence representations of some characters.
[...]
\/  represents the solidus character (U+002F).  
[...]

Rapdjson 1.0.0 instead maintains the \ when parsing, the result being the string "ABC\/DEF".
Of course it is allowed to not escape the solidus in strings in Json, but since the standard explicitly allows the escaped solidus and some applications use this feature when creating a Json file, the parser should also be able to interpret it correctly in my opinion.

**Comment by miloyip** [comment]
Escaped solidus is supported. I also tried to reproduce your example but it shows that RapidJSON is correct:

~~~cpp
TEST(Document, Issue347) {
    Document d;
    d.Parse("\"ABC\\/DEF\"");
    EXPECT_FALSE(d.HasParseError());
    EXPECT_STREQ("ABC/DEF", d.GetString());
}
~~~

**Comment by sleso** [comment]
Thanks for the fast response and my apologies! You're right, RapidJSON treats the escaped solidus correctly. The false alarm was raised by a bug in our (test) code. Sorry for any inconvenience caused!
