### ISSUE TITLE
some doc pages 404

### ISSUE THREAD

**Issue by tczengming** [miloyip/rapidjson#351]
in page https://github.com/miloyip/rapidjson/blob/master/doc/tutorial.md
Streams links to
https://github.com/miloyip/rapidjson/blob/master/doc/doc/stream.md
but correct link is
https://github.com/miloyip/rapidjson/blob/master/doc/stream.md
the other pages have the same issuse

**Comment by miloyip** [comment]
It is a problem of relative path in doxygen. The links are so in order to make the generated [page](http://miloyip.github.io/rapidjson/md_doc_tutorial.html) correct. I cannot make both doing correctly. Please view the generated manual.

If anyone find out solutions to solve it, please tell us.
