### ISSUE TITLE
Why member iterator is random access one?

### ISSUE THREAD

**Issue by andgur** [miloyip/rapidjson#352]
JSON object is an unordered collection of name-value pairs. Once so, why member iterators are random access type? I believe they should be bidirectional, same as, for example, in std::map.
Or, do I misunderstand something?

**Comment by Bu11etmagnet** [comment]
This is yet another example of the implementation leaking out to the interface. Internally, rapidjson stores members in a contiguous array (a poor man's vector).

**Comment by andgur** [comment]
This explains it, but does not justify. I believe that this should be downgraded to bidirectional one.
There is a related issue - RemoveMember versus EraseMember methods of GenericValue, where the latter "preserves the order of members" (of an unordered collection?)

**Comment by miloyip** [comment]
As I understand, unordered collection does not imply that it cannot be randomly accessed. And actually members are not really unordered, as it needed to preserve the order of the original JSON in roundtrip.

I am unsure if @pah chose random iterator for particular purpose.

By the way, as @Bu11etmagnet mentioned, RapidJSON uses a `vector` like storage for members. There can be alternatives, as discussed in #102.

**Comment by pah** [comment]
I agree with @miloyip's comments.

The rationale for defining the `GenericMemberIterator` as random iterator was mainly a performance choice: The implementation currently fulfills the required guarantees, so why not taking advantage of that?

Regarding @Bu11etmagnet's comment about exposing implementation details: Yes, this is correct. Applications should not rely on this guarantee to be maintained indefinitely, especially with respect to potential future changes outlined in #102. But I don't see this as an issue, as RapidJSON is a header-only library, which exposes its whole implementation to its clients anyhow.

Thanks, Philipp

**Comment by andgur** [comment]
I did not expect that public API can have anything to do with performance.
If so, all right, let it be...

**Comment by pah** [comment]
Algorithms can optimize based on the iterator category. Search for "iterator tag dispatch".
