### ISSUE TITLE
Why allocators are templated and not defined as an interface

### ISSUE THREAD

**Issue by ditashi** [miloyip/rapidjson#355]
This is a general inquiry, I'm trying to understand why allocators for values / documents were set as templated classes in lieu of defining an interface for them.

Since the allocators rapidjson is using are already adhering to some interface (Malloc / Realloc / Free) it shouldn't be such an effort to use inheritance here instead of templating, true runtime validation might impact the epic performance of rapidjson but it might make it easier to implement new allocators as I have found myself doing (mainly for benchmarking purposes).

Since at this moment, I can not use allocator B on a value / document already instantiated with a template argument of allocator A (it might be a dubious attempt but I see not reason it shouldn't be allowed). 

Could you shed some light on why you decided to implement allocators via template arguments instead of the proposed route?

**Comment by wingc-china** [comment]
Technically using template or inheritance does not limit how customize an allocator.

Take a look at the template class MemoryPoolAllocator which takes a template parameter CrtAllocator. You can implement your own allocator template class following that.

Then when you need to use GenericValue or GenericDocument pass in your own allocator template class as parameter after encoding you will get your allocator work as easy as GenericDocument<UTF16<>, YOUR_ALLOCATOR<> >.

Hope this could help. Or probably I don't fully get your question yet. In that way please elaborate. Thanks!

**Comment by miloyip** [comment]
I can think of:

1. Performance. Runtime polymorphism increase overheads in runtime. `MemoryPoolAllocator:Free()` is actually an empty function. If it is a virtual function it must be called and just simply return. These may be subtle but still an important factor.

2. Instantiation. `Document` (actually the `internal::Stack` inside it) need to create a concrete allocator instance. So it is necessary to specify the actual type, or let user pass the instance, or need some kind of object factory to create the allocator in runtime.

Also, the template solution is basically more flexible. You can even create polymorphism with the current template solution. For example, you can define a polymorphic `AllocatorBase`, which contains virtual functions .And then make concrete allocator classes inherit from it. `Document` only care about if the `Allocator` provides the 3 functions. (Though the static member function `Free()` is more tricky.)

By the way, we also notice the problem of interop issue between `GenericValue` of different allocators.  Some member functions can work with this, e.g.

~~~cpp
template <typename Encoding, typename Allocator = MemoryPoolAllocator<> > 
class GenericValue {
public:
    // ...

    template< typename SourceAllocator >
    GenericValue(const GenericValue<Encoding, SourceAllocator>& rhs, Allocator & allocator);

    template <typename SourceAllocator>
    GenericValue& CopyFrom(const GenericValue<Encoding, SourceAllocator>& rhs, Allocator& allocator);

    template <typename SourceAllocator>
    bool operator==(const GenericValue<Encoding, SourceAllocator>& rhs) const;
};
~~~

If `GenericValue` are having same encoding, they can be worked together with above functions.

**Comment by ditashi** [comment]
Thank you for your clarifying this.
Performance issues aside I am still unsure of the interop issues you're referring to, granted two values use the same encoding how does using different allocators types might interfere with the normal usage of GenericValue (granted these allocator instances are guaranteed to live long enough and not get destroyed before the value does)? 

Also regarding the instantiation bullet, using an interface should not interfere with the use of Document since you are already using a default template argument for a concrete class, so could using a polymorphic BaseAllocator (without the use of templates) be used and a default MemoryPoolAllocator satisfying that interface could be used as a default value.

**Comment by miloyip** [comment]
If `a` and `b` are of different `GenericValue` types, and `CopyFrom()` is a non-template member function, `a.CopyFrom(b)` cannot work.

So you need to pass an instance of `MemoryPoolAllocator` to `Document`'s constructor. It is possible as I said. However, currently `Document` will instaniate an self-owned allocator, if user does not supply one. In this case, `Document` must know what concrete class to be instantiated.

**Comment by miloyip** [comment]
Just leaving an additional comment before closing this.
If two values are just different from their allocator types, they can still be tested for equality by:

~~~cpp
template <typename SourceAllocator>
bool GenericValue::operator==(const GenericValue<Encoding, SourceAllocator>& rhs) const;
~~~

You may need to make functions as template functions when they need to work with different encodings and/or allocator types.
