### ISSUE TITLE
RapidJSON NuGet is outdated

### ISSUE THREAD

**Issue by rafaelwinter** [miloyip/rapidjson#357]
There is a NuGet package for RapidJSON, but it is older than my granny: `0.11.0`.
Package link: https://www.nuget.org/packages/rapidjson/

I downloaded it directly from Visual Studio and couldn't use it even to compile the sample that is in the documentation's first page. Is it possible to update the package, or if you don't plan to support it, can you remove it from the NuGet repo?

**Comment by miloyip** [comment]
I found out that the maintainer is @leonardosantos .
I will first try to contact him and see if he would like to maintain it.

**Comment by jking777** [comment]
fyi, the NuGet package is still at 0.11.0.  I hope you can get it updated.

**Comment by miloyip** [comment]
There is an update of 1.0.2 now.
