### ISSUE TITLE
Address which is not 16-bytes aligned causes access violation

### ISSUE THREAD

**Issue by imearlybird** [miloyip/rapidjson#358]
In include\rapidjson\reader.h, line 273

    static const char whitespace[16] = " \n\r\t";
    const __m128i w = _mm_load_si128((const __m128i *)&whitespace[0]);

On windows platform, sometimes whitespace is NOT 16-bytes aligned, that causes access violation while invoking _mm_load_si128.
I change it to 
__declspec(align(16)) static const char whitespace[16] = " \n\r\t";
It works.

**Comment by miloyip** [comment]
I change it to `_mm_loadu_si128()` as in the SSE2 version.

**Comment by miloyip** [comment]
Thank you for reporting.
