### ISSUE TITLE
Array memory deallocation

### ISSUE THREAD

**Issue by cedricve** [miloyip/rapidjson#361]
I'm having some memory issues.

The situation:

In my current setup I’ve created a new object, and added value members and an array member to it. The object is passed by reference to multiple functions and used in the flow of my program.

    JSONValue::Value data;
    data.SetObject();

    while(...)
    {
       ... calculation of rectangle and numberOfChanges vars

        // --------------------------
        // Add coordinates to object

        JSON::AllocatorType& allocator = data.GetAllocator();

        JSONValue region;
        region.SetArray();
        region.PushBack(rectangle.m_x1, allocator);
        region.PushBack(rectangle.m_y1, allocator);
        region.PushBack(rectangle.m_x2, allocator);
        region.PushBack(rectangle.m_y2, allocator);

        data.AddMember("regionCoordinates", region, allocator);

        // --------------------------
        // Add number of changes

        data.AddMember("numberOfChanges", numberOfChanges, allocator);

        ... call function and pass data
        ... call function2 and pass data

        if(data.MemberBegin() != data.MemberEnd())
        {
            data.EraseMember(data.MemberBegin(), data.MemberEnd());
        }
    }

I’m using the same object in a loop, and thus erasing the members of the object before I’m adding the members again. I’m using the EraseMember function for this. However I’ve noticed that this function isn’t releasing the memory of the array member, and thus leaks memory.

How can I make rapidjson to release the complete object with all it members?

**Comment by Kosta-Github** [comment]
The memory is freed when the object `data` runs out of its scope.

**Comment by cedricve** [comment]
True, but I would expect that `EraseMember` call the destructor of the Array member.

**Comment by miloyip** [comment]
The destructor is called but the default `MemoryPoolAllocator` do not release memory immediately.

You may use `GenericDocument<UTF8<>, CrtAllocator>` instead, but with performance overhead for actually releasing memory.
