### ISSUE TITLE
Truncate Double Values

### ISSUE THREAD

**Issue by nightmouse** [miloyip/rapidjson#362]
It'd be nice if the GenericValue::Double() method took a default parameter to truncate double values:

v.Double(12.529999732971191);    ---> 12.529999732971191
v.Double(12.529999732971191, 3) ---> 12.529

**Comment by miloyip** [comment]
I am not sure if this feature should be added. There are different ways to do the "truncations" or "rounding".

I think, a way of doing this externally is:

~~~cpp
double RoundDecimal(double d, double p) {
    std::round(d * p) / p;
}

double TruncDecimal(double d, double p) {
    std::trunc(d * p) / p; // C++11
}

v.Double(RoundDecimal(12.529999732971191, 1000.0)); // 12.530
v.Double(TruncDecimal(12.529999732971191, 1000.0)); // 12.529
~~~

But if this is really common, I think it is also possible to add this feature, which may also reduces some  computation overheads.

**Comment by nightmouse** [comment]
I tried your suggestion with a different implementation.  Given the following:
Value v;
double x = -3.18842;
v.Double(Truncate(x, 3));

In the JSON document, v was written as -3.188000202178955.

**Comment by miloyip** [comment]
Can you show your implementation?
Actually, this feature is a bit complicated, since rounding/trancation has quite some options. For example, currently it will generate scientific notation for some range of exponents(like %g). Should trancation applies to the mantissa or the actual decimals?

**Comment by nightmouse** [comment]
Sure, this is a temporary solution I put together.  It seems to work with cout, but only 0-5 decimal places.

    template<unsigned decimals>
    double Truncate(double val)
    {
          double devisor = 1.0;
          for(int i=0; i!=decimals; i++)
              devisor /= 10;
          return val - fmod(val, devisor);
    }

cout << Truncate<2>(3.141596) << endl;  // 3.14 

I work for a company that uses your excellent library to encode scientific data.  For our purposes, we're only interested in truncating decimal places.  The accuracy of 7 decimal places generally isn't repeatable across platforms, so the remaining digits have no use for us.  

Regarding scientific notation, I'm not sure it's important to use.  We're wanting to truncate mainly to save some bytes and parse time in javascript.  Some of our documents are 4MB in size and in a few examples truncating to 3 decimal places saved us 1.1MB.

**Comment by bbassett17** [comment]
Truncating is a need for our software.  We have values with 3 significant decimal places.  I have not found a way using the Writer.Double method to print them rounded and truncated to 3 decimal places.

**Comment by miloyip** [comment]
Added in PR #536. 
The current implementation simply truncate decimal places (not rounding, not significant digits).
Please review.
