### ISSUE TITLE
Escape policy

### ISSUE THREAD

**Issue by cerevra** [miloyip/rapidjson#364]
Hi!
Is there any opportunity to set strict policy for UTF8-to-ASCII escaping?
For example, I need to escape symbol '/'

May be it is acceptable to set user defined list for extended escaping?
Thank you

**Comment by miloyip** [comment]
I think your question is how to make `Writer` to escape character such as `/`.
Currently there is no such feature. You may modify the `escape` array in `Writer::WriteString()`.
Another possibility is to make a custom stream (actually like a filter) that escapes `/`.

**Comment by cerevra** [comment]
Thank you
What do you think? Does project need such feature? I could implement it.

**Comment by miloyip** [comment]
I am not sure whether this is common actually. Why do you need to escape '/'?

Besides, I hope to follow zero overhead principle, such that adding new features would not affect performance of existing users which does not need that feature.

**Comment by cerevra** [comment]
Legacy. My reason is legacy.
Thank you for conversation

**Comment by maidamai0** [comment]
Hi, 
it seems `writer.string()` can not unescape characters:
```
rapidjson::StringBuffer buffer;
rapidjson::Writer<StringBuffer> writer(buffer);
writer.StartObject();
writer.String("Reason");
writer.String("\"escape quote\"");
writer.EndObject();
```

with `buffer.GetString()` I get `\"escape quote\"` instead of `"escape quote"`
did I miss something?

**Comment by miloyip** [comment]
@maidamai0 This is the correct behavior.
If you need unescaping a string in a JSON, you should parse the JSON instead.
