### ISSUE TITLE
How to clear-and-minimize a document?

### ISSUE THREAD

**Issue by mloskot** [miloyip/rapidjson#368]
The documentation clearly explains that neither `RemoveAllMembers` (of object) nor `Clear` (an array) deallocate, so they leave capacity unchanged.

What is the equivalent of clear-and-minimize of standard container?
```
std::vector<T>().swap (v); // or clear followed by shrink_to_fit
```

Is there any recommended way different than the following?
```
Document d;
... // build DOM
d.SetObject();  // clear and minimize
```

**Comment by miloyip** [comment]
All `SetXXX()` calls destructor which deallocates data.
`d.Swap(Value(kObjectType).Move())` should work as well.

**Comment by mloskot** [comment]
Thanks!

**Comment by pah** [comment]
It's probably shorter to write
```cpp
Value(kObjectType).Swap(d); // keeps stack and allocator of "d"
```
That said, I think it's useful to add an explicit `Swap()` function to `GenericDocument` as well, allowing to fully free the memory even in case of a `MemoryPoolAllocator`.
```cpp
Document().Swap(d).SetObject(); // minimize and recreate allocator
Document(kObjectType).Swap(d); // after merging #369
```

**Comment by mloskot** [comment]
:+1: for the explicit `Document::Swap`

**Comment by amilcarlucas** [comment]
To clear and minimize the document I have the following code
```
    if (doc->GetAllocator().Size() > 65536) {
        // force a memory garbage collection, if it requires more than one (default 65KB) block
        rapidjson::Document d; // new temp document
        doc->Swap(d).SetObject(); // minimize and recreate allocator
        d.Swap(*doc);
    }
```
I expect that `doc->GetAllocator().Size()` never grows past 65KiB, but it does.
We never destroy the `doc` document, and we constantly modify it's values.

If `Swap()` is not a solution, then what is?

**Comment by amilcarlucas** [comment]
OK, I got the solution now:
```
  rapidjson::Document* d = new rapidjson::Document;
 ...
  while(1) {
    ...
    change the contents of the doc
    ... 
    if (doc->GetAllocator().Size() > ALLOCATOR_MAX_SIZE) {
        // force a memory garbage collection, if it requires more than one (default 65KB) block
        rapidjson::Document d;
        d.CopyFrom(*doc, d.GetAllocator());
        delete(doc);        // delete it to fully dealocate the memory
        doc = new rapidjson::Document;
        doc->Swap(d);       // now put the clean data back in the document
        printf("Avoided a 65KiB memory leak in doc datastructure");
    }
...
more code
...
}
delete(doc);
```
