### ISSUE TITLE
about mips architecture problem

### ISSUE THREAD

**Issue by BalckCat** [miloyip/rapidjson#370]
Hi,rapidjson is a nice project,it is very easy to use,and gave me much advantage in my work.but there is a problem confuse me a few days.I had used rapidjson in pc and a machine with linux,there is no ERROR,but in other machine(mips architecture,32bit,with FPU) with linux os got a "bus error" when I called Document::Parse method,same code but different result.Then I added the -msoft-float macro in my makefile,it didnt crush unexpectedly! I want to know that how to avoid the bus error when I use -mhard-float macro,is there any work I must to do?

**Comment by miloyip** [comment]
Can you give us more information, such as the JSON data the backtrace when it is crashed?

**Comment by miloyip** [comment]
Besides, you may try to build and run the unit tests.

**Comment by pah** [comment]
As it is related to hard- vs. soft-float, could it be an alignment issue? 
Does it help to define `RAPIDJSON_ALIGN` before including RapidJSON?
```cpp
#define RAPIDJSON_ALIGN(x) ((x + 7u) & ~7u) // align on 8-byte boundary for -mhard-float
#include <rapidjson/...>
```
or on the command-line (including the single quotes)
```sh
... -D'RAPIDJSON_ALIGN(x)=((x + 7u) & ~7u)'
```

**Comment by BalckCat** [comment]
It works when I added -D'RAPIDJSON_ALIGN(x)=((x + 7u) & ~7u)' macro in my project.Now, every thing is ok!Thank you very much indeed!

**Comment by miloyip** [comment]
Will it be possible to detect this with macros on your platform/compiler combination?
So that it will solve the problem for others also.
