### ISSUE TITLE
iterate objects inside array

### ISSUE THREAD

**Issue by venkateshpappu** [miloyip/rapidjson#371]
"audios":[{"id":"509699","url":"/sapi/download/audio?","viewurl":"/sapi/download/audio?","date":1431011235730,"creationdate":1431011191000,"modificationdate":1411789592000,"size":6152204,"name":"Cranberries - Zombie.mp3","metadata":{"genre":"Pop","duration":"307610","formatname":"mp3","title":"Zombie","bitrate":"160000","artist":"Cranberries ","track_number":"01","codecname":"mp3"},

In the Above Json i can able to parse the Audios array but how can i fetch the values of "metadata" object.

**Comment by miloyip** [comment]
I firstly try to format your "JSON" and make it a valid JSON.
~~~javascript
{
    "audios":[
        {
            "id":"509699",
            "url":"/sapi/download/audio?",
            "viewurl":"/sapi/download/audio?",
            "date":1431011235730,
            "creationdate":1431011191000,
            "modificationdate":1411789592000,
            "size":6152204,
            "name":"Cranberries - Zombie.mp3",
            "metadata":{
                "genre":"Pop",
                "duration":"307610",
                "formatname":"mp3",
                "title":"Zombie",
                "bitrate":"160000",
                "artist":"Cranberries ",
                "track_number":"01",
                "codecname":"mp3"
            }
        }
    ]
}
~~~

If this JSON is parsed to a `Document d`, then
~~~
const Value& audios = d["audios"];
assert(audios.IsArray());
for (Value::ConstIterator itr = audios.Begin(); itr != audios.End(); ++itr) {
    const Value& metadata = (*itr)["metadata"];
    // ...
}
~~~

The above code fragment assumes `"audios"` and `"metadata"` keys exist. If it is not sure, more checking is needed.

Please read the [tutorial](http://rapidjson.org/md_doc_tutorial.html) for more information on accessing the DOM.

**Comment by venkateshpappu** [comment]
Thanks for your quick response. im already parse the json Array like below
const Value& a = d["audios"];
assert(a.IsArray());
for (SizeType i = 0; i < a.Size(); i++) // Uses SizeType instead of size_t
{
for (Value::ConstMemberIterator itr = a[i].MemberBegin(); itr != a[i].MemberEnd(); ++itr) {
//...
}
But when the Type is Object i tried to keep the loop you suggested, but it crashed. can you suggest some more about getting values inside "metadata" by example.

**Comment by mloskot** [comment]
@venkateshpappu Process your `d` document exactly as @miloyip explained, it will work as you require.

p.s. Please, learn basics of [GitHub markdown](https://help.github.com/articles/github-flavored-markdown/) and format any block code you submit.

**Comment by sinuos** [comment]
but how to get whole "metadata" object , i don't care the value in "metadata" object, can i just transfer "metadata" object as string to others

**Comment by miloyip** [comment]
@sinuos You can stringify any `Value` to a string, but the receiver may need to parse it again for using.

**Comment by ddevetak** [comment]
how can one read key values without a predefined list?

**Comment by miloyip** [comment]
Please check http://rapidjson.org/md_doc_tutorial.html#QueryObject, the `MemberBegin()` and `MemberEnd()` usage example.
