### ISSUE TITLE
Comparison to Python's ujson

### ISSUE THREAD

**Issue by OndraFiedler** [miloyip/rapidjson#375]
I am reimplementing an application from Python to C++ to achieve better performance. This application parses and writes a lot of JSON.

The Python's ujson seems to parse JSON faster then rapidjson, which surprises me. Am I doing some mistake?

Consider following code snippets:

C++:

    #include "rapidjson/document.h"
    int main()
    {
        const char* json = "{\"type\": \"test\", \"data\":{\"S84F5FQ1A3\":\"C2Z7NBJBR7\",\"XYIWLLC2UJ\":\"NIDQ0KL2YR\", ... ,\"IN5OYSOMUZ\":\"EM3AX8QFDJ\"}}";
        for(int i=0;i<5000;i++)
        {
        	rapidjson::Document d;
            d.Parse(json);
	   }
	   return 0;
	}
	
Python:

    import ujson
    for i in range(5000):
	     message = ujson.loads('{"type": "test", "data":{"S84F5FQ1A3":"C2Z7NBJBR7","XYIWLLC2UJ":"NIDQ0KL2YR", .. "IN5OYSOMUZ":"EM3AX8QFDJ"}}')

The first one runs on my computer 8.3 secons, the second one just 3.6 seconds.

The json is 26 028 characters long.
My OS is Ubuntu 14.04 LTS. Processor: AMD Turion TM X2 Dual-Core Mobile RM-74 2.2 GHz, RAM: 3.6 GB.
Compiler: g++ 4.9.2, Python: 3.4.0.

**Comment by miloyip** [comment]
What are the gcc compilation options?

**Comment by OndraFiedler** [comment]
You are right, I forgot the optimization flag! Using `-O2` flag improved the performance a lot, executing the sample code in 1.17 seconds instead of 8.3 seconds. Thanks for help ;)
