### ISSUE TITLE
License not open source because of "not evil" clause

### ISSUE THREAD

**Issue by joto** [miloyip/rapidjson#377]
Your `license.txt` includes the clause "The Software shall be used for Good, not Evil." from the terms of the JSON License. This makes this software not Open Source, which prevents it, among other things, from becoming part of any software distributed with Debian.

See https://wiki.debian.org/qa.debian.org/jsonevil for details.

Can we get rid of that part of the software so RapidJSON can officially become Open Source?

**Comment by joto** [comment]
Looking at this more closely this should only affect the files from JSON_checker. Is that right? Maybe this can be clarified somehow?

**Comment by sebastic** [comment]
@miloyip, can you confirm that only the JSON_checker code is under the problematic JSON license?

I'm waiting for clarifications on this issue before I can include software that includes RapidJSON code in Debian.

**Comment by miloyip** [comment]
Yes. JSON checker files are the only ones using that JSON license.

**Comment by sebastic** [comment]
Thansk for the confirmation, I've push a change to the license.txt to clarify the issue.
