### ISSUE TITLE
"‘rapidjson::kObjectType’ is not a type" when used inside a struct

### ISSUE THREAD

**Issue by ChicagoSchooler** [miloyip/rapidjson#379]
Dumb question, but inside a ```struct```, I have:

```c++
rapidjson::Value book(rapidjson::kObjectType);
```

which gives the error in the title.

I do not get this error elsewhere.  How can this be fixed?

**Comment by miloyip** [comment]
This code itself should not have problem. You can create a simple project to reproduce that.
Will it be the problem that `book` is defined somewhere else?

**Comment by ChicagoSchooler** [comment]
Unfortunately, a raw test gives the same error:

```c++
#include "rapidjson/document.h"

struct test_struct {
	rapidjson::Value book(rapidjson::kObjectType);
};

int main() {
	return 0;
}
```

```SetObject()``` works inside a contstructor.

Thank-you for taking the time to write this library!  It's obvious just from the syntax alone that it's a beast.

**Comment by ChicagoSchooler** [comment]
I don't think I'm screwing this up, but now I'm getting an error on ```addMember()```:

```c++
#include "rapidjson/document.h"

int main() {
	rapidjson::Value book(rapidjson::kObjectType);
	rapidjson::Document::AllocatorType allocator;
	book.addMember( "test", "test", allocator );
	return 0;
}
```

My compiler is ```gcc version 4.8.4```.  I'm compiling header-only.

**Comment by miloyip** [comment]
`book` was declared as a member function in the struct.

**Comment by ChicagoSchooler** [comment]
Ah, of course.  Excuse me.

Do you know why my last set of code is giving ```error: ‘rapidjson::Value’ has no member named ‘addMember’```?

I think I'm following [```valuetest.cpp```](https://github.com/miloyip/rapidjson/blob/c8c8ad47c372dc724cbabcbaf5c62aee4618afeb/test/unittest/valuetest.cpp#L159-L168) exactly.

**Comment by ChicagoSchooler** [comment]
Of course.  Thank you!
