### ISSUE TITLE
How to handle Parse Errors in Document?

### ISSUE THREAD

**Issue by cgmb** [miloyip/rapidjson#385]
There seem to be some issues in the documentation for handling [parse errors](https://github.com/miloyip/rapidjson/blob/823b73189601a234dfa75f387130433fe7bedd38/doc/dom.md#parse-error-parseerror). Specifically, the example code uses a `reader` variable that is not declared. Is that supposed to be the document object?

```c++
#include "rapidjson/document.h"
#include "rapidjson/error/en.h"

// ...
Document d;
if (d.Parse(json).HasParseError()) {
    fprintf(stderr, "\nError(offset %u): %s\n", 
        (unsigned)reader.GetErrorOffset(),
        GetParseError_En(reader.GetParseErrorCode()));
    // ...
}
```

I also notice that `ParseErrorCode GetParseError()` and `size_t GetParseOffet()` are listed as the functions used up near the top of that section. I didn't notice until just now, but there's a typo in `GetParseOffet`. That's not the whole story, though, because even with that corrected, they still don't match the names used in the example code. But even the example code doesn't seem to quite match the real names, either.

My working (?) code for this is:

```c++
Document d;
d.Parse(json);
if (d.HasParseError()) {
    fprintf(stderr, "\nError(offset %u): %s\n",
        (unsigned)d.GetErrorOffset(),
        GetParseError_En(d.GetParseError()));
    // ...
}
```

**Comment by miloyip** [comment]
Yes. You are correct. It was a documentation error.
I have fixed it in master branch.
Thank you.

**Comment by michcleary** [comment]
I see in reader.h of rapidjson that there seems to be some use for \n, \r, etc.  How do I parse and get error, such that it gives the correct line number/offset into that line for the error?  I'm having trouble piecing that call together.  Does rapidjson provide that already? Our json is very long, and it would be better not to have to count 1000 characters into the json to find the error.  Plus the error offset seems to be including \n in the character count of the offset.

**Comment by miloyip** [comment]
You may request this feature in a new issue. I think probably this could be created via a stream wrapper.

**Comment by michcleary** [comment]
Where would I request that?  I'm already implementing this, but was hoping that rapidjson had it already.

**Comment by miloyip** [comment]
Just create a new issue if you cannot find this in existing issues.
