### ISSUE TITLE
rapidjson call AddMemeber function error

### ISSUE THREAD

**Issue by deajosha** [miloyip/rapidjson#386]
i am a newer for rapidjson, the problem is below:
{
  rapidjson::Document d;

  rapidjson::Document::AllocatorType& allocator = d.GetAllocator();

    const char* t = "connect";
    rapidjson::Value zookeeper(rapidjson::kObjectType);

    rapidjson::Value connect("xxxx");
    zookeeper.AddMember(t, connect, allocator);
}

when i compile it using visual studio 2013, it ocurrs:
error C2664: “rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>> &rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::AddMember(rapidjson::GenericStringRef<char>,rapidjson::GenericStringRef<char>,Allocator &)”: 无法将参数 1 从“const char *”转换为“rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>> &”
1>          with
1>          [
1>              Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>.

**Comment by lifeilu** [comment]
I compile similar code in visual studio 2017，and get the same error C2664. Have u get the solution? and why it occurs?
