### ISSUE TITLE
Got issue get value from a deep nested Json object

### ISSUE THREAD

**Issue by ourlord** [miloyip/rapidjson#389]
Say I have a nested Json object shown as below. Except those field `level1`, `level2`, `level3`, `my_goal`, other fields are all generated randomly from somewhere else which I can never know its value in compile time, which needs me to use iterator. 

What would be the best way to fetch the value of `my_goal` in this case? I've already worked out a little but get stuck. My example code lists below.

```
{
  "level1" : "value",
  "level2" : {
    "qwjeqlwe" : {
      "level3" : {
        "my_goal" : "..."
        ....
      }
    } ,
    "qweq123123" : {
      "level3" : {
         "my_goal" : "..."
      }
    }
  }
}
```

```
aJsonString = ...; // As shown above
Document d;
d.Parse(aJsonString);
if (d.HasMember("level2")) 
{
  for (auto itr = d["level2"].MemberBegin(); // use auto here to save from typing
     itr != d["level2"].MemberEnd(); ++itr) 
  {
    // Got stuck here, don't know what exactly is itr point to
    if (itr["level3"].HasMemeber("my_goal")) // if this correct?
    { ... }
  }
}
```

The real scenario is even more complicated than this. So I wish to find a smart way to navigate and find the value I'm looking for. But for now, at least I know the path to the value I wish to find, i.e. `root -> level2 -> itr -> level3 -> my_goal`.

And I've found some workaround say can use `findMember` this kind of method call. But got no idea how to work with that.

**Comment by miloyip** [comment]
You need to use `(*itr)["level3"]` instead.

And it is suggested to prevent redundant queries to improve performance.

~~~
auto& level2 = d["level2"];
for (auto itr = level2.MemberBegin(); itr != level2.MemberEnd(); ++itr) {
    // ...
}
~~~

**Comment by ourlord** [comment]
Thanks for the reply. Helps me the clear some ideas. But I still got some problem with this, after using `(*itr)["level3"]`, I got a compiling issue says

```
error: no match for ‘operator[]’ in ‘aJsonIter.rapidjson::GenericMemberIterator<Const, Encoding, 
Allocator>::operator* [with bool Const = true, Encoding = rapidjson::UTF8<char>, Allocator = 
rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]()[netlogger::
<unnamed>::kWriteBackNodeHttpHttp.std::basic_string<_CharT, _Traits, _Alloc>::c_str [with _CharT 
= char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]()]'
```

And I cannot use `itr->HasMember` which reports

```
error: ‘const struct rapidjson::GenericMember<rapidjson::UTF8<char>, 
rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >’ has no member named ‘HasMember’
```

**Comment by ourlord** [comment]
The main concern from me is about how to iterate through a such Json structure: 

```
json_doc = "
{
  \"a\" : {
    \"b\" : 123,
    \"c\" : true,
    \"d\" : \"a string\"
  }
} ";
Document d;
d.Parse(json_doc);
```

When an iterator is pointing to `"a"` (I don't know how to correctly write an example code to show an iterator point to `"a"`...`it = d.MemberBegin()`? ), how to access `"b"` or `"c"` or `"d"` from the iterator ?

**Comment by ourlord** [comment]
So actually I found a workaround with the problem but not sure if it is the proper way. 

The `MemberIterator` is pointing to a `Member` object. But the way we usually access is `Value` objects.  

After briefly browsing the source codes, I change my code from `(*it)["level2"]` into `it->value["level2"]` fixed the problem. 

As a whole example, this is how to get access to the "d" in the below Json string. Remember we don't know the exact value of `"a"` in my real scenario. 

```
json_doc = "
{
  "k" : {
    \"a(unknown value)\" : {
      \"b\" : 123,
      \"c\" : true,
      \"d\" : \"a string\"
    }
  }
} ";
Document d;
d.Parse(json_doc);
// I'm not sure if can use MemberBegin() against Document so I add this "k"
const Value& k = d["k"]; 
// We don't know the exact value of "a" so we cannot use d["a"] to get access the "b","c","d"
for (auto it = k.MemberBegin(); it != k.MemberEnd(); ++it) {
  if (it->value.HasMember("d")) {
    std::cout << it->value["d"].GetString() << std::endl;
  }
}
```

Do you think if it is good to have an example showing how to use iterator in similar scenarios?

**Comment by miloyip** [comment]
Yes. Your solution is corrected.

**Comment by michcleary** [comment]
You are using value.HasMember.  Is that a typo?  You don't have a variable value.  I tried Value, and it didn't work.
