### ISSUE TITLE
rapidjson\internal/dtoa.h(104): error C4146: unary minus operator applied to unsigned type, result still unsigned

### ISSUE THREAD

**Issue by ImmortalDragonm** [miloyip/rapidjson#396]
VS 2013 x32, x64
Create new empty console project. And copy \example\tutorial\tutorial.cpp

**Comment by blackball** [comment]
Hi, I have the same issue with you today. You could add very less codes to fix this: 

Modify https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/internal/dtoa.h#L104 
like this: 
GrisuRound(buffer, *len, delta, p2, one.f, wp_w.f * kPow10[-static_cast<int>(kappa)]);

I have already created a pull request for this fix. Hope it helps.

**Comment by miloyip** [comment]
Fixed in #397
