### ISSUE TITLE
string compare fails

### ISSUE THREAD

**Issue by Sil3ntStorm** [miloyip/rapidjson#398]
```c++
Document d;
d.Parse("{ \"hello\" : \"world\", \"t\" : true , \"f\" : false, \"n\": null, \"i\":123, \"pi\": 3.1416, \"a\":[1, 2, 3, 4] }");
for (auto it = d.MemberBegin(); it != d.MemberEnd(); ++it) {
	if (it->name.GetString() == "hello")
		cout << "Should be called, never is";
	if (string(it->name.GetString()) == "hello")
		cout << "will be called";
}
```

GetString() supposedly returns a string and thus should be comparable to a string, however evidently it isn't. Printing it->name.GetString() works just fine though.

**Comment by mloskot** [comment]
> GetString() supposedly returns a string and thus should be comparable to a string

No, it should not.
`GetString` does not return a string, but pointer to character. Check the docs [here](http://rapidjson.org/classrapidjson_1_1_generic_value.html#aab763460a97e8944ddedf51203581a3b).
