### ISSUE TITLE
MemoryPoolAllocator::Realloc expands fail

### ISSUE THREAD

**Issue by jimmydashwu** [miloyip/rapidjson#399]
as the comment said, "// Simply expand it if it is the last allocation and there is sufficient space", but in unit test/allocatorstest.cpp,

uint8_t* q = (uint8_t*)a.Realloc(p, 100, 200);
do not lead to
p == q

which does not make sense.

MemoryPoolAllocator::Realloc failed in this case which does not consider RAPIDJSON_ALIGN to originalSize in allocators.cpp:

// Simply expand it if it is the last allocation and there is sufficient space
if (originalPtr == (char *)(chunkHead_) + RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + chunkHead_->size - originalSize) {

the increment may not be precise either.

size_t increment = static_cast<size_t>(newSize - originalSize);
increment = RAPIDJSON_ALIGN(increment);

**Comment by miloyip** [comment]
I cannot completely understand your point.
Can you send us a pull request on this?

**Comment by jimmydashwu** [comment]
in the unittest allocatorstest.cpp, for MemoryPoolAllocator case in TestAllocator(Allocator & a) function, after these two statements finished.

uint8_t* p = (uint8_t*)a.Malloc(100);
uint8_t* q = (uint8_t*)a.Realloc(p, 100, 200);

I think p and q should be equal, which is the "expand" case for MemoryPoolAllocator::Realloc function.

if "expand" does not occur, then MemoryPoolAllocator::Malloc and additional memcpy will be called which cause a little waste.

void* newBuffer = Malloc(newSize);
RAPIDJSON_ASSERT(newBuffer != 0);   // Do not handle out-of-memory explicitly.
if (originalSize)
      std::memcpy(newBuffer, originalPtr, originalSize);
return newBuffer;
