### ISSUE TITLE
GenericReader drops decimal digits

### ISSUE THREAD

**Issue by dasto** [miloyip/rapidjson#403]
I use a generic Reader for parsing a StringStream on Win 8.1, VS2013 Community. Some of the values passed to the Double() method of my handler aren't correct:

24.8984375 -> 24.8984
171.8984375 -> 171.8984

I already tried to use the "kParseFullPrecisionFlag" - no difference. Is this already related to resolution of doubles or is this a possible bug?

**Comment by pah** [comment]
How did you print out the values in your handler?  MSVC limits the output precision by default.
You can print the full value by using a `rapidjson::Writer` instead:
````cpp
    using namespace rapidjson;
    Document d;
    d.Parse<kParseFullPrecisionFlag>("24.8984375");
    // ...

    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    writer.Double(d.GetDouble());

    std::cout << "std::cout: " << d << "\n"
              << "rapidjson: " << buffer.GetString() << std::endl;
````
hth, 
Philipp

**Comment by dasto** [comment]
Thx Philipp,

In fact, I already used a writer. To give some more details: I want to encode a custom class hierarchy  to a JSON representation and vice versa. Therefore I know the exact values going into the process. Encoding goes like this:
```c++
	StringBuffer s;
	Writer<StringBuffer> writer(s);
	customRootObject->writeJSON(writer, jsonFlags);

```
