### ISSUE TITLE
errro when running make

### ISSUE THREAD

**Issue by chfakht** [miloyip/rapidjson#406]
Hi  i have followed the procedure in readme but when running make i get those errors 

[  2%] Building CXX object example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o
cc1plus: error: bad value (native) for -march switch
example/CMakeFiles/capitalize.dir/build.make:54: recipe for target 'example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o' failed
make[2]: *** [example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o] Error 1
CMakeFiles/Makefile2:1009: recipe for target 'example/CMakeFiles/capitalize.dir/all' failed
make[1]: *** [example/CMakeFiles/capitalize.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2

some help here plzz :)

**Comment by miloyip** [comment]
The `-march=native` seems unsupported in your compiler. Please try removing the `-march=native` in `CMakeLists.txt`. And please tell us the compiler and version that you are using. Thank you.

**Comment by chfakht** [comment]
i'm using g++ (Debian 4.6.3-14+rpi1) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
cmake version 2.8.9
i'm using raspberry pi 
when removing the flag you telled me i get this
[  2%] Building CXX object example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o
In file included from /home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:6:0:
/home/pi/yB/rapidjson/include/rapidjson/reader.h: In member function 'rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Tokenize(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch) [with SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch = char]':
/home/pi/yB/rapidjson/include/rapidjson/reader.h:1409:41:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:395:58:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/reader.h:1068:9: error: comparison is always true due to limited range of data type [-Werror=type-limits]
/home/pi/yB/rapidjson/include/rapidjson/reader.h: In member function 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 0u, SEncoding = rapidjson::UTF8<>, TEncoding = rapidjson::UTF8<>, InputStream = rapidjson::FileReadStream, OutputStream = rapidjson::FileReadStream, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]':
/home/pi/yB/rapidjson/include/rapidjson/reader.h:644:13:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:992:23:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:408:13:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/reader.h:687:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
/home/pi/yB/rapidjson/include/rapidjson/reader.h: In member function 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 0u, SEncoding = rapidjson::UTF8<>, TEncoding = rapidjson::UTF8<>, InputStream = rapidjson::FileReadStream, OutputStream = rapidjson::GenericReader<rapidjson::UTF8<>, rapidjson::UTF8<> >::StackStream<char>, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]':
/home/pi/yB/rapidjson/include/rapidjson/reader.h:653:13:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:992:23:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:408:13:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/reader.h:687:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
In file included from /home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:7:0:
/home/pi/yB/rapidjson/include/rapidjson/writer.h: In member function 'bool rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::WriteString(const Ch*, rapidjson::SizeType) [with OutputStream = rapidjson::FileWriteStream, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char, rapidjson::SizeType = unsigned int]':
/home/pi/yB/rapidjson/include/rapidjson/writer.h:125:39:   instantiated from 'bool rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::String(const Ch*, rapidjson::SizeType, bool) [with OutputStream = rapidjson::FileWriteStream, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char, rapidjson::SizeType = unsigned int]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:31:58:   instantiated from 'bool CapitalizeFilter<OutputHandler>::String(const char*, rapidjson::SizeType, bool) [with OutputHandler = rapidjson::Writer<rapidjson::FileWriteStream>, rapidjson::SizeType = unsigned int]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:649:13:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:992:23:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:408:13:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/writer.h:293:18: error: comparison is always true due to limited range of data type [-Werror=type-limits]
cc1plus: all warnings being treated as errors
example/CMakeFiles/capitalize.dir/build.make:54: recipe for target 'example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o' failed
make[2]: *** [example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o] Error 1
CMakeFiles/Makefile2:1009: recipe for target 'example/CMakeFiles/capitalize.dir/all' failed
make[1]: *** [example/CMakeFiles/capitalize.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by miloyip** [comment]
I think you may remove `-Werror` as well at this moment. I will check whether this can be solved better.

**Comment by chfakht** [comment]
i have removed -Werror but i still have erros
[  2%] Building CXX object example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o
In file included from /home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:6:0:
/home/pi/yB/rapidjson/include/rapidjson/reader.h: In member function 'rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Tokenize(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch) [with SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch = char]':
/home/pi/yB/rapidjson/include/rapidjson/reader.h:1409:41:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:395:58:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/reader.h:1068:9: error: comparison is always true due to limited range of data type [-Werror=type-limits]
/home/pi/yB/rapidjson/include/rapidjson/reader.h: In member function 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 0u, SEncoding = rapidjson::UTF8<>, TEncoding = rapidjson::UTF8<>, InputStream = rapidjson::FileReadStream, OutputStream = rapidjson::FileReadStream, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]':
/home/pi/yB/rapidjson/include/rapidjson/reader.h:644:13:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:992:23:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:408:13:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/reader.h:687:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
/home/pi/yB/rapidjson/include/rapidjson/reader.h: In member function 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 0u, SEncoding = rapidjson::UTF8<>, TEncoding = rapidjson::UTF8<>, InputStream = rapidjson::FileReadStream, OutputStream = rapidjson::GenericReader<rapidjson::UTF8<>, rapidjson::UTF8<> >::StackStream<char>, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]':
/home/pi/yB/rapidjson/include/rapidjson/reader.h:653:13:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:992:23:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:408:13:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/reader.h:687:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
In file included from /home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:7:0:
/home/pi/yB/rapidjson/include/rapidjson/writer.h: In member function 'bool rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::WriteString(const Ch*, rapidjson::SizeType) [with OutputStream = rapidjson::FileWriteStream, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char, rapidjson::SizeType = unsigned int]':
/home/pi/yB/rapidjson/include/rapidjson/writer.h:125:39:   instantiated from 'bool rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::String(const Ch*, rapidjson::SizeType, bool) [with OutputStream = rapidjson::FileWriteStream, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator, rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char, rapidjson::SizeType = unsigned int]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:31:58:   instantiated from 'bool CapitalizeFilter<OutputHandler>::String(const char*, rapidjson::SizeType, bool) [with OutputHandler = rapidjson::Writer<rapidjson::FileWriteStream>, rapidjson::SizeType = unsigned int]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:649:13:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:992:23:   instantiated from 'void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:408:13:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u, InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/include/rapidjson/reader.h:433:53:   instantiated from 'rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream, Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >, SourceEncoding = rapidjson::UTF8<>, TargetEncoding = rapidjson::UTF8<>, StackAllocator = rapidjson::CrtAllocator]'
/home/pi/yB/rapidjson/example/capitalize/capitalize.cpp:60:33:   instantiated from here
/home/pi/yB/rapidjson/include/rapidjson/writer.h:293:18: error: comparison is always true due to limited range of data type [-Werror=type-limits]
cc1plus: all warnings being treated as errors
example/CMakeFiles/capitalize.dir/build.make:54: recipe for target 'example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o' failed
make[2]: *** [example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o] Error 1
CMakeFiles/Makefile2:1009: recipe for target 'example/CMakeFiles/capitalize.dir/all' failed
make[1]: *** [example/CMakeFiles/capitalize.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by miloyip** [comment]
I found that there are 3 `CMakeLists.txt` have `-Werror`:
~~~
/Users/miloyip/github/rapidjson/CMakeLists.txt:
   27  
   28  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
   29:     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native -Wall -Wextra -Werror")
   30  elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
   31:     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native -Wall -Wextra -Werror -Wno-missing-field-initializers")
   32  elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
   33      add_definitions(-D_CRT_SECURE_NO_WARNINGS=1)

/Users/miloyip/github/rapidjson/example/CMakeLists.txt:
   19  
   20  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
   21:     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Weffc++ -Wswitch-default")
   22  elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
   23:     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Weffc++ -Wswitch-default")
   24  elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
   25      add_definitions(-D_CRT_SECURE_NO_WARNINGS=1)

/Users/miloyip/github/rapidjson/test/unittest/CMakeLists.txt:
   20  
   21  if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
   22:     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Weffc++ -Wswitch-default -Wfloat-equal")
   23  elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
   24:     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Weffc++ -Wswitch-default -Wfloat-equal -Wimplicit-fallthrough")
   25  elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
   26      add_definitions(-D_CRT_SECURE_NO_WARNINGS=1)
~~~

**Comment by najlepsiwebdesigner** [comment]
I confirm that removing flags enables compilation on raspbian. I used g++

**Comment by miloyip** [comment]
Thanks for your confirmation.
