### ISSUE TITLE
Crashing at allocators.h line 235: it appears a chunk is NULL

### ISSUE THREAD

**Issue by GatoRat** [miloyip/rapidjson#414]
We are getting periodic crashes at line 235 in allocators.h. The code in this instance is doing in insitu parsing of a fairly small packet (less than 200 characters) every two seconds.

    void AddChunk(size_t capacity) {
        if (!baseAllocator_)
            ownBaseAllocator_ = baseAllocator_ = RAPIDJSON_NEW(BaseAllocator());
        ChunkHeader* chunk = reinterpret_cast<ChunkHeader*>(baseAllocator_->Malloc(RAPIDJSON_ALIGN(sizeof(ChunkHeader)) + capacity));
        chunk->capacity = capacity; // Crashes here with c0000005, indicating that chunk is NULL
        chunk->size = 0;
        chunk->next = chunkHead_;
        chunkHead_ =  chunk;
    }

It appears the crash happens when parsing the first object in the array (I've shortened the string for illustrative purposes.) Unfortunately, we don't have the actual packet that causes the crash and my attempts to create a corrupt string have failed.

{"LevelValues":[{"LevelId":17,"Value":78.22}]}

Is there a known or suspected issue around this part of the code and/or do you have any suggestions on the cause of and possibly how to force this error?

**Comment by GatoRat** [comment]
I think I've pinned it down. Under a very edge case the object owning the buffer can get deleted, though this should never happen during processing of the Json packet. I suspect there is a case I haven't considered.

**Comment by miloyip** [comment]
If the program always parse small JSON, I will suggest using [user buffer](http://rapidjson.org/md_doc_dom.html#UserBuffer). This prevent heap allocation, thus also fragmentation.
Is it safe to close this issue?

**Comment by mloskot** [comment]
@miloyip This may be off-topic for this particular issue, I think , it would be helpful if this suggestion is available in the docs/FAQ, as part of Performance topics.

**Comment by GatoRat** [comment]
The user buffer suggestion is excellent. Thank you. Yes, close the issue.
