### ISSUE TITLE
RAPIDJSON_ALIGN gives wrong results with x > 4 GB

### ISSUE THREAD

**Issue by segmtfault** [miloyip/rapidjson#418]
In rapidjson.h, with this definition:
#ifndef RAPIDJSON_ALIGN
#if RAPIDJSON_64BIT == 1
#define RAPIDJSON_ALIGN(x) ((x + 7u) & ~7u)

~7u will generate a 32-bit bitmask (FFFF FFF8), thus giving incorrect values when x > 2^32 (4 GB).
For example, passing x = 4,901,136,555 will return 606,169,264

~7u should be changed to ~7llu (or ~7ull) to generate a 64-bit bitmask instead.

(Tested on VisualStudio 2012)

**Comment by miloyip** [comment]
Thank you for reporting this.
