### ISSUE TITLE
Build fails due to warn_unused_result in filewritestream.h

### ISSUE THREAD

**Issue by kurt-nj** [miloyip/rapidjson#420]
I'm seeing a build failure due to a "unused result" warning found in filewritestream.h. The result of the fwrite call in the Flush method is not used.

I'm building with gcc 4.8.2

```
/data/buildbot/dependencies/rapidjson-1.0.2/src/rapidjson/include/rapidjson/filewritestream.h: In member function ‘void rapidjson::FileWriteStream::Flush()’:
/data/buildbot/dependencies/rapidjson-1.0.2/src/rapidjson/include/rapidjson/filewritestream.h:60:77: error: ignoring return value of ‘size_t fwrite(const void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Werror=unused-result]
             fwrite(buffer_, 1, static_cast<size_t>(current_ - buffer_), fp_);
```

**Comment by miloyip** [comment]
I found a [discussion](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509) on gcc about this.
Do you have suggestion for resolving this?

**Comment by cosinekitty** [comment]
Hi miloyip,

That was an interesting debate to read!  :)  I didn't know about (void) not suppressing the warning.  Also interesting to read that sometimes fwrite errors are not detected until a subsequent flush.

In general, it would be a good idea to try to check for I/O errors returned by fwrite.

But I don't know this particular code base, so all I can say is, if handling an error returned by fwrite (perhaps even throwing an exception) is not a good option, then the following comment I read may be helpful:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425#c18

Specifically, try wrapping the call in a do-nothing "if" statement:

````
if (fwrite(...) < static_cast<size_t>(current_ - buffer_)) {
    // we deliberately ignore write failures because ...
}
````

**Comment by miloyip** [comment]
Would you mind test it and see if it works on your platform?
I am open for pull request on this.

**Comment by kurt-nj** [comment]
I can make a pull request for this. Also, as a note, this failure only happens when configuring with the "-DCMAKE_BUILD_TYPE=Release" flag
