### ISSUE TITLE
如何不去除json数据中的空格？

### ISSUE THREAD

**Issue by Nightaway** [miloyip/rapidjson#422]
比如一段json  {"a" : "a b c"}  那么通过rapidjson取得的key值为a的数据中空格都被删除了，如何不删除空格，保持数据原样？

**Comment by miloyip** [comment]
字符串中的空格是不会被删除的。你是指冒号前后的whitespace？

**Comment by Nightaway** [comment]
感谢回复，找到问题了。

**Comment by likunyan** [comment]
带有 \ 导致解析不了，这个怎么破
