### ISSUE TITLE
Document to String and function argument

### ISSUE THREAD

**Issue by FlorianIragne** [miloyip/rapidjson#423]
Hi,

I'm defining a rapidjson::Document as this:
    rapidjson::Document fb;
    fb.SetObject();
    rapidjson::Document::AllocatorType& allocator = fb.GetAllocator();
    fb.AddMember("command", "command", allocator);
    fb.AddMember("status", "ok", allocator);

i then log the document as a string, like this:
    rapidjson::GenericStringBuffer<rapidjson::UTF8<> > outbuffer;
    rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<> > > outwriter(outbuffer);
    fb.Accept(outwriter);
    syslog(LOG_NOTICE, outbuffer.GetString());

Then i pass this object to a function using std::move : myfunction(std::move(fb));

And i modify and display fb content in this function:
    myfunction(rapidjson::Document fb){
        rapidjson::GenericStringBuffer<rapidjson::UTF8<> > outbuffer;
        rapidjson::Writer<rapidjson::GenericStringBuffer<rapidjson::UTF8<> > > outwriter(outbuffer);
        fb.Accept(outwriter);

        fb["status"] = "ko";
        syslog(LOG_NOTICE, outbuffer.GetString());

First syslog display a json with status field = "ok", but also the second one. It seems that the status = "ko" modification is not applied.

Am i missing something? Is this a bug? Is there a simpler way to make a "toString()"?

Florian

**Comment by FlorianIragne** [comment]
After reading a bit of code, it seems that this is expected behaviour. the writer is "filled" with Document content on the "Accept" call, so that any change to the Document after that is ignored by the writer.

I would have expected the writer to really "write" the Document content upon GetString call.

Is there a more dynamic toString-like method for a Document?

**Comment by miloyip** [comment]
Yes .`fb.Accept(outwriter)` serializes `fb` into JSON via `outwriter `, and  `outwriter ` outputs the characters into the string buffer. `GetString()` is a const member function only for returning the JSON.

So, basically you should write a document into JSON, after modifying the document.
