### ISSUE TITLE
VS 2013  warning C4530

### ISSUE THREAD

**Issue by dgregorius** [miloyip/rapidjson#428]
Hi, I am using VS 2013 (Update 5) on a Windows 7 (64 bit). RTTI and Exceptions are disabled in my project. After including the document header and creating a document instance I get the following warning:

1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

I was under the impression that RapidJSON has no external dependencies including the standard library. Can I work around this warning, but defining _HAS_EXCEPTIONS_ = 0?

**Comment by wingc-china** [comment]
I don't see any RapidJSON's header file includes any standard library header directly or indirectly. Instead it's unit test code does. Probably in your case your project has too. Try set CL build option "/showIncludes" and check the build log after, you will see who includes who.

From my building experience of RapidJSON's unit test code the RapidJSON itself is really CPP STL free:
...
  Note: including file: D:\Code\Libs\RapidJson\include\rapidjson/document.h
  Note: including file:  d:\code\libs\rapidjson\include\rapidjson\reader.h
  Note: including file:   d:\code\libs\rapidjson\include\rapidjson\rapidjson.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\msinttypes/stdint.h
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdint.h
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\crtdefs.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\msinttypes/inttypes.h
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\inttypes.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\allocators.h
  Note: including file:     d:\code\libs\rapidjson\include\rapidjson\rapidjson.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\encodings.h
  Note: including file:     d:\code\libs\rapidjson\include\rapidjson\rapidjson.h
  Note: including file:   d:\code\libs\rapidjson\include\rapidjson\internal/meta.h
  Note: including file:   d:\code\libs\rapidjson\include\rapidjson\internal/stack.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\internal\swap.h
  Note: including file:   d:\code\libs\rapidjson\include\rapidjson\internal/strtod.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\internal\ieee754.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\internal\biginteger.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\internal\diyfp.h
  Note: including file:    d:\code\libs\rapidjson\include\rapidjson\internal\pow10.h
  Note: including file:   d:\code\libs\rapidjson\include\rapidjson\error/error.h
  Note: including file:  d:\code\libs\rapidjson\include\rapidjson\internal/strfunc.h
...

**Comment by dgregorius** [comment]
I created an empty console project in VS2013 with exceptions disabled:

#include "rapidjson/document.h"
using namespace rapidjson;

int main()
	{
	Document d; 
	d.SetObject();

	return -1;
	}

This creates the following warning:

1>c:\program files (x86)\microsoft visual studio 12.0\vc\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
1>  rapidjson.vcxproj -> C:\Users\User\Documents\Visual Studio 2013\Projects\rapidjson\Debug\rapidjson.exe

I think we can safely conclude it has nothing to do with my code. Here is a link to that project for your convenience: https://dl.dropboxusercontent.com/u/55377219/rapidjson.rar

**Comment by dgregorius** [comment]
I used \showincludes and if I understand it correctly it was pulled in with 
#include <iterator>

Defining RAPIDJSON_NOMEMBERITERATORCLASS solves this problem.

**Comment by wingc-china** [comment]
You are right. From building your project, I found the include path is like:
```
  Note: including file: d:\code\projects\rapidjson\rapidjson\rapidjson/document.h
  Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\iterator
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\istream
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\ostream
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\ios
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocnum
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\streambuf
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xiosbase
  Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale
```

The rapidjson/document.h does include the std::iterator if the RAPIDSON_NOMEMBERITERATORCLASS is not defined, therefore the xlocale is included to complaint about missing /EHsc

**Comment by wingc-china** [comment]
Another solution could be to disable exception in STL. Try to have 
```
#define _HAS_EXCEPTIONS 0
```
in your code before including any header file, or have -D_HAS_EXCEPTIONS=0 as command line parameter to compiler. You will be able to use std::iterator and no warnings still.

**Comment by dgregorius** [comment]
Yeah, I looked into this, but I found a comment by an MS engineer on the VS
team that this is not really supported for the STL since exceptions are an
essential part of the design. So I think the first is the better solution.

2015-09-24 17:09 GMT-07:00 wingc-china <notifications@github.com>:

**Comment by miloyip** [comment]
Do you mean a forward header for RapidJSON classes?
If you have one, welcome for contribution.

**Comment by miloyip** [comment]
Added forward declaration header in 8cb978dc1526089800c3546f2ae31c5caa890363.
