### ISSUE TITLE
std::iostream support

### ISSUE THREAD

**Issue by bruno-j-nicoletti** [miloyip/rapidjson#430]
Hi,

I'm implementing std::iostream support for rapidjson, because my code doesn't work with FILEs. Would you like it pushed back to you? It is just two extra headers.

cheers

Bruno

**Comment by miloyip** [comment]
I think that's fine. Please also add some unit tests as well. Thank you.

**Comment by bruno-j-nicoletti** [comment]
Cool. I won't be able to do that until next week now. I've also gone and added a few convenience overloads to Writer, making it a functor so you can write key/value pairs out and also doing autoscoping of Arrays and Objects (so you don't have to remember when to close the object). It cuts down on the verbosity of writing stuff. It does need C++11 to make the auto scoping work though.

Here's some working C++ code from what I'm working on. Cuts down hugely on the verbosity of the API and making sure you get blocks right....

void Bikes::write(std::ostream &stream,
                          const Bikes::Map &bikes)
{
  rapidjson::StdStreamWriteStream streamer(stream);

  /// make a writer
  rapidjson::PrettyWriter<rapidjson::StdStreamWriteStream> writer(streamer);
  writer.SetIndent(' ', 2);
  {
    /// start an anonymous object, when objBlock goes out of scope, writer.EndObject() will be called
    auto objBlock(writer.ObjectBlock());

    /// write a key/value pair out. Uses templared and overloaded () operator
    writer("currentBike", gCurrentBikeID.value());
    {
      /// start a named array, with the Key of 'bikes', when arr goes out of scope, writer.EndArray() will be called
      auto arr(writer.ArrayBlock("bikes"));
      for(auto &b : bikes) {
        auto &bike = b.second;
        // anonymous block
        auto objBlock(writer.ObjectBlock());

        // some key/value pairs
        writer("id", bike.id().value());
        writer("name", bike.name());
        writer("wheelDiameter", bike.wheelDiameter());

        if(bike.devices().size() > 0) {
          // a named object
          auto b(writer.ObjectBlock("devices"));
          for(auto &d : bike.devices()) {
            const DeviceID &devID = d.second;
            // a named sub-object
            auto objBlock(writer.ObjectBlock(Onyer::deviceTypeAsString(devID.deviceType())));
            // and some key/value pairs
            writer("protocol",   Onyer::protocolAsString(devID.protocol()));
            writer("deviceType", Onyer::deviceTypeAsString(devID.deviceType()));
            writer("address",    devID.address());
          }
        }
      }
    }
  }
}

**Comment by dgregorius** [comment]
Please make this optional using ifdefs or even better an external extension and keep the original rapidjson STL free.

**Comment by miloyip** [comment]
Without `auto`, it can be designed as non-intrusive:

~~~cpp
ObjectBlock b1(writer);
{
    writer.Key(...);
    ArrayBlock b2(writer);
    // ...
}
~~~

This seems not adding too much typing compared to your design. What do you think?

**Comment by bruno-j-nicoletti** [comment]
The helper class that manages the blocks is non intrusive already, but it is templated.

The code for it is....
```C++
////////////////////////////////////////////////////////////////////////////////
template<class WRITER>
class AutoObjectBlock {
public :
  AutoObjectBlock(WRITER *w)
    : writer_(w)
  {}

  // move copy constructor
  AutoObjectBlock(AutoObjectBlock &&src)
    : writer_(src.writer_)
  {
    src.writer_ = NULL;
  }

  ~AutoObjectBlock()
  {
    if(writer_) {
      writer_->EndObject();
    }
  }
protected :
  WRITER *writer_;
};

////////////////////////////////////////////////////////////////////////////////
template<class WRITER>
class AutoArrayBlock {
public :
  AutoArrayBlock(WRITER *w)
    : writer_(w)
  {}

  // move copy constructor
  AutoArrayBlock(AutoArrayBlock &&src)
    : writer_(src.writer_)
  {
    src.writer_ = NULL;
  }

  ~AutoArrayBlock()
  {
    if(writer_) {
      writer_->EndArray();
    }
  }

protected :
  WRITER *writer_;
};
```

So you suggestion already works, but needs to look like....

```C++
ObjectBlock<PrettyWriter> b1(writer);
{
    writer.Key(...);
    ArrayBlock<PrettyWriter> b2(writer);
    // ...
}
```
Also, given my coding standard, I won't allow 'using namespace' in my code. Which means the above gets even more verbose. By adding the intrusive members to PrettyWriter/Writer below, combined with auto, you get the much tighter code from the post above.

```C++
    AutoArrayBlock<PrettyWriter> ArrayBlock()
    {
      StartArray();
      return std::move(AutoArrayBlock<PrettyWriter>(this));
    }

    AutoArrayBlock<PrettyWriter> ArrayBlock(const std::string &key)
    {
      Key(key);
      StartArray();
      return std::move(AutoArrayBlock<PrettyWriter>(this));
    }
```

**Comment by bruno-j-nicoletti** [comment]
Perhaps the best way to manage this is two create two new derived writer classes with the STL and auto methods, and leave the base Writer and PrettyWriter classes alone. But to do that I'd want to rearrange the writer class hierarchy to remove duplicated code from what would be four writer classes by using static polymorphism via [CRTP](http://eli.thegreenplace.net/2011/05/17/the-curiously-recurring-template-pattern-in-c/) and a new base class that collects most of the methods in it.

I'd also like to add an overload to all the functions that currently take a **const char * ** argument can spot string literals and so avoid running strlen on them. 

```C++
const char *str = strdup("banana");
writer.Key("banana"); // calls the string literal version, and so avoids strlen
writer.Key(str); // calls the 'char *' version, which needs to call strlen

class Writer {
  ....
  // overloaded for string literals, where we can spot the size of the array at compile time
  template<typename T, int N>
  void key(const T(&str)[N]) {
    key(str, N-1);
  }

  // overloaded for normal strings, where we have to run strlen
  template<typename T>
  void length(const T* const& str) {
    key(str, internal::StrLen(str));
  }
...
};
```

**Comment by bruno-j-nicoletti** [comment]
One more thing. If you forced the use of my suggested autoblocks, and removed the ability to directly call Begin/End for Arrays and Objects, you would not need the internal level stack. Clients of the API couldn't get it wrong via the auto API, so you don't need to check. Less allocation and data management needed, and smaller code all round. You'd want to keep a level counter though so that IsComplete still works.

**Comment by bruno-j-nicoletti** [comment]
I've done all the work to implement the above with no extra dependencies on third party modules to the existing code. I've issued two separate pull requests, one for the iostream support and one for the major writer refactor. I've also merged them both into the master on my own copy of your repo, which you can use if you want to pull both down.
