### ISSUE TITLE
UTF8 vs UTF16 encoding question

### ISSUE THREAD

**Issue by wildpackets-ma** [miloyip/rapidjson#434]
I have created a very simple x64 test console application under Windows 7 x64 using Visual Studio 2013 - testing rapidjson before adding it to a larger project.	
The test project specifies Unicode character set. creating a document on the stack and parsing a json string works properly: 

	rapidjson::Document rjdoc2;
	rjdoc2.SetObject();
	const char ajson[] = "{\"type\":2}";
	if (!rjdoc2.Parse<0>(ajson).HasParseError()) {
		int j = rjdoc2["type"].GetInt();
	}

Next step, I add the rapidjson code - working in the test project - to a larger existing x64 console project, also using unicode character set., At runtime, the stack created document is corrupt, prior to any usage. A UTF16 document works:

	// rjdoc1 is not corrupt and can be used subsequently to parse json
	using namespace rapidjson;
	typedef GenericDocument<UTF16<> > WDocument;
	WDocument rjdoc1;

	// rjdoc2 is corrupt upon creation and fails with "memory around rjdoc2 is corrupt" 
	// at runtime if we try to parse with it
	Document rjdoc2;

The larger console project exhibiting the problem is using boost 1.57 and googletest 1.7 - maybe a #define conflict?
I'm wondering what might be the issue, and what workaround exists?

**Comment by miloyip** [comment]
Will it be possible that your large project also used another version of RapidJSON?

**Comment by wildpackets-ma** [comment]
Hello Milo,


Thank you for the reply. I was using the January 27, 2014 build at the time of the issue. I am not quite clear: I can definitely use the latest version of rapidjson if that might help. Is this what you are suggesting?


Regards, Mark Andrews


________________________________

**Comment by miloyip** [comment]
My suggestion will be firstly try to build the unit tests and see if it passed all tests.
Please follow to the readme.
