### ISSUE TITLE
Writer: Key() vs String()

### ISSUE THREAD

**Issue by cerevra** [miloyip/rapidjson#435]
Hi!

https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/writer.h#L128

I have a question:
Why there is no overload? Is there any sense?

```c++
    bool Key(const std::basic_string<Ch>& str) {
        return String(str.data(), SizeType(str.size()));
    }
```

**Comment by miloyip** [comment]
For writer, output process of string and key are completely the same.
The separation of these two events are more convenient to some SAX handler.
