### ISSUE TITLE
[Question] Is v1.0.2 binary compatible with previous 0.11 on google code?

### ISSUE THREAD

**Issue by DONGChuan** [miloyip/rapidjson#440]
I just want to make sure that 0.11 on google code and the latest release v1.0.2 whether they are binary compatible? :D

**Comment by spl** [comment]
On the [`readme.md`](https://github.com/miloyip/rapidjson/blob/master/readme.md#installation):

> RapidJSON is a header-only C++ library.

What kind of binary compatibility are you looking for?

**Comment by DONGChuan** [comment]
Hi Thanks spl, Yeh, you are right, it's a header-only lib. I will close my stupid question.

**Comment by spl** [comment]
Not stupid, but possibly easy to miss. :smiley: #441
