### ISSUE TITLE
Warning - No break at the end of case

### ISSUE THREAD

**Issue by etiennebatise** [miloyip/rapidjson#444]
Hi, 
I'm using rapidJSON on a C++ project with Eclipse CDT. So the IDE finds warnings in some switch case statements in the rapidJSON library. It seems breaks are missing in the default statements here : 

[document.h](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/document.h#L2101)

[reader.h](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/reader.h#L510)

[reader.h](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/reader.h#L546)

[reader.h](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/reader.h#L995)

[reader.h](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/reader.h#L1397)

Is it something that is going to be fixed ?

**Comment by thebusytypist** [comment]
I think the break statement is not mandatory in switch-case clause. Which
compiler are you using?

**Comment by mloskot** [comment]
It falls into good pracitces to include `break` at every level of `switch`, even the last one (i.e. it makes code clear, refactoring friendly, etc.).
Perhaps @etiennebatise compiles in strict mode, with static analysis on.

**Comment by miloyip** [comment]
I am open to this. Please submit a PR.

**Comment by etiennebatise** [comment]
@mloskot is right, I use *-Wall* with *g++*.
I'll submit a PR as soon as possible about this.
