### ISSUE TITLE
Embarcadero 32bits

### ISSUE THREAD

**Issue by SaNxEz89** [miloyip/rapidjson#446]
Hi, 
I have tried to use rapidjson library in Embarcadero XE7 IDE.
I can compile and use the library perfectly when running in 64bits. However, an error comes up in the struct BaseReaderHandler on "reader.h"file when I compile the same code for 32bits: 

Error Message: "[bcc32 Error] reader.h(185): E2299 Cannot generate template specialization from 'internal::SelectIf<C,T1,T2>'" 

Any idea or reason why I can compile it using 64bits and cannot compile in 32bits? Do i need to modify anything in the library?

Steps to reproduce:
1) Include library in project include's path. 
2) Create an empty project.
3) Include "rapidjson/document.h" in the .h
4) Add somewhere in the .cpp file "rapidjson::Document doc;"
5) Compile for 64bits --> OK, compiled and running
6) Compile for 32bits ---> Error mentioned before comes up

Thanks in advance,
Rafael.

**Comment by miloyip** [comment]
I suppose this would be a compiler issue. It may be that the 32-bit compiler is older and does not support (or has bug for) some standard C++ features. You may contact the vendor.

This class `BaseReaderHandler` is actually not used by RapidJSON per se, but for using RapidJSON. If you do not need it in your client code, you may comment it out.
