### ISSUE TITLE
Warning - No return, in function returning non-void

### ISSUE THREAD

**Issue by etiennebatise** [miloyip/rapidjson#448]
Hi,

I've found 4 new warnings int *encodedstream.h*
  * [1](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/encodedstream.h#L80)
  * [2](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/encodedstream.h#L81)
  * [3](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/encodedstream.h#L230)
  * [4](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/encodedstream.h#L230)

The line number can change with new versions so here is the first item for example :

```c++
Ch Peek() const { RAPIDJSON_ASSERT(false); }
```

So maybe just adding `return 0;` before the closing brace will solve this, but the comment `//Not implemented` leaves me wondering about this one.

**Comment by miloyip** [comment]
Yes. Adding `return 0` should be fine.
It is `// Not implemented` because these streams does not support insitu-parsing but insitu-parsing is enabled by a template parameter. So it still needs to be exists for passing compilation but should never be called.
