### ISSUE TITLE
Parsing time compire json_decode

### ISSUE THREAD

**Issue by RustJason** [miloyip/rapidjson#451]
Hi @miloyip, I just wrote a php extension for rapidjson. And I get confused about it's running time, I've read your report here https://github.com/miloyip/nativejson-benchmark, and this show rapidjson is fast enough to get a top rank, But my tests shows in a different way.
```
#json string length;
int(253423)
#parsing time
Rapidjson: 0.007145881652832

json_decode: 1.5020370483398E-5
```
I can see rapidjson is almost zero memory cost in another test. So I think this is It's just a trade-off and rapidjson is memory friendly but not that fast or I am doing this in a wrong way?
Many thanks in advance

**Comment by Kosta-Github** [comment]
how did you compile your `rapidjson` C++ part of that extension? did you use appropriate optimization flags?

**Comment by RustJason** [comment]
@Kosta-Github  Beside -O3, Is there any optimization switch shoud I turn on ?

**Comment by thebusytypist** [comment]
Hello @RustJason ,
For general optimization I think `-O3` is sufficient.

You can also define `RAPIDJSON_SSE2` or `RAPIDJSON_SSE42` macros with `RAPIDJSON_SIMD` turned on before you include `rapidjson.h`. Then RapidJSON will use the selected instructions to accelerate parsing.

Note that this depends on your target machine's CPU capacity. Maybe SSE 4.2 is too aggressive.

**Comment by frederikbosch** [comment]
@RustJason Where can I find this extension? :)

**Comment by RustJason** [comment]
@frederikbosch  You are looking for php extension of rapidjson?  Here it is https://github.com/RustJason/php-rapidjson ,But I just stated write it and haven't finish yet.
