### ISSUE TITLE
Compare two JSON objects

### ISSUE THREAD

**Issue by alexandruirimiea** [miloyip/rapidjson#452]
In my case, I compare the hashes of the JSON strings, but if the field order is different, then I receive a false positive.

Is there a way to compare two JSON objects?

**Comment by pah** [comment]
After parsing, you can use [`operator==`](https://miloyip.github.io/rapidjson/classrapidjson_1_1_generic_value.html#afbdbc9cbc3b59feb5a28d5bfee97dbb3) of the RapidJSON values.

**Comment by alexandruirimiea** [comment]
Indeed, this seems to be the solution.

**Comment by miloyip** [comment]
Actually I tried to calculate a hash of a subtree in the schema branch. By using commutative operator to combine the hashes of object members (e.g. modulo addition, xor, etc), it can do the comparison in O(n) if not considering hash collision. Otherwise, the current operator==() is O(n^2).
