### ISSUE TITLE
kDefaultStackCapacity with SAX and big JSON-String

### ISSUE THREAD

**Issue by dpfe** [miloyip/rapidjson#453]
When I use `Reader.Parse` to parse a JSON-String of ~6000 bytes, it stops at offset 192 with arbitrary error messages.

After setting `kDefaultStackCapacity` to 25600 everything went fine. 
What can I do to make the `Reader.Parse` method run through the String in smaller portions step-by-step?

**Comment by miloyip** [comment]
This should not be happened.
Please provide more information, such as platform and compiler.
If possible, please post the JSON string and see if we can reproduce the problem. If there is sensitive information in the JSON, you may consider e-mail to me privately miloyip@gmail.com .

**Comment by dpfe** [comment]
The platform is a STM32F4 microcontroller and I use arm-gcc 4.9 2014q4 with c++11 enabled.


The Handler is implemented as (sorry, code-markdown didn't work for some reason):


using namespace rapidjson;
using namespace std;

struct MyHandler {
    bool Null() { printf("Null()\n"); return true; }
    bool Bool(bool b) { printf("Bool(%d)\n",b); return true; }
    bool Int(int i) { printf("Int(%d)\n",i); return true; }
    bool Uint(unsigned u) { printf("Uint(%u)\n",u); return true; }
    bool Int64(int64_t i) { printf("Int64(%d)\n",i); return true; }
    bool Uint64(uint64_t u) { printf("Uint64(%u)\n",u); return true; }
    bool Double(double d) { printf("Double()\n"); return true; }
    bool String(const char* str, SizeType length, bool copy) {
        printf("String(%s)\n",str);
        return true;
    }
    bool StartObject() { printf("StartObject()\n"); return true; }
    bool Key(const char* str, SizeType length, bool copy) {
        printf("Key(%s)\n",str);
        return true;
    }
    bool EndObject(SizeType memberCount) { printf("EndObject(%d)\n", memberCount); return true; }
    bool StartArray() { printf("StartArray()\n"); return true; }
    bool EndArray(SizeType elementCount) { printf("EndArray(%d)\n", elementCount); return true; }
};



**I start the parsing through:**



MyHandler handler;
Reader reader;
StringStream ss(mRootObject->sProt->answer(std::string("getJSON?")).c_str());
reader.Parse(ss, handler);
reader.GetParseErrorCode();
printf("\nError(offset %u): %s\n",
(unsigned)reader.GetErrorOffset(),
GetParseError_En(reader.GetParseErrorCode()));



**The output is:**


StartObject()<\n>
Key(EffectList)<\n>
StartObject()<\n>
Key(effects)<\n>
StartArray()<\n>
StartObject()<\n>
Key(Hue base)<\n>
StartObject()<\n>
Key(val)<\n>
Uint(0)<\n>
Key(type)<\n>
String(uint32)<\n>
Key(min)<\n>
Uint(0)<\n>
Key(max)<\n>
Uint(360)<\n>
EndObject(4)<\n>
Key(name)<\n>
StartObject()<\n>
Key(val)<\n>
String(Plasma)<\n>
Key(type)<\n>
String(string)<\n>
Key(internal)<\n>
Bool(1)<\n>
EndObject(3)<\n>
Key(scale)<\n>
StartObject()<\n>
Key(val)<\n>
Double()<\n>
Key(type)<\n>
String(float)<\n>
Key(min)<\n>
Double()<\n>
Key(max)<\n>
<\n>
Error(offset 192): Invalid value.<\n>

I sent you the JSON-String, that was given to MyHandler via E-Mail.

**Comment by pah** [comment]
The following line looks suspicious to me:
```cpp
StringStream ss( mRootObject->sProt->answer( std::string("getJSON?") ).c_str() );
```
In case, `->answer("getJSON")` returns a `std::string` by **value**, the `c_str()` pointer is invalidated right after the construction of the `StringStream` and anything may happen.

Can you check if the error persists, if you change this line to
```cpp
std::string ans( mRootObject->sProt->answer( "getJSON?" ) );
StringStream ss( ans.c_str() );
```

**Comment by dpfe** [comment]
This is a good point. I'll check that later.

I wondoer, how this could have been solved by increasing kDefaultStackCapacity...

**Comment by dpfe** [comment]
Ok, you were right. Invalidating the returned std::string seems to have destroyed the JSON-String in memory.

Thanks for the quick help and for this nice piece of software.

One small additional question:
What is the suggested procedure if I get a JSON-String only piecwise through an interface, when I want it to be parsed SAX-like without storing the whole string in memory?

**Comment by miloyip** [comment]
You need to create a custom stream for that. You may refer to [user guide](http://rapidjson.org/md_doc_stream.html) and implementation of `FileReadStream`.
