### ISSUE TITLE
Crash in debug mode

### ISSUE THREAD

**Issue by SDraw** [miloyip/rapidjson#455]
Using debug compilation mode in Visual Studio 2013 library works wrong.
If use attached code to parse attached JSON file it will says that there is no problem in data parsing, but it's impossible to get any parsed data due crashing.
Program code: http://pastebin.com/bKctArpK
JSON file: http://pastebin.com/WXm0A4TQ
Maybe, I missed something in documentation.

**Comment by Disinterpreter** [comment]
I check is issue on linux and get a crash too
http://i.imgur.com/4YRA5Ne.png

**Comment by miloyip** [comment]
@SDraw , `Size()` is for getting the number of elements of an **array**.

~~~cpp
    //! Get the number of elements in array.
    SizeType Size() const { RAPIDJSON_ASSERT(IsArray()); return data_.a.size; }
~~~

But the root of provided JSON is an **object** (the `animation[0]` is also an object), so the following lines will assert failure in debug configuration:

~~~cpp
    printf("Info: Root node has %d members\n",l_file.Size());
    // ...
    printf("Info: animation[0] node has %d members\n",l_node.Size());
~~~

**Comment by SDraw** [comment]
Thank you, your explanation helped a lot.
