### ISSUE TITLE
Nested object HasMember()?

### ISSUE THREAD

**Issue by SS70Chevelle** [miloyip/rapidjson#456]
Hello,  I have been using rapidJSON and am wondering if there is a way to possibly check if an object within an object has a member. The message is structured as such:

{"control" : {"type1" : {"name" : "Joe", "age" : 45}}}

The issue is I need to know if it is a control message, there are several types such as control, status, etc and I also need to know what type it is, type1, type2, etc.  Well, I am able to parse the message into a document, let's call it doc.  I am then calling doc.HasMember("control") to verify it is a control type and then I need to find out what kind of control message it is, however the way I would have assumed this to work ( doc.HasMember("type1"); or doc["control"].HasMember("type1"); ) does not work.  I am wondering if/how to see what type the message is.

Any help would be extremely appreciated.  Thank you!

**Comment by miloyip** [comment]
`doc["control"].HasMember("type1")` should work in this case.

Another simple way is to use the new [JSON Pointer](http://rapidjson.org/md_doc_pointer.html) feature provided by RapidJSON.

It can be something like:

~~~cpp
if (Value* type1 = GetValueByPointer(doc, "/control/type1")) {
    const char* name = (*type1)["name"].GetString();
    int age = (*type1)["age"].GetInt();
    // ...
}
~~~
