### ISSUE TITLE
integer conversion warning in diyfp.h with intel 16 compilers

### ISSUE THREAD

**Issue by cyrush** [miloyip/rapidjson#457]
I am getting a new warning using rapidjson with intel 16 beta compilers:

```
rapidjson/include/rapidjson/internal/diyfp.h(257): error #68: integer conversion resulted in a change of sign
       *outExp = -348 + index * 8;
                 ^
```

Since it's in the rapidjson internals, I am not sure if this is a real issue or a red herring. I noticed there isn't a RAPIDJSON_DIAG_PUSH/POP case for intel compilers, would you be open to a pull request with logic to help disable warnings for intel?

**Comment by miloyip** [comment]
I remembered it has been fixed in the master branch.

**Comment by cyrush** [comment]
Thanks! I'll update to a newer master and close out if all is well.

**Comment by cyrush** [comment]
I tested out a new version of master, and the warning was resolved.
Thanks for the info!
