### ISSUE TITLE
Weird parsing behavior

### ISSUE THREAD

**Issue by dummy0stud** [miloyip/rapidjson#461]
Hello, thanks for the awesome lib, but I'd like to understand why is this piece of data being parsed successfully?

```
{
		//const char* json = "{\"project\":\"rapidjson\",\"stars\":10}";
		rapidjson::Document doc;
		char* json = "\"asasdasddasdasdadasdasdadasdasdaasdasd\"";		
		std::cout << "HasParseError:" << doc.Parse(json).HasParseError() << "\n";
		std::cout << "HasParseError:" << doc.HasParseError() << "\n";
		std::cout << "GetParseError:" << doc.GetParseError() << "\n";
		return 0;
}	
```

output:
```
HasParseError:0
HasParseError:0
GetParseError:0
```

**Comment by miloyip** [comment]
The newer [RFC7159](http://www.ietf.org/rfc/rfc7159.txt) has the following change from RFC 4627:

> Changed the definition of "JSON text" so that it can be any JSON
      value, removing the constraint that it be an object or array.

So that, a string value at root is valid.

**Comment by dummy0stud** [comment]
wow, very interesting, can we add some other data to it? Something like 

```
char* json = "\"asasdasddasdasdadasdasdadasdasdaasdasd\""; 
doc.Parse(json);
doc.AddMember("data",true, doc.GetAllocator());
```
It looks like it's not working

**Comment by miloyip** [comment]
No. You cannot add a member to a string typed value.
You need to convert the root into an object, before adding member. But this will erase the existing string.
You may put the root string into a member of a new root, then you can add new members:

~~~cpp
doc.Parse("\"asasdasddasdasdadasdasdadasdasdaasdasd\"");
Value newRoot(kObjectType);
newRoot.AddMember("s", doc, doc.GetAllocator()); // Move the root string into a new member
newRoot.AddMember("data",true, doc.GetAllocator());
newRoot.Swap(doc); // doc's root become newRoot.
// {"s":"asasdasddasdasdadasdasdadasdasdaasdasd","data":true}
~~~
