### ISSUE TITLE
rapidjson\document.h(2042): error C2061: syntax error: identifier 'stack_'

### ISSUE THREAD

**Issue by pillya** [miloyip/rapidjson#463]
while trying to build this

using namespace rapidjson;
typedef GenericDocument<UTF16<> > WDocument;
typedef GenericValue<UTF16<> > WValue;
FILE* fp = fopen("localization.json", "rb"); // non-Windows use "r"
char readBuffer[256];
FileReadStream bis(fp, readBuffer, sizeof(readBuffer));
AutoUTFInputStream<unsigned, FileReadStream> eis(bis);  // wraps bis into eis
WDocument d;
d.ParseStream<0, AutoUTF<unsigned> >(eis);

**Comment by miloyip** [comment]
Your `typedef GenericDocument > WDocument` looks strange to me.

**Comment by pillya** [comment]
Sorry! Bugs in my dna) Your lib is great, especially double conversion speed.
Thank you
