### ISSUE TITLE
Unexpected Crash - (Big Json Files) 

### ISSUE THREAD

**Issue by just-coffee** [miloyip/rapidjson#464]
Hi there, 

I am trying to figure out, whether I am responsible for that crash (api mis-usage) of rapidjson or there indeed a problem and it crashes.

Let me describe a little bit, what I am doing and it crashes, always at the same point. I have to process 30 json-formated files, which are 500MB each and there is a json document per line. Similar to the following: 

*{"threat_tri": 1, "threat_id": "127.0.0.1", "64a03958c4f6b2d5292c6890e61ed538": 1, "id_keys": ["64a03958c4f6b2d5292c6890e61ed538"]}*

My physical memory is 16GB, running Linux debian 3.16.0-4-686-pae.

The code that parses and load into memory the json-data is the following: 
```c++
///////////////////////////////////////////
// Get data from a single file
void TRI::file(std::string filename, std::string fullpath)
{
    Records records;
    Records sources;

    ifstream jsonfile(fullpath.c_str());
    bool perror = false;
    string jsonline;

    /* rapidjson stream parser */
    Document document;

    LOG(INFO) << fullpath.c_str() << " "<< jsonline.c_str();

    /* Read file line-by-line */
    while (getline(jsonfile, jsonline))
    {
        perror = document.Parse<0>(jsonline.c_str()).HasParseError();

        if (perror)
        {
            continue;
        }

        if(document.HasMember("error"))
        {
            continue;
        }

        /* Get all appearances from different sources, for each record. */
        if(document.HasMember("threat_id"))
        {
            string value = document["threat_id"].GetString();
            if (records.find(value) == records.end())
            {
                if(document.HasMember("id_keys"))
                {
                    records[value] = float(document["id_keys"].Size());
                }
            }
            else
            {
                continue;
            }

            /* Store records into a dictionary for later processing by process(). */
            if(_mrecords.find(value) == _mrecords.end())
            {
                _mrecords[value] = 1;
            }
            else
            {
                _mrecords[value] += 1;
            }
        }

        /* Get duplication level for each source */
        if(document.HasMember("id_keys"))
        {
            for (Value::ConstValueIterator itr = document["id_keys"].Begin(); itr != document["id_keys"].End(); ++itr)
            {
                if(sources.find( itr->GetString()) == sources.end())
                {
                    sources[itr->GetString()] = float(document[itr->GetString()].GetInt());
                }
                else
                {
                    sources[itr->GetString()] += float(document[itr->GetString()].GetInt());
                }
            }
        }
        else
        {
            continue;
        }
    }

    /*  Not sure I need that - But it did not make a different to my crash (with or without) */
    Document().Swap(document).SetObject();
    Document(kObjectType).Swap(document);

    /* Store total sources of the day and all the records. */
    _dsources[filename] = sources.size();
    _drecords[filename] = records;
}
  ```
**Crash Reports** - I have attached the full gdb-report.txt

Program received signal SIGSEGV, Segmentation fault.
0x0807cba8 in rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>::AddChunk (this=0x6a47fe0, capacity=65536) at ./include/rapidjson/allocators.h:235
235	        chunk->capacity = capacity;

It always crashes at the same point, around 4GB of memory usage, which make think that:

*I most likely hit a memory limitation and I can't figure out, how to fix that.*

Some other thoughts, which crossed my mind.

*Could it be a corrupted-format line or a NULL pointer causing that ? *

Are there any ideas, why I keep getting that ? 
 
Thank you in advance.

**Comment by just-coffee** [comment]
You can ignore/close my issue, since I believe that my problem might be the 32-bit heap limitations. I will setup a 64bit, re-try and let you know, if the crash is still there. 

Thanks again.

**Comment by miloyip** [comment]
32-bit application has maximal 4GB address space. 64-bit should help.
By the way, RapidJSON supports SAX API, which do not need to parse the whole document into a DOM. But it is event-driven, which is only suitable for some situations that only need to scan the JSON once, e.g. converting into other formats, extracting particular information, etc.
