### ISSUE TITLE
Custom Handlers

### ISSUE THREAD

**Issue by samunns** [miloyip/rapidjson#465]
Are there any examples on how to use handlers? I read in your "http://rapidjson.org/md_doc_dom.html" that "User may create custom handlers for transforming the DOM into other formats. For example, a handler which converts the DOM into XML." Since I am fairly new to C++ and using your code I was wondering if any examples exist that might help me illustrate how to write such a handler?

**Comment by pah** [comment]
Some examples can be found in http://rapidjson.org/md_doc_sax.html.
