### ISSUE TITLE
How to initialize Value& from CString ?

### ISSUE THREAD

**Issue by mariopavlov** [miloyip/rapidjson#466]
I have looked to all tutorials and examples from here:
http://rapidjson.org/md_doc_sax.html

However, I was not able to find any example for how can I initialize Value& from CString (string).
From the example:

// 2. Modify it by DOM
Value& s = d["stars"];

How can I accomplish something like this ?
string name = "some information";
Value& s = d[name];

**Comment by pah** [comment]
This should work, if you add [`-DRAPIDJSON_HAS_STD_STRING=1`] (http://rapidjson.org/group___r_a_p_i_d_j_s_o_n___c_o_n_f_i_g.html#ga2f2eef0ee4477f3fe5874703a66e997f) to your compiler switches.
Hth,
  Philipp

**Comment by mariopavlov** [comment]
Thank you for your comment,

However I'm not sure whether or not I have understand your solution correctly. First I have tried to add what you have write in your reply in Visual Studio Options C++ --> Command Line, it does not help me, and returned an error.

Then I have tried to define the following:

**Comment by mloskot** [comment]
@mariopavlov I have to admit, your question is confusing.
In the topic, you use `CString` which is MFC/ATL type name, but do you actually mean C-string?
Then, in your example you use `string` which I assume is meant to read `std::string`.

Anyhow, here is selection of options for the mixture of all of types you are possibly asking:

```
rapidjson::Document d;
d.Parse("{\"a\":\"aaa\"}");
RAPIDJSON_ASSERT(!d.HasParseError());

CStringA mfc_name("a"); // or ATL

// Option 1: via CString explicitly converted to char* (C-string)
Value& s1 = d[mfc_name.GetBuffer()];

// Option 2: via std::string
std::string std_name(mfc_name);
Value& s2 = d[std_name];

// Option 3, version of 2 with temporary bound to const-reference
Value& s3 = d[std::string(mfc_name)];
```

**Comment by mariopavlov** [comment]
@mloskot, thank you for your comment. My project is MFC project so I use CString, however because the examples does not use MFC, I'm trying first to solve this problem with std::string, in different project.

I have tried your solutions however, I receive the following errors:
Option 1:
Error	12	error C2679: binary '[' : no operator found which takes a right-hand operand of type 'wchar_t *' (or there is no acceptable conversion)

Option 2:
Error	12	error C2679: binary '[' : no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable conversion)

So I'm still not sure how to define 
#define RAPIDJSON_HAS_STDSTRING
So that I can use strings and CString with rapidjson.

**Comment by Kosta-Github** [comment]
``` c++
#define RAPIDJSON_HAS_STDSTRING 1
#include <rapidjson/...>
```

**Comment by mloskot** [comment]
@mariopavlov I have updated my example.

**Comment by mariopavlov** [comment]
@mloskot 
@Kosta-Github 

I have tried the solution you have provided, I still have the same problems.

![image](https://cloud.githubusercontent.com/assets/9350618/11179993/fb8f37d8-8c5f-11e5-8235-1368e2931097.png)

@Kosta-Github, here @miloyip explains why std::string is not available by default.
http://stackoverflow.com/questions/30157406/is-there-way-to-use-rapidjson-with-stdstring-efficiently

**Comment by Kosta-Github** [comment]
can you switch off the usage of `precompiled headers`? or at least ensure, that you don't include something from `rapidjson` in them?

**Comment by mariopavlov** [comment]
@Kosta-Github, I have tried to switch off, the `precompiled headers `. This does not help me, still the same error. Also I have tried the same thing in the example project that is provided with Rapidjson, and still the same error.

**Comment by Kosta-Github** [comment]
Can you unfold the `no operator "[]" matches these operands` lines in your error log?

**Comment by mariopavlov** [comment]
![image](https://cloud.githubusercontent.com/assets/9350618/11181680/f7a10d38-8c6c-11e5-849c-55a6f48c69b9.png)

**Comment by mariopavlov** [comment]
Anyone with some idea ? :(

**Comment by mloskot** [comment]
I have re-tested with VS2013 from scratch against the current `master` and all I can say, it just works as expected!

![capture](https://cloud.githubusercontent.com/assets/80741/11206743/4fcb5f64-8d11-11e5-98d9-3568ec197a5e.PNG)

The only idea I have is, double or triple check your environment, your project settings, remove `#include <stdafx.h>` completely, etc.

**Comment by mariopavlov** [comment]
@mloskot, Thank you for your help.

I have pulled the latest version from GitHub of the repository and everything is working fine now. I guess I have used older version, where the usage of String was not possible.

Thanks again, 
Best to all!

**Comment by mloskot** [comment]
@mariopavlov Good it worked out for you.

p.s. Please, be precise whenever you call types. "usage of String" is another ambiguous term, especially if you capitalise it.. Call it `string` or `std::string` or `CString` or C-string, IOW, help to help yourself and make it clear what you talking about.

**Comment by mariopavlov** [comment]
Note taken! :)
