### ISSUE TITLE
Pretty print to a string

### ISSUE THREAD

**Issue by na-ka-na** [miloyip/rapidjson#467]
Feature request - pretty print a json to a string stream. Something like this:

std::ostringstream oss;
rapidjson::PrettyWriter(oss);
doc.Accept(oss);

**Comment by miloyip** [comment]
You can done it since #530 

~~~cpp
#include "rapidjson/ostreamwrapper.h"

std::ostringstream oss;
rapidjson::OStreamWrapper osw(oss);
rapidjson::PrettyWriter writer(osw);
doc.Accept(writer);
~~~
