### ISSUE TITLE
Maybe something like Mantle

### ISSUE THREAD

**Issue by gggin** [miloyip/rapidjson#471]
我不知道怎么说好..
这个东西可以根据一个schema来生成ObjectC的对象,自动生成代码 直接把json字符串变成Oc的内存对象,能否直接搞成c++的struct呢? 通过schema那个东西?
https://github.com/Mantle/Mantle

**Comment by miloyip** [comment]
In #326 @patrickjwhite also have a similar suggestion. I will think about it.
You may also provide more detail ideas or prototypes.

**Comment by gggin** [comment]
I find autojsoncxx in wiki
