### ISSUE TITLE
Template specialization failure with SunOS compiler

### ISSUE THREAD

**Issue by woldendans** [miloyip/rapidjson#472]
Hello,

I am reporting this as the fix is really simple, even if the problem applies only to an old SunOS c++ compiler (Sun C++ 5.10). I can produce the patch later, but I would be very interested if anyone could explain me why the fix works.

In *document.h*, line 500, we find:
```
explicit GenericValue(T b, RAPIDJSON_ENABLEIF((internal::IsSame<T, bool>))) RAPIDJSON_NOEXCEPT
```
If I get this right, the point is to make sure the compiler will select the boolean constructor if and only if 'b' type is strictly 'bool', preventing any implicit conversion.

Yet, while compiling this on Sun, I get this:
```
line 500: Error: Type is not a member of rapidjson::internal::RemoveSfinaeTag<rapidjson::internal::SfinaeTag&(*)(?)>.
```
As you can see, the compiler was unable to determine what *internal::IsSame<T, bool>* means.
But by reverting the template arguments:
```
explicit GenericValue(T b, RAPIDJSON_ENABLEIF((internal::IsSame<bool, T>))) RAPIDJSON_NOEXCEPT
```
The compiler succeeds without an issue, and the tests pass perfectly.

I believe this is due to the partial specialization of IsSame, which requires the first parameter to be known, but if anyone finds the time I would be happy to have a more insightful explanation.

Cheers!

**Comment by miloyip** [comment]
Thank you for your report.
It seems purely a compiler bug.
But if this workaround can fix the issue, I would welcome for a PR.
