### ISSUE TITLE
rapidjson::Writer asserts when root element is a string

### ISSUE THREAD

**Issue by ntauthority** [miloyip/rapidjson#476]
The following code asserts in rapidjson::Writer::Prefix:

```c++
rapidjson::Document document;
document.SetString("hello", document.GetAllocator());

rapidjson::StringBuffer sb;
rapidjson::Writer<rapidjson::StringBuffer> writer(sb);

document.Accept(writer);
```

on the following line:

```c++
RAPIDJSON_ASSERT(type == kObjectType || type == kArrayType);
```

This prevents me from serializing arbitrary data as JSON from another serialization format, as the root element may very well be a string or a number.

**Comment by miloyip** [comment]
Are you using an old version? This restriction should have been removed.

**Comment by ntauthority** [comment]
Ah, indeed, my fault - I thought I fetched rapidjson from the master repository using my dependency management system; turns out I had a local copy dangling in my own repository.

Thanks for the help, anyway!
