### ISSUE TITLE
Proper value corrupts json at runtime

### ISSUE THREAD

**Issue by tsteinholz** [miloyip/rapidjson#479]
Here is my code out of context
```c++
    ...
    printf("%s", buffer);//debug

    // Parse Json
    rapidjson::Document document;
    document.Parse(buffer);
    assert(!document.IsNull());
    ...
```

This is my code that is valid. (check herre: http://jsonlint.com/)
```json
{
    "FullScreen": true,
    "VSync": true,
    "AntiAliasingLevel": "NONE",
    "ColorBlindLevel": "NONE",
    "Resolution": [ 800, 600 ],
    "Master": 100,
    "FX": 100,
    "Speech": 100,
    "Music": 100,
    "Subtitles": true,
    "Language": "English"
}
```
Which outputs... :+1: 
```
[100%] Built target Somnia
{
    "FullScreen": true,
    "VSync": true,
    "AntiAliasingLevel": "NONE",
    "ColorBlindLevel": "NONE",
    "Resolution": [ 800, 600 ],
    "Master": 100,
    "FX": 100,
    "Speech": 100,
    "Music": 100,
    "Subtitles": true,
    "Language": "English"
}
Somnia Version: 0.0.1
Demo Version: false
Settings:
[Video]
	 FullScreen : 1
[Audio]
[Game]
```

Then when I change the json value of "Fullscreeen" to false(still valid http://jsonlint.com/), the Document is not an object and is null.

```json
{
    "FullScreen": false,
    "VSync": true,
    "AntiAliasingLevel": "NONE",
    "ColorBlindLevel": "NONE",
    "Resolution": [ 800, 600 ],
    "Master": 100,
    "FX": 100,
    "Speech": 100,
    "Music": 100,
    "Subtitles": true,
    "Language": "English"
}
```

I get this output :-1:

```
[100%] Built target Somnia
{
    "FullScreen": false,
    "VSync": true,
    "AntiAliasingLevel": "NONE",
    "ColorBlindLevel": "NONE",
    "Resolution": [ 800, 600 ],
    "Master": 100,
    "FX": 100,
    "Speech": 100,
    "Music": 100,
    "Subtitles": true,
    "Language": "English"
}
Somnia: /home/tsteinholz/Development/C++/Somnia/source/utils/settings.cpp:35: void Settings::Load(const char*): Assertion `!document.IsNull()' failed.
��./quick-debug.sh: line 4:  4732 Aborted                 (core dumped) ./Somnia
```

**Comment by pah** [comment]
Can you [check the status] [1] of the last parsing operation?
````cpp
rapidjson::ParseResult ok = document.Parse(buffer);
if (!ok)
    printf( "JSON parse error: %s (%u)\n", GetParseError_En(ok.Code()), ok.Offset());
````

[1]: https://miloyip.github.io/rapidjson/group___r_a_p_i_d_j_s_o_n___e_r_r_o_r_s.html

**Comment by tsteinholz** [comment]
@pah Sorry, what do I need to include for `GetParseError_En`?

I already tried rapidjson.h, error.h and reader.h

**Comment by pah** [comment]
Sorry, missed that. It's
````cpp
#include <rapidjson/error/en.h>
````

**Comment by tsteinholz** [comment]
okay the first part works however I cannot fix this error still, is there a method or something for this?

```
error: conversion from ‘rapidjson::GenericDocument<rapidjson::UTF8<> >’ to non-scalar type ‘rapidjson::ParseResult’ requested
     rapidjson::ParseResult ok = document.Parse(buffer);
                                                      ^
```

**Comment by pah** [comment]
Ok, my bad again. :disappointed:  It's the `Reader`, that allows direct access to the `ParseResult` from the return value of the parsing.  For `Document`, you need to use `GetParseError()` and `GetParseErrorOffset()` explicitly:
````cpp
rapidjson::ParseErrorCode ok = document.Parse(buffer).GetParseError();
if (ok != rapidjson::kParseErrorNone)
    printf( "JSON parse error: %s (%u)\n", GetParseError_En(ok), document.GetParseErrorOffset());
````

**Comment by tsteinholz** [comment]
I randomly stopped having the problem, but I added that parsing error code just in case something like that happens again. One of the downsides of using this library seems to be the readability of the errors ;-; but thanks for your help @pah

**Comment by pah** [comment]
> One of the downsides of using this library seems to be the readability of the errors
Can you elaborate on that?

I'd say, one of the downsides has been the usability of the error handling code when using a `Document`.  To help here, I just opened #480.  Do you see other things missing?

Thanks,
  Philipp

**Comment by tsteinholz** [comment]
Like I once tried to get `document["Subtitles"].AsBool()` after asserting it, but I added an extra character in-front of  the string so I got a 4 line error code about generic values that didn't once mention the string "Subtitles"

**Comment by pah** [comment]
Are you referring to compiler errors or runtime errors here?

**Comment by tsteinholz** [comment]
compiler in this instance

**Comment by pah** [comment]
Yes, being heavily templated, RapidJSON often has less readable compiler errors. Concrete examples could help to work on improvements here.

**Comment by tsteinholz** [comment]
@pah you couldn't tell me what was wrong just from this message, its almost as it just says "you did something wrong somewhere"

```
Somnia: /home/tsteinholz/Development/C++/Somnia/include/utils/rapidjson/document.h:866: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
Aborted (core dumped)
```

**Comment by pah** [comment]
Well, it's an assertion.  Assertions indicate programming errors and are meant for developers.

You can look at the source position mentioned in the assertion's message to find out that you try to access a non-existent member of an object.

Or send a PR to change the assertion to
````cpp
RAPIDJSON_ASSERT(false && "Access to non-existent member.");
````
