### ISSUE TITLE
Escape character like \n

### ISSUE THREAD

**Issue by zheolong** [miloyip/rapidjson#486]
When parsing {"line_delimiter":"\\\n"}, we will get the value of "line_delimiter" as "\\\n", but the right value should be "\n".

**Comment by miloyip** [comment]
When parsing `{"line_delimiter":"\\n"}`, you will get the value of `"line_delimiter"` as `"\n"` (2 characters).

**Comment by zheolong** [comment]
@miloyip You are right, my mistake.
