### ISSUE TITLE
unittest/pointertest.cpp won't compile on Linux/ARM 32 

### ISSUE THREAD

**Issue by ncalad** [miloyip/rapidjson#489]
When trying to build rapidjson on Linux/ARM 32 systems, the unittest build fails with a signed/unsigned comparison error. 

72%] Building CXX object test/unittest/CMakeFiles/unittest.dir/pointertest.cpp.o
In file included from /home/andy/Skedans/sdk-core/assets/packages/rapidjson/src/rapidjson/test/unittest/unittest.h:37:0,
                 from /home/andy/Skedans/sdk-core/assets/packages/rapidjson/src/rapidjson/test/unittest/pointertest.cpp:15:
/home/andy/Skedans/sdk-core/assets/packages/rapidjson/src/rapidjson/thirdparty/gtest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = wchar_t]’:
/home/andy/Skedans/sdk-core/assets/packages/rapidjson/src/rapidjson/thirdparty/gtest/include/gtest/gtest.h:1501:30:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = wchar_t; bool lhs_is_null_literal = false]’
/home/andy/Skedans/sdk-core/assets/packages/rapidjson/src/rapidjson/test/unittest/pointertest.cpp:309:9:   required from here
/home/andy/Skedans/sdk-core/assets/packages/rapidjson/src/rapidjson/thirdparty/gtest/include/gtest/gtest.h:1467:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (expected == actual) {

**Comment by mloskot** [comment]
It is a warning, isn't it?

(It is good to use [markup for code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks))

**Comment by ncalad** [comment]
Yes it is a warning but the build flags include -Werror so the compile 
stops at that point.

I fixed it temporarily by turning off building of the unit tests in the 
CMakeLists.text file

option(RAPIDJSON_BUILD_TESTS "Build rapidjson perftests and unittests." OFF)

-- Andy

Mateusz Łoskot wrote:
