### ISSUE TITLE
Glue two documents together

### ISSUE THREAD

**Issue by alexandruirimiea** [miloyip/rapidjson#490]
Is there a possibility to glue two documents together like below?

E.g.:

    {
        "key1": "value1",
        "key2": "value2"
    }

    {
        "key3": "value3"
    }

Result:

    {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3"
    }

In my case, I have a lot of classes that are serialized as JSON. The problem is that when a subclass is serialized, I have to rewrite the same code from the base class in the extended class, plus the additional members, but I already have a method in the base class which populates a `rapidjson::Value &`, so the implementation is redundant.

**Comment by miloyip** [comment]
For two objects, it can be merged by:

~~~cpp
void MergeObject(Value& target, Value& source, Value::AllocatorType& allocator) {
    assert(target.IsObject());
    assert(source.IsObject());
    for (Value::MemberIterator itr = source.MemberBegin(); itr != source.MemberEnd(); ++itr)
        target.AddMember(itr->name, itr->value, allocator);
}

TEST(Document, MergeObject) {
    Document d1, d2(&d1.GetAllocator());
    d1.Parse("{\"key1\":\"value1\",\"key2\":\"value2\"}");
    d2.Parse("{\"key3\":\"value3\"}");
    MergeObject(d1, d2, d1.GetAllocator());
    StringBuffer sb;
    Writer<StringBuffer> writer(sb);
    d1.Accept(writer);
    EXPECT_STREQ("{\"key1\":\"value1\",\"key2\":\"value2\",\"key3\":\"value3\"}", sb.GetString());
}
~~~

However, in your case, this should be achieved by refactoring the code, such as:

~~~
class Base {
public:
    virtual void serialize(Value& v, Value::Allocator& allocator) {
       v.AddMember("b", b, allocator);
    }
    int b;
};

class Derived : public base {
    virtual void serialize(Value& v, Value::Allocator& allocator) {
        Base::serialize(v, allocator);
        v.AddMember("d", d, allocator);
    }
    int d;
};
~~~

If you only need to serial into a JSON, but not intermediate DOM representation, nor deserialization, you can refer to https://github.com/miloyip/rapidjson/blob/master/example/serialize/serialize.cpp

**Comment by alexandruirimiea** [comment]
Yes, I can confirm this works.

I also wrote the test case for the second part and it works too:

    class Base{
    public:
        virtual void serialize(Value& v, Value::AllocatorType& allocator){
            v.AddMember("b", b, allocator);
        }    
        int b = 1;
    };

    class Derived : public Base{
    public:
        virtual void serialize(Value& v, Value::AllocatorType& allocator){
            Base::serialize(v, allocator);
            v.AddMember("d", d, allocator);
        }
        int d = 2;
    };


    TEST(Document, TestDerivationConsistence) {
        Document d1;
        d1.SetObject();

        Base base;
        base.serialize(d1, d1.GetAllocator());

        StringBuffer sb;
        Writer<StringBuffer> writer(sb);
        d1.Accept(writer);
        EXPECT_STREQ(R"({"b":1})", sb.GetString());

        d1.SetObject();
        writer.Reset(sb);
        sb.Clear();

        Derived derived;
        derived.serialize(d1, d1.GetAllocator());

        d1.Accept(writer);
        EXPECT_STREQ(R"({"b":1,"d":2})", sb.GetString());
    }
