### ISSUE TITLE
Travis CI failed due to its migration

### ISSUE THREAD

**Issue by miloyip** [miloyip/rapidjson#491]
After Travis CI's [infrastructure migration](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future), RapidJSON cannot build doxygen successfully. There were two issues.

1. https://github.com/travis-ci/travis-ci/issues/5225 , temporarily fixed by a1c4f325cab87c0fa2ce5b2737750adbc905b279

2. GitHub authorization failure during uploading the doxygen output to gh-pages. No idea how to fix it yet, @pah ?

**Comment by pah** [comment]
I may have time to look at this next week. I'm currently traveling and don't have sufficient bandwidth right now.

**Comment by miloyip** [comment]
Not a problem. It may be just related to old git version as well.Have a good trip☺Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [rapidjson] Travis CI failed due to its migration (#491)From: "Philipp A. Hartmann" To: miloyip/rapidjson CC: Milo Yip I may have time to look at this next week. I'm currently traveling and don't have sufficient bandwidth right now.

**Comment by pah** [comment]
After a quick look, it seems indeed to be an issue with the outdated git version on the Travis hosts. We're using the Git [credential] [1] subsystem, which has been introduced in Git 1.7.12 (newer than 1.7.9).

As the upstream issue has been fixed, can you recheck if the error persists on our side?  And maybe revert a1c4f32 as well?

[1]: https://git-scm.com/docs/git-credential

**Comment by miloyip** [comment]
I re-tried a few days ago it still fail. But your recent PR passed Travis again. They seem have deployed the changes to the boxes now.
Thank you anyway.
