### ISSUE TITLE
operator[] can lead to corrupted NullValue

### ISSUE THREAD

**Issue by lietusme** [miloyip/rapidjson#492]
This code method is unsafe as it can return non-const reference to static and shared NullValue:

    template <typename SourceAllocator>
    GenericValue& operator[](const GenericValue<Encoding, SourceAllocator>& name) {
        MemberIterator member = FindMember(name);
        if (member != MemberEnd())
            return member->value;
        else {
            RAPIDJSON_ASSERT(false);    // see above note
            static GenericValue NullValue;
            return NullValue;
        }
    }

It should either add non existing value to object or return const reference. There is no way combine both. Other option would be to return pointer and nullptr would mean that member does not exist.

**Comment by miloyip** [comment]
Actually this operator assumes the member must exist. The else part is available mainly for diagnostic in debug mode. This API is simple and useful when the JSON is validated before.

For returning pointer kind of API, you may use `FindMember()` which returns a `MemberIterator` pointed to the member (containing key and value), or equaled to pass-the-end iterator `MemberEnd()` if the member was not exist.

A new alternative is the [JSON Pointer API](http://rapidjson.org/md_doc_pointer.html), which provides several options:

~~~cpp
// Access DOM by Get(). It return nullptr if the value does not exist.
if (Value* stars = Pointer("/stars").Get(d))
    stars->SetInt(stars->GetInt() + 1);

// GetWithDefault() returns reference. And it deep clones the default value.
Value& hello = Pointer("/hello").GetWithDefault(d, "world");
~~~
