### ISSUE TITLE
parser error about comma

### ISSUE THREAD

**Issue by mklong** [miloyip/rapidjson#496]
# parse error about comma

```
{
    "json":123,
}
```
When i parse json which has comma without any object following , rapidjson return errno 4 (kParseErrorObjectMissName) while other json parser return ok.
Which is standard?

**Comment by pah** [comment]
Quoting [RFC7159] [1]:
> An object structure is represented as a pair of curly brackets surrounding zero or more name/value pairs (or members).  A name is a string.  A single colon comes after each name, separating the name from the value.  A single comma separates a value from a following name.  The names within an object SHOULD be unique.
>
>      object = begin-object [ member *( value-separator member ) ]
>              end-object
>
>      member = string name-separator value

RapidJSON follows this strictly right now.  There have been enhancement requests to allow relaxation of these rules, see e.g. #36.

[1]: https://www.ietf.org/rfc/rfc7159.txt

**Comment by mklong** [comment]
thanks

**Comment by ranjithpp** [comment]
> Quoting [RFC7159](https://www.ietf.org/rfc/rfc7159.txt):
> 
> > An object structure is represented as a pair of curly brackets surrounding zero or more name/value pairs (or members).  A name is a string.  A single colon comes after each name, separating the name from the value.  A single comma separates a value from a following name.  The names within an object SHOULD be unique.
> > ```
> >  object = begin-object [ member *( value-separator member ) ]
> >          end-object
> > 
> >  member = string name-separator value
> > ```
> 
> RapidJSON follows this strictly right now. There have been enhancement requests to allow relaxation of these rules, see e.g. #36.

when said, followed strictly, does it throw any error today? i used the example program and when used two values, it Parse accepted
Modified JSON with reformatting:
{
    "hello": "rapidjson",
    "hello": "world",
    "t": true,
    "f": false,
    "n": null,
    "i": 2432902008176640000,
    "pi": 3.1416,
    "a": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        "Lua",
        "Mio"
    ],
    "author": "Milo Yip"
}
