### ISSUE TITLE
Character after incomplete literal is skipped while parsing

### ISSUE THREAD

**Issue by jschobben** [miloyip/rapidjson#507]
During some stress-testing with parsing of garbage-prefixed json messages, I noticed that sometimes rapidjson fails to parse a valid message when it is prefixed with a "t".

What appears to happen is that whenever a literal (i.e. "false", "true" or "null") is being parsed but it contains a syntax error (such as being only a "t" instead of "true"), the character immediately after the incorrect literal is thrown away.

For instance, this message fails to be parsed:
```json
t{"json": 42}
```

While this one parses fine (after some noise about the "x"):
```json
x{"json": 42}
```

I've made a change in reader.h, in the ParseTrue/ParseFalse/ParseNull methods, so that they do not Take() the next character if it isn't part of the literal.

Is the current behavior as intended? If not, I will submit my change as pull request.

**Comment by pah** [comment]
Is this a real gain to special-case the literals? What about
````json
[{"json": 42}
````
Do you want to only throw away the first bracket?  Currently, RapidJSON will consume the whole input, trying to find the closing array.

**Comment by miloyip** [comment]
How about

~~~js
"{"json": 42}
~~~

I think it will be difficult to define "garbage".

**Comment by jschobben** [comment]
I see your point. "parsing of garbage-prefixed json messages" is probably a silly use case anyway, and the whole message should just be skipped on parse errors.

A perhaps better description of the problem (and looking for realistic use cases :wink:):
After a parse error has occurred, in some cases one character is dropped from the input stream. This can also be the NULL character at the end of the message (i.e. when a message is truncated by the sender, or an incomplete transport). It's not consistently dropped for all errors though.

This could be an issue when a stream of multiple JSON messages, separated by NULL bytes, is being parsed one by one. In that case, when a parse error occurs the program using rapidjson would want to skip to the next NULL for the next message. But if a NULL is dropped, the program would skip the next message unnecessarily. Of course the calling program could take care of this case, but it is a bit of a hassle.

In general, this dropping happens in most places where a Take() is done before knowing for sure that the taken value is as expected.

Some truncated examples where the input stream is one byte past the NULL after the parse error:
- ```{"answer" :```
- ```[42```
- ```"\u123```
- ```"\uD800```

While for these messages the input stream still points at the NULL after the parse error (as I would expect):
- ```/*```
- ```{```
- ```"answer```

Of course changing this sort of thing always runs the risk that someone is depending on the current behavior. But if you think the risk is acceptable, I can prepare a patch to handle all parse errors like in the second set of examples, i.e. only call Take() after sufficient Peek()ing.

What do you think?

**Comment by miloyip** [comment]
I think the risk is acceptable as it does not guarantee on the position of cursor when parsing is failed.
I have several concerns:

1. Will it affect performance?
2. There are two parsers, normal and iterative. What about the behavior of the second one?
3. Can we list all test cases exhaustively?

**Comment by miloyip** [comment]
I have accidentally committed my proposed change to master ab250d21bc41b3a145d82330c92d30632980fb2f .

My answers to my questions:
1. There is no observable performance degradation.
2. null/true/false/string are shared by both parser.
3. Added error offset confirmation in unit tests to confirm the rectification. It can also ensure the consistency in future version.

Please review if this rectification is OK.

**Comment by jschobben** [comment]
I have reviewed the change, it looks good. Thanks for that.

Performance impact consists mostly of extra calls to Peek(), which is of course implemented by users themselves. But it's reasonable to assume their Peek() implementation will be lightweight I suppose.

The unit tests could be extended even more, by also checking how many bytes are read from the stream. I made a pull request, please have a look: #541

**Comment by miloyip** [comment]
Thank you a lot.
With more tests right now, the behavior becomes more clear now.
I close this.
