### ISSUE TITLE
NaN encoded as 2.696539702293474e308

### ISSUE THREAD

**Issue by stepelu** [miloyip/rapidjson#509]
I am aware that NaNs are not part of the JSON standard and I am not advocating adding the ability to encode/decode them.

However, currently NaNs are silently encoded as `2.696539702293474e308` which is very error prone.
It would be preferable to have an error thrown in Writer::Double() if a NaN is passed.

**Comment by miloyip** [comment]
Yes. This is not currently checked.

With the current `bool WriteDouble(double d)` API, I can make it return `false` if `d` is either NaN or infinity.

**Comment by stepelu** [comment]
Thanks for the prompt fix! 

While Nans should be checked, I am unsure about the Inf case. 
I am actually able to get them forth and back correctly, do you have any opinion on the matter?

**Comment by miloyip** [comment]
I don't think it is able to make a roundtrip for +/-inf.
#36 has proposed to add relaxed JSON syntax for NaN/though.
If you think #510 is OK, I will merge it.

**Comment by stepelu** [comment]
Yes, it is fine with me, thank you.
