### ISSUE TITLE
RapidJSON cannot parse UTF-8 encoding string

### ISSUE THREAD

**Issue by nasacj** [miloyip/rapidjson#512]
``` cpp
rapidjson::Document doc;
doc.Parse<0>(strJson.c_str()).HasParseError()
```
I am trying to parse the JSON string from a file which is UTF-8 encoded, read them into a string with common std getline() way, but the *HasParseError()* function always return *true*. 
It is OK to parse the string with GB2312 encoded, but always failed on UTF-8 encoded.

**Comment by miloyip** [comment]
Can you provide code for reading the file and the problematic binary file?

**Comment by nasacj** [comment]
**code:**
``` cpp
ifstream fin("json.txt");
std::string strJson
getline(fin,str);
rapidjson::Document doc;
if(doc.Parse<0>(strJson.c_str()).HasParseError())
    std::cout << "ERROR" << endl;
else
    std::cout << "OK" << std:endl;
```
**File:**
[json.txt](https://github.com/miloyip/rapidjson/files/101731/json.txt)

**Comment by nasacj** [comment]
I find the root cause:
The file I uploaded "json.txt" is UTF-8 with BOM encoding.
I tried with UTF-8 without BOM, RapidJSON works well.

**Comment by miloyip** [comment]
Actually there is a `EncodedInputStream` which can handle BOM. It wraps a byte stream (e.g. `FileReadStream`) to an encoded stream.

**Comment by nasacj** [comment]
Could you please show me some piece of sample codes of `EncodedInputStream` usage

**Comment by miloyip** [comment]
You may refer to [Encoded Streams](http://rapidjson.org/md_doc_stream.html#EncodedStreams).
