### ISSUE TITLE
[question] code works with SizeType but don't know how to use the iterator

### ISSUE THREAD

**Issue by toudi** [miloyip/rapidjson#516]
I have this json:

```
[
 {
  "pk": 1,
  "name": "foo"
 }
]
```
I am able to read it using the following code:

```
const rapidjson::Value& obj = *doc;

for (rapidjson::SizeType i = 0; i < obj.Size(); i++)
        printf("obj[%d]["pk"] = %d\n", i, obj[i]["pk"].GetInt());
```

so far, so good. Now, I want to achieve the same thing using the iterator, so I did this:

```
for (rapidjson::Value::ConstValueIterator itr = obj.Begin(); itr != obj.End(); ++itr) {
        printf("obj.pk=%d\n", itr["pk"].GetInt());
    }
```

but the error I'm receiving is as following:

```
error: invalid types ‘rapidjson::GenericValue<rapidjson::UTF8<> >::ConstValueIterator {aka const rapidjson::GenericValue<rapidjson::UTF8<> >*}[const char [3]]’ for array subscript
```

this looks rather cryptic to me. What I am doing wrong here?

best regards,
mateusz

**Comment by miloyip** [comment]
As `itr` is an iterator, `*itr` is the `Value&` type (which is the JSON array). So the correct code should be `(*itr)["pk"]`.

This usage is the same as using STL, e.g. `std::map<std::string, std::map<std::string, int>>`.

**Comment by toudi** [comment]
I could have sworn that I have tried (*itr) but obviously I haven't.. This must have been a long night :D

sorry for asking such dumb question and thank you very much for the wonderful rapidjson!
