### ISSUE TITLE
error: comparison is always true due to limited range of data type

### ISSUE THREAD

**Issue by supertwang** [miloyip/rapidjson#517]
I'm trying to compile on Debian Wheezy, on a BeagleBone Black and getting the following errors:

[ 10%] Building CXX object example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o
In file included from /root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/example/capitalize/capitalize.cpp:6:0:
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h: In instantiation of ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Tokenize(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch) [with SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator; rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Ch = char]’:
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:1645:41:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:400:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:440:53:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/example/capitalize/capitalize.cpp:60:33:   required from here
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:1303:9: error: comparison is always true due to limited range of data type [-Werror=type-limits]
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h: In instantiation of ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 0u; SEncoding = rapidjson::UTF8<>; TEncoding = rapidjson::UTF8<>; InputStream = rapidjson::FileReadStream; OutputStream = rapidjson::FileReadStream; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’:
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:712:13:   required from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:1224:23:   required from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:414:13:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:440:53:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/example/capitalize/capitalize.cpp:60:33:   required from here
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:756:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h: In instantiation of ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 0u; SEncoding = rapidjson::UTF8<>; TEncoding = rapidjson::UTF8<>; InputStream = rapidjson::FileReadStream; OutputStream = rapidjson::GenericReader<rapidjson::UTF8<>, rapidjson::UTF8<> >::StackStream<char>; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’:
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:721:13:   required from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:1224:23:   required from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:414:13:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:440:53:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/example/capitalize/capitalize.cpp:60:33:   required from here
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:756:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
In file included from /root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/example/capitalize/capitalize.cpp:7:0:
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/writer.h: In instantiation of ‘bool rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::WriteString(const Ch*, rapidjson::SizeType) [with OutputStream = rapidjson::FileWriteStream; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator; rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char; rapidjson::SizeType = unsigned int]’:
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/writer.h:126:39:   required from ‘bool rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::String(const Ch*, rapidjson::SizeType, bool) [with OutputStream = rapidjson::FileWriteStream; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator; rapidjson::Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator>::Ch = char; rapidjson::SizeType = unsigned int]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/example/capitalize/capitalize.cpp:31:58:   required from ‘bool CapitalizeFilter<OutputHandler>::String(const char*, rapidjson::SizeType, bool) [with OutputHandler = rapidjson::Writer<rapidjson::FileWriteStream>; rapidjson::SizeType = unsigned int]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:717:13:   required from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseString(InputStream&, Handler&, bool) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:1224:23:   required from ‘void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseValue(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:414:13:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 0u; InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/reader.h:440:53:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with InputStream = rapidjson::FileReadStream; Handler = CapitalizeFilter<rapidjson::Writer<rapidjson::FileWriteStream> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/example/capitalize/capitalize.cpp:60:33:   required from here
/root/devel/3rdparty/rapidjson/rapidjson-1.0.2-4f20bdc/include/rapidjson/writer.h:307:18: error: comparison is always true due to limited range of data type [-Werror=type-limits]
cc1plus: all warnings being treated as errors
make[2]: *** [example/CMakeFiles/capitalize.dir/capitalize/capitalize.cpp.o] Error 1
make[1]: *** [example/CMakeFiles/capitalize.dir/all] Error 2
make: *** [all] Error 2
\make install

**Comment by miloyip** [comment]
They are actually warnings. Maybe some version of compilers trigger warnings differently. Can you try a newer version of RapidJSON?

**Comment by supertwang** [comment]
I'm finding these same errors on the main branch checkout.  Is there a newer version?  cc1plus says: 'all warnings being treated as errors'  ... might that be relevant?  Is there any way to prevent that?

Would it be safe in this case to #ifdef the 'always true' part of the comparison out?

**Comment by supertwang** [comment]
OK, I got it to ignore these by changing the line in example/CMakeLists.txt to not complain about the specific error being encountered.  Hopefully this will help someone else get past this.  Thanks for your quick feedback.  GREAT LIBRARY by the way!

from:
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wextra -Weffc++ -Wswitch-default")

to:
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wall -Wno-error=type-limits -Wextra -Weffc++ -Wswitch-default")
