### ISSUE TITLE
VS 2013 warning C4251

### ISSUE THREAD

**Issue by fjhub** [miloyip/rapidjson#519]
I recently came across this library and added it to my codebase which is primarily C with some C++.  I use cmake to build for both OSX and Windows.  I am not that proficient with C++ and even less so with Windows and Visual Studio.  In adding support for this in one of my C++ classes, I quickly came across the following warning from VS:
```c
warning C4251: 'MyClass::document' : class 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::Memory
PoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>' needs to have dll-interface to be used by clients of class 'MyClass'
```
I searched this and attempted to find a way to make this warning go away without having to specify a compiler flag to disable this warning.  The closest thing that I came across was the following:
```c
https://support.microsoft.com/en-us/kb/168958
```
Unfortunately I don't know anything about templates and gave up after spending too much time trying to include a class member for a **document** and an **allocator** using RapidJSON's types in my class.

The solution I came up with was to use a **void** pointer for both of these objects and then cast them appropriately when I used them.  This has worked fine but it has always bothered me that I couldn't figure out how to solve the original issue.  It would have also been nice to be able to access data using the bracket notation:
```c
 document["hello"] = "world";
```
which I cannot do using the **void** pointer solution because I get a compiler error (illegal index, indirection not allowed) if I attempt to use the following (no matter how hard I wish that it would work):
```c
 ((rapidjson::Document *)document)["status"] = "world";
```
I'm open to any suggestions that might help be resolve the C4251 warning.  I appreciate your help and the fact that this library exists in the first place.  Thanks for your efforts!

**Comment by pah** [comment]
In your final line, it should be sufficient to add a dereference (note the initial `*`):
````cpp
(*(rapidjson::Document *)document)["status"] = "world";
````

Regarding the warning in general, it seems you're exporting `MyClass` through a DLL.  In this case, it actually makes sense to hide the RapidJSON internals from this interface.  Instead of using a `void*`, you could try to push the RapidJSON dependency to the `.cpp` file by using the [Pimpl idiom][1].

[1]: https://en.wikipedia.org/wiki/Opaque_pointer

**Comment by fjhub** [comment]
I cannot believe I didn't try this.  I know tried
```c
 *((rapidjson::Document *)document)["status"] = "world";
```
I guess I should have looked at my operator precedence...what a rookie mistake.  my bad.

thanks a bunch.

**Comment by miloyip** [comment]
Just as a note, I think it may be a good idea to create forward declaration headers, like `documentfwd.h`, or simply an single header `rapidjsonfwd.h` for all classes.
So that users can declare a typed pointer in header without including the whole thing.
@pah, what do you think?

**Comment by pah** [comment]
I like the idea of having a forward header (`rapidjsonfwd.h`, or simply `rapidjson/fwd.h`?) listing the external classes and their default typedefs. :+1:

**Comment by miloyip** [comment]
Added `rapidjson/fwd.h` in 8cb978dc1526089800c3546f2ae31c5caa890363.
