### ISSUE TITLE
when an json contain an json

### ISSUE THREAD

**Issue by xcl3721** [miloyip/rapidjson#521]
phpcode

$a=array(
    "abc\\ddd"=>"xxx",
);

$b=array(
   "m"=>json_encode($a),
)

echo json_encode($b);

it's will output string {"m":"{\"abc\\\\ddd\":\"xxx\"}"}

but when i used rapid json parser it and get m field
it will give me a string like {"abc\ddd":"xxx"} 
i expect it output {"abc\\\\ddd":"xxx"}

please help me

**Comment by miloyip** [comment]
I tested it on my machine it works normal:
~~~php
<?php
$a=array(
    "abc\ddd"=>"xxx",
);
echo json_encode($a), PHP_EOL;
$b=array(
    "m"=>json_encode($a),
);
echo json_encode($b), PHP_EOL;
?>
~~~

Output:
~~~js
{"abc\\ddd":"xxx"}
{"m":"{\"abc\\\\ddd\":\"xxx\"}"}
~~~

**Comment by xcl3721** [comment]
yes and when i using rapidjson decode it 
and getString() with m field
it's will give me a {"abc\ddd":"xxx"}  string like this

**Comment by miloyip** [comment]
I cannot reproduce any problem:

test.json:
~~~js
{"m":"{\"abc\\\\ddd\":\"xxx\"}"}
~~~

test.cpp
~~~cpp
#include "rapidjson/document.h"
#include "rapidjson/filereadstream.h"
#include <cstdio>

using namespace rapidjson;

int main() {
    char buffer[256];
    FILE* fp = fopen("test.json", "r");
    FileReadStream fs(fp, buffer, sizeof(buffer));
    
    Document d;
    d.ParseStream(fs);
    fclose(fp);
    printf("%s\n", d["m"].GetString());

    Document d2;
    d2.Parse(d["m"].GetString());
    printf("%s -> %s\n", d2.MemberBegin()->name.GetString(), d2.MemberBegin()->value.GetString());

    return 0;
}
~~~

Output:
~~~
{"abc\\ddd":"xxx"}
abc\ddd -> xxx
~~~

**Comment by xcl3721** [comment]
opps thank u.
 lets me upgrade my package and test it
