### ISSUE TITLE
Iterating over the DOM

### ISSUE THREAD

**Issue by sidprice** [miloyip/rapidjson#523]
I am trying to learn about rapidJSON for my project and while I have made a good start I am hitting a roadblock with trying to iterate over the DOM I have generated from my input JSON. Ultimately I need to be able to query the DOM using the URI supplied by other code. I am hoping that "pojnters" will allow me to do this, however initially I would just like to iterate through the nested objects in the DOM.

Here is a snippet of the start of the JSON I am working with:

`{
    "ObjectModel": {
        "Test": {
             "list": {
                "_list": "one|two|three",
                "_value": "One"
              }
           },
           "Active_Abstraction": {
              "_type": "string",
              "_value": "Abstraction1"
            },
            "Info": { ...`

I have the following code to parse the JSON and then iterate over the DOM:

`	ifstream inFile;
	inFile.open(AbstractionObjectModelFilename);	//open the input file

	if (inFile.is_open() == true)
	{
		stringstream strStream;
		strStream << inFile.rdbuf();				//read the whole file into a string stream
		std::string str = strStream.str();			//str holds the content of the file
		const char* json = str.c_str();				// JSON parser requires a "const char *" as input
		OM.Parse(json);								// Parse the JSON string into the object model
		//
		// Assert the root is an object
		//
		if (OM.IsObject() == true)
		{
			const char* kTypeNames[] =
			{ "Null", "False", "True", "Object", "Array", "String", "Number" };
			for (Value::ConstMemberIterator itr = OM.MemberBegin(); itr != OM.MemberEnd(); ++itr)
			{
				printf("Type of member %s is %s\n",
					itr->name.GetString(), kTypeNames[itr->value.GetType()]);
			}
		}
	}
`
When this runs only the type of the "ObjectModel" object is output, the iteration goes no further.

I hope someone can help me get this to work.
Sid

**Comment by sidprice** [comment]
I think I have answered my own question, what I have done is to detect when the value of a node is an object and to get an iterator for that object and recursively call my iteration method.

My remaining question is really needing some examples of using pointers to access nested nodes using a simple URI, e.g. "/ObjectModel/Test/_list", using the above JSON in my DOM.

Thanks,
Sid

**Comment by miloyip** [comment]
I am not sure if this is what you need:

~~~cpp
// If you are not sure that path can be resolved, check if return value is non-null
if (Value* list = GetValueByPointer(OM, "/ObjectModel/Test/_list"))
    printf("%s\n", list->GetString());

// Otherwise
printf("%s\n", GetValueByPointer(OM, "/ObjectModel/Test/_list"))->GetString());
~~~

**Comment by sidprice** [comment]
Yes that tells me what I need to know. Many thanks,
Sid
