### ISSUE TITLE
how to integrete rapidjson into project not using cmake?

### ISSUE THREAD

**Issue by hiyijian** [miloyip/rapidjson#524]
Is there an easy way to achive this? 
thanks

**Comment by spl** [comment]
RapidJSON is primarily a header-only library. CMake is used to build tests and benchmarks.

So you can copy the `.h` files or the `include/rapidjson` directory into your project. Alternatively, if you're using `git`, you can add this repository as a `git` submodule.

**Comment by hiyijian** [comment]
wow, that's great. I did not  notice that. 
Sorry.
Thanks

**Comment by spl** [comment]
No problem. :)
