### ISSUE TITLE
Segmentation Fault on ARM

### ISSUE THREAD

**Issue by sombol20** [miloyip/rapidjson#547]
I'm having a segmentation fault when running the following code with optimization enabled, with GCC 4.9, on a ARM platform.
`
...
#include "extern/rapidjson/document.h"

void* MyThread(void*)
{
   std::cout << "Start of MyThread" << std::endl;
   
   rapidjson::Document doc;

   doc.Parse("{ \"NAME\": \"Peter\", \"AGE\": 38, \"Male\": true}");

   std::cout << "End!";
   return NULL;
}

int main(int argc, char** argv) 
{
   pthread_t thread;
   
   pthread_create(&thread, NULL, &MyThread, NULL);
   
   std::string str;
   std::cout << "Press return..." << std::endl;
   std::getline(std::cin, str);
   
   return 0;
}
`

No issue if I put the code outside a thread.  I can't duplicate on Windows (VS2012).  No issue when optimization are disabled.

**Comment by miloyip** [comment]
I cannot reproduce this on QEMU with [Debian on armel](https://people.debian.org/~aurel32/qemu/armel/):

    qemu-system-arm -M versatilepb -kernel vmlinuz-3.2.0-4-versatile -initrd initrd.img-3.2.0-4-versatile -hda debian_wheezy_armel_desktop.qcow2 -append "root=/dev/sda1"

And then installed g++-4.9 (4.9.2) and build [issue547.cpp](https://gist.github.com/miloyip/3cfc08eabb6f2c2ed7f8) with

   g++ -O3 -Iinclude -lpthread issue547.cpp

It did run normally.

Please provide additional information.

**Comment by sombol20** [comment]
Was a setup issue, I was compiling with 1.0.2.  Works fine with latest code.  Thanks.
