### ISSUE TITLE
SchemaDocument: Copy constructor

### ISSUE THREAD

**Issue by cviebig** [miloyip/rapidjson#552]
Hello @miloyip,

thank you for merging the Validator branch so fast.

I'm about to use it now and found a difference in behauvior of `Document` and `SchemaDocument` where I wonder if this is important. To me it seems that the copy constructor of `SchemaDocument` is implicitly deleted while `Document` maybe copied. Did I perceive this correctly? Alternatively I can of course use smart pointers, but just being curious, thus asking here :) So feel free to close it without much explanations please.

	#include <rapidjson/document.h>
	#include <rapidjson/schema.h>

    ::rapidjson::Document
    load_json_from_file(
            const std::string& path_to_file) {
        std::string json = readFileContent(path_to_file);
        ::rapidjson::Document document;
        document.Parse(json.c_str());
        return document;
    }

    ::rapidjson::SchemaDocument
    load_schema_from_file(const std::string& path_to_file) {
        ::rapidjson::Document const& document =
            load_json_from_file(path_to_file);
        return ::rapidjson::SchemaDocument(document);
    }
 
Stacktrace:

    SchemaDocument const& schema = load_schema_from_file(schema_file);
    Document const& document = load_json_from_file(path_to_file);
 
	json_parser.cpp: In function ‘rapidjson::SchemaDocument load_schema_from_file(const string&)’:
	json_parser.cpp:1397:52: error: use of deleted function ‘rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > >::GenericSchemaDocument(const rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > >&)’
		     return ::rapidjson::SchemaDocument(document);
		                                                ^
	In file included from json_validator.hpp:7:0,
		             from json_parser.cpp:42:
	/usr/include/rapidjson/schema.h:1304:7: note: ‘rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > >::GenericSchemaDocument(const rapidjson::GenericSchemaDocument<rapidjson::GenericValue<rapidjson::UTF8<> > >&)’ is implicitly deleted because the default definition would be ill-formed:
	 class GenericSchemaDocument {
		   ^
	In file included from /usr/include/rapidjson/reader.h:23:0,
		             from /usr/include/rapidjson/document.h:20,
		             from json_parser.cpp:13:
	/usr/include/rapidjson/internal/stack.h:212:5: error: ‘rapidjson::internal::Stack<Allocator>::Stack(const rapidjson::internal::Stack<Allocator>&) [with Allocator = rapidjson::CrtAllocator]’ is private
		 Stack(const Stack&);
		 ^
	In file included from json_validator.hpp:7:0,
		             from json_parser.cpp:42:
	/usr/include/rapidjson/schema.h:1304:7: error: within this context
	 class GenericSchemaDocument {
		   ^
	In file included from /usr/include/rapidjson/reader.h:23:0,
		             from /usr/include/rapidjson/document.h:20,
		             from json_parser.cpp:13:
	/usr/include/rapidjson/internal/stack.h:212:5: error: ‘rapidjson::internal::Stack<Allocator>::Stack(const rapidjson::internal::Stack<Allocator>&) [with Allocator = rapidjson::CrtAllocator]’ is private
		 Stack(const Stack&);
		 ^
	In file included from json_validator.hpp:7:0,
		             from json_parser.cpp:42:
	/usr/include/rapidjson/schema.h:1304:7: error: within this context
	 class GenericSchemaDocument {
		   ^
	ninja: build stopped: subcommand failed.

**Comment by miloyip** [comment]
It is actually due to that `Document` supports move constructor in C++11.
I have added the move constructor for `SchemaDocument` in PR #554.

**Comment by cviebig** [comment]
Cool, thank you :)
