### ISSUE TITLE
Is the nuget package official?

### ISSUE THREAD

**Issue by petke** [miloyip/rapidjson#565]
Hi

https://www.nuget.org/packages/rapidjson/

Is this nuget package official? As in did you make it, or do you know and trust the people who made it?

Is it safe to install? (No security vulnerabilities added on purpose).

If it is official, is it being updated regularly?

**Comment by miloyip** [comment]
It is not maintained by me. I do not know the maintainer.

Since RapidJSON is header-only library, not involving binary distribution, I think it should be quite safe to install. However, GitHub is current the only official repository for RapidJSON distribution.
