### ISSUE TITLE
error: assuming signed overflow does not occur when assuming that (X - c) > X is always false

### ISSUE THREAD

**Issue by cyrus-and** [miloyip/rapidjson#566]
Something between 9515b9cc949e19f6aa0b904aac54fb65661b3c6d and ef5e74a200f5feab8714619dc1136ca9e96de004 (the current master branch) seems to have broken the compilation.

With `cmake . && make` I get:

```
[...]
Scanning dependencies of target simplewriter
[100%] Building CXX object example/CMakeFiles/simplewriter.dir/simplewriter/simplewriter.cpp.o
In function ‘int main()’:
cc1plus: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
cc1plus: all warnings being treated as errors
```

According to `git bisect` the first bad commit is 7f9921fc60c78bf6760ae6439c038c59fd26220a.

I'm using gcc version 4.9.2 (Debian 4.9.2-10).

**Comment by miloyip** [comment]
Thank you for your report.
