### ISSUE TITLE
Strange behavior of the Array

### ISSUE THREAD

**Issue by stefanosimula** [miloyip/rapidjson#567]
Hi,

I'm trying to parse the following document:

```
{
	"objects": [
		{
			 "name": "MyName",
			    "t": true ,
			    "n": null,
			    "i": 123,
			    "pi": 3.1416,
    			"a": [1, 2, 3, 4]
		}
	]
}
```

If I use the pointer of the object document, like this:

`Value* objects = &(*pDocument)["objects"]`

And I try to access to the first element, in a simple for

```
for (SizeType i = 0; i < objects->Size(); i++)
        {
            WValue& currentObj = objects[i];
}
```

The first element of the array (so currentObj) is a pointer of the array, instead I'm expecting that the element was the first item on the collection.

The strange thing is that I'm able to retrieve the first item on the collection using this piece of code:

```
for (SizeType i = 0; i < objects->Size(); i++)
{
            WValue& currentObj = objects[0][i];
}
```

Someone can explain what I'm doing wrong?

Thanks,
Ste

**Comment by miloyip** [comment]
Since `objects` is a pointer, the code to access the i-th element should be:
~~~
(*objects)[i]
~~~
