### ISSUE TITLE
Writer/PrettyWriter output overlap

### ISSUE THREAD

**Issue by adfmoreira** [miloyip/rapidjson#569]
I'm trying to create a json using rapidjson and I am having some unexpected problems with generating a proper output. As far as I can tell from the documentation I am doing nothing out of the ordinary here.

I'm creating and populating a document like this:

    Document d;
	d.SetObject();

	rapidjson::Document::AllocatorType& allocator = d.GetAllocator();

	size_t sz = allocator.Size();

	d.AddMember("version",	1, allocator);
	d.AddMember("testId",	2, allocator);
	d.AddMember("group",	3, allocator);
	d.AddMember("order",	4, allocator);

	Value tests(kArrayType);
	Value obj(kObjectType);
	Value val(kObjectType);

	obj.AddMember("id", 1, allocator);

	string description = "a description";
	val.SetString(description.c_str(), static_cast<SizeType>(description.length()), allocator);
	obj.AddMember("description", val, allocator);

	string help = "some help";
	val.SetString(help.c_str(), static_cast<SizeType>(help.length()), allocator);
	obj.AddMember("help", val, allocator);

	string workgroup = "a workgroup";
	val.SetString(workgroup.c_str(), static_cast<SizeType>(workgroup.length()), allocator);
	obj.AddMember("workgroup", val, allocator);

	val.SetBool(true);
	obj.AddMember("online", val, allocator);

	tests.PushBack(obj, allocator);
	d.AddMember("tests", tests, allocator);

	// Convert JSON document to string
	rapidjson::StringBuffer strbuf;
	rapidjson::PrettyWriter<rapidjson::StringBuffer> writer(strbuf);
	d.Accept(writer);

When I run this code, I'm expecting to obtain this json:

```
{
	"version": 1,
	"testId": 2,
	"group": 3,
	"order": 4,
	"tests": [
		{
			"id": 1,
			"description": "a description",
			"help": "some help",
			"workgroup": "a workgroup",
			"online": true
		}
	]
}
```

but the actual generated output is...

```
{
	"version": 1,
	"testId": 2,
	"group": 3,
	"order": 4,
	"tests": [
		{
			"id": 1,
			"description": "a description",
			"help": "some help",
			"workgroup": "a workgroup",
			"online": tr{
	"version": 1,
	"testId": 2,
	"group": 3,
	"order": 4,
	"tests": [
		{
			"id": 1,
			"description": "a description",
			"help": "some help",
			"workgroup": "a workgroup",
			"online": true
		}
	]
}
```

If I use `Writer` instead of `PrettyWriter` it works for this particular example, but if I keep adding entries it will eventually happen as well.

As it is overwriting the output, it seems to be a problem with the `allocator`(?)

**Comment by adfmoreira** [comment]
This code is running in an MFC app.

I ran it in a simple console app and it runs fine. Then I ran it in a simple MFC single document app and it works fine as well, so it will be something to do with my application. 

I ran it in my app InitInstance() to rule out other threads and the behaviour is wrong as well. It might be something to do with order of initialization?

**Comment by miloyip** [comment]
How do you output the JSON? I think that part may be suspicious.

**Comment by adfmoreira** [comment]
You are a minute late ;) 

I think there is a problem with OutputDebugString() because if I write the string returned by GetString() to a file, it is as expected.
