### ISSUE TITLE
Slow member find

### ISSUE THREAD

**Issue by blackmanos** [miloyip/rapidjson#570]
Hello
my test code
http://pastebin.com/Au1M3fzm
What am I doing wrong?
Find member very slow.

**Comment by andrusha97** [comment]
Internally objects are just arrays of key-value pairs. So FindMember scans the array sequentially. Probably it's not supposed to be fast.

**Comment by pah** [comment]
Try moving the random number generation out of the benchmarking loop.  To me, this looks like this affects the measurement significantly.

**Comment by miloyip** [comment]
Memory query is currently, deliberately O(n), which is optimized for adding members instead of querying memory. See #102
For large data set, please convert the DOM to suitable data structure, or using SAX to build your own data structure.
