### ISSUE TITLE
0 and 1 are not considered doubles or floats?

### ISSUE THREAD

**Issue by JonMarbach** [miloyip/rapidjson#573]
Hi there - I'm new to JSON and GitHub, but I've run into a problem (well, perhaps an annoyance) with using rapidjson to read files written by another library. Firstly - let me say a quick thanks for making rapidjson: I've switched to it due to some very high memory consumption in another library and it certainly lives up to its name (at least, as long as you don't use the istreamwrapper :) )

Here's the problem. The other library I used wrote out JSON files like this:
```
			"normals" : 
			[
				[
					[
						0,
						0,
						1
					],
					[
						0,
						0,
						1
					],

```

The values I had passed to it were actually floating point 1's and 0's but its writer truncates those to "1" and "0" with no decimal point. Rapidjson asserts-out if I try to read these as floats/doubles which means I have to complicate my reader like this:

```
normal.x = jsonNormal[0].IsFloat()? jsonNormal[0].GetFloat() : static_cast<float>(jsonNormal[0].GetInt());
normal.y = jsonNormal[1].IsFloat()? jsonNormal[1].GetFloat() : static_cast<float>(jsonNormal[1].GetInt());
normal.z = jsonNormal[2].IsFloat()? jsonNormal[2].GetFloat() : static_cast<float>(jsonNormal[2].GetInt());

```

I can tell from searching through some other issues that you take great care to adhere to the spec and I have no idea what the spec has to say about this, but would it be possible to allow treating integers as double, or at least a special-case for 0 and 1 (as many compilers do) since they are exactly representable?

Apologies in advance if I've missed something obvious...

**Comment by miloyip** [comment]
It was a mistake. `GetFloat()` should be valid when it is a number type.

**Comment by miloyip** [comment]
Thank you for your report.

**Comment by JonMarbach** [comment]
Thanks for the quick fix - and glad the report was helpful!
