### ISSUE TITLE
 JSON parsing fails with Assertion `IsObject()' failed

### ISSUE THREAD

**Issue by prashantabkari** [miloyip/rapidjson#578]
I am trying to parse the data received from a server with rapidJSON . Following is the exact string that is received
 
[{"Node":"9478149a08f9","Address":"172.17.0.2","ServiceID":"HSS","ServiceName":"HSS","ServiceTags":[],"ServiceAddress":"","ServicePort":6666,"ServiceEnableTagOverride":false,"CreateIndex":2855,"ModifyIndex":2855}] 

The above is a valid JSOn string 
``
int main(void)
{
  CURL *curl;
  CURLcode res;

  struct MemoryStruct chunk;

  chunk.memory = (char *)malloc(1);  /* will be grown as needed by the realloc above */
  chunk.size = 0;    /* no data at this point */

  /* In windows, this will init the winsock stuff */
  curl_global_init(CURL_GLOBAL_ALL);

  /* get a curl handle */
  curl = curl_easy_init();
  if(curl) {
    /* First set the URL that is about to receive our POST. This URL can
       just as well be a https:// URL if that is what should receive the
       data. */
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:8500/v1/catalog/service/HSS");
    /* Now specify the POST data */

    // Set the callbackfunction to handle the JSON string
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writefunc);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &chunk);
    /* Perform the request, res will get the return code */
    res = curl_easy_perform(curl);
    /* Check for errors */
    if(res != CURLE_OK)
      fprintf(stderr, "curl_easy_perform() failed: %s\n",
              curl_easy_strerror(res));

    /* always cleanup */
    curl_easy_cleanup(curl);
  }

  std::string str;
  str.assign(chunk.memory,chunk.size);

  cout<<"The string response is :"<<str<<endl;
  Document d;
  d.Parse(str.c_str());

  assert(d.IsObject());

<-- It fails here

The JSON data is valid but not sure why its still failing.

**Comment by erikfroseth** [comment]
Hi,

It fails because the root of your document is an Array, and not an Object. See that the entire object is wrapped around '[   ]', and not '{  }'.

If you change your assertion to "assert(d.IsArray())", it should pass.

**Comment by prashantabkari** [comment]
Sorry it failed. 

httpcl: httpClient.cpp:89: int main(): Assertion `d.IsArray()' failed.

**Comment by prashantabkari** [comment]
I even tried to iterate assuming that its an array. Still it failed.

**Comment by prashantabkari** [comment]
I tried even parsing it using an iterator. It failed. That is because the JSON string that is obtained doesn't have a key at all. For example below string doesn't have a key at all. it just has an array of strings. So this string has to be tweaked? 
[{"Node":"9478149a08f9","Address":"172.17.0.2","ServiceID":"HSS","ServiceName":"HSS","ServiceTags":[],"ServiceAddress":"","ServicePort":6666,"ServiceEnableTagOverride":false,"CreateIndex":2855,"ModifyIndex":2855}]

**Comment by prashantabkari** [comment]
Ok it worked this time. The rapidjson documentation is a bit confusing and doesnt give full details. I was able to iterate through the array and get the exact string.
