### ISSUE TITLE
Is there a way to convert Object to std::string?

### ISSUE THREAD

**Issue by europelee** [miloyip/rapidjson#579]
for example:

json string {"h":"d", "sub":{"q":1, "e":"22"}}

use rapidjson to parse it,   we can get   Value & sub = document["sub"],  but sub is a Object, I want to convert it into a string({"q":1, "e":"22"}),  i can not find any api (like std::string Object2str(Value & o) )to do that, so i have to travel every member of Object and convert them to string?

**Comment by miloyip** [comment]
I am not sure what do you mean by converting an object to a string. If you mean converting a value to JSON, then it is the same as converting a document to JSON:
~~~cpp
StringBuffer sb;
Writer<StringBuffer> writer;
sub.Accept(writer);
std::string s = sb.GetString();
~~~

**Comment by europelee** [comment]
thanks!

**Comment by guoxiao** [comment]
@miloyip I think this line:
`Writer<StringBuffer> writer;`
should be
`Writer<StringBuffer> writer(sb);`

**Comment by miloyip** [comment]
@guoxiao Yes. I updated it. Thank you.

**Comment by AndrewOfC** [comment]
template<typename T>
string stringify(const T& o)
{
	StringBuffer sb;
	Writer<StringBuffer> writer(sb);
	o.Accept(writer);
	return sb.GetString();
}

**Comment by miloyip** [comment]
> Rather:
> 
> ```c++
> std::string stringify(const rapidjson::Value& v)
> {
> 	if (v.IsString())
> 		return { v.GetString(), v.GetStringLength() };
> 	else
> 	{
> 		rapidjson::StringBuffer strbuf;
> 		rapidjson::Writer<rapidjson::StringBuffer> writer(strbuf);
> 		v.Accept(writer);
> 		return { strbuf.GetString(), strbuf.GetLength() };
> 	}
> }
> ```
> 
> Faster and will also prevent quotes around from being added if the value is already a string.

JSON and JSON string value are two different concepts. Just returning the string value is not "stringifying a JSON".
