### ISSUE TITLE
Internal regex crash

### ISSUE THREAD

**Issue by ktrushin** [miloyip/rapidjson#583]
Passing special regex pattern to `rapidjson::internal::GenericRegex` class leads to extremely high memory consumption and crash due to 'out of memory' error. The following snippet when added to `regextest.cpp` reproduces the issue:
```
TEST(Regex, QuantifierExact4) {
    Regex re("[0-9]{99999}");
    ASSERT_TRUE(re.IsValid());
}
```
Running `./build/bin/unittest` just shows failed test but running `./build/bin/unittest --gtest_throw_on_failure` crashes with segmentation fault (rapid increase in memory usage can be noticed with tools like `top`).

The reproduction is in branch `regex_crash` in ktrushin/rapidjson repository.

**Comment by wingc-china** [comment]
Tried to get a repro. Only reproduces when the binary is built from g++.
The unittest.exe binary built from VC runs well but just with run time like 40~50ms while other Regex test finishes like 0ms.

**Comment by miloyip** [comment]
Sorry for late reply on this. I have been thinking on this for quite some time, with the error reporting mechanism of `SchemaValidator` regarding to regex.

I have not reproduced this yet. But this should be related to the DFA nature of the regex, and the current implementation requires `O(n)` space where `n` is the quantifier. This may not be what people expected (I think most people assume `O(1)` for this).

The question is that, `O(n)` space should still be runnable for `n = 10^6`.

I will try to see what costs the problem. And may be it should have a default, customizable limit for quantifier.

Another issue that, when regex is invalid during construction, there is no error reporting mechanism to show what error occurs and where does it occurs. It should be better report this. And the `SchemaValidator` should somehow able to obtain this piece of information.

**Comment by miloyip** [comment]
It really was a bug 😭.

**Comment by miloyip** [comment]
BTW, construction of this regex costs 6ms in release mode on Travis. This is actually `O(n)` as well.

**Comment by miloyip** [comment]
@wingc-china Just as a note. I think, the reason that it does not crash on VC is due to the reallocation returns the same original address.
