### ISSUE TITLE
Generic SkipWhiteSpace in reader.h is inefficient

### ISSUE THREAD

**Issue by razorx922** [miloyip/rapidjson#594]
The generic implementation of SkipWhiteSpace is inefficient as it does four InputStream::Peek() calls (which could be expensive when using custom streams, as it is in our case, but that's beside the point), one for each possible white space character. 

Granted there is a specialization for SSE2/SSE4.2, but the generic implementation could be optimized as well, i.e. read once, and then compare the result to each whitespace character, unless I'm missing some detail?

We've just overriden the method as a work-around, but the base case within the library could be fixed as well.

**Comment by miloyip** [comment]
Although I think it is easy to implement `Peek()` fast in any input stream, I have modified the function as requested.
