### ISSUE TITLE
rapidjson::Document pass by reference

### ISSUE THREAD

**Issue by nilanc** [miloyip/rapidjson#596]
I have following function,

~~~cpp
int32_t RapidJsonEnDec::GetApiId(rapidjson::Document& doc) {
  rapidjson::Value::ConstMemberIterator itr = doc.FindMember("api"); 
  if(itr != doc.MemberEnd()) {
	  return itr->value.GetInt();
  }
  return -1;
}
~~~

And in another function I have following code segment,

~~~cpp
//////////////////////
//parse data in to a RapidJSON document
  rapidjson::Document jdoc;
  char jbuff[size+1];
  std::strncpy(jbuff, static_cast<const char*>(data), size);

  if(jdoc.Parse(jbuff).HasParseError()) {
    return blf::ReturnCode::kBadInput;
  }

  //Retrieve API id
  int32_t ApiId = GetApiId(jdoc);     ****<- Error
///////////////////////////
~~~

In the above marked Errorline (GetApiId(jdoc);), It produces Invalid argument error.
Can anyone see something wrong there.

Error message ;

~~~
Invalid arguments '
Candidates are:
int GetApiId(rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &)
~~~

**Comment by miloyip** [comment]
The listed code should not have problem.

I suspected that the parsing part is in a const member function, and then `GetApiId()` is a non-const member function.

Please show more code, or even better, a minimal reproduction case.

P.S. you don't need to copy the source JSON into a local buffer for normal parsing. It is only needed when using *is situ* parsing.

**Comment by nilanc** [comment]
Thanks Milo, yes your suspicion was correct, the calling function is a const one and  GetApiId() is not a const. That was the real problem. But my Eclipse was anyhow giving me that stupid error. Might be due to some other errors. 

Now it compiled without a problem, and Now I know that I can pass Document types by reference.
That is what I really wanted to do.

**Comment by miloyip** [comment]
Oh, I see for the array issue now. Actually there is a slower `MemoryStream` which can handle non-null input, which you may want to try.
