### ISSUE TITLE
How do you deal with a stream of json objects?

### ISSUE THREAD

**Issue by FaizShah** [miloyip/rapidjson#597]
Hi, I want to use rapidjson to process a stream of newline delimited json like:

`{"a":"b", "b":"c"}\n{"a":"d", "b":"e"}\n{"a":"f", "b":"g"}\n`

I am doing a filter operation where I want to remove some of the fields and output to stdout. What's the appropriate way of doing this using the DOM api?

Additionally, how would you modify the capitalization example to do deal with this stream?

Thanks.

**Comment by miloyip** [comment]
Basically you need to parse the JSON one by one. To make the parser stops parsing when a JSON is completely parsed, for DOM API, you can use `document.ParseStream<kParseStopWhenDoneFlag>(stream);` to parse a single JSON from the stream. And then continue to parse to stream for next JSON.

capitalization example uses SAX API. For SAX API, you can use `reader.Parse<kParseStopWhenDoneFlag>(stream, handler);` to do similar thing.

**Comment by FaizShah** [comment]
Thanks, it might be useful to add a stream like that to the examples since it's a common format to find json data sets in.

**Comment by miloyip** [comment]
Thank you for your suggestion.
Besides, note that deliminators are not necessary between the JSONs when using `kParseStoWhenDoneFlag`.

**Comment by jmille01** [comment]
I am finding `kParseStopWhenDoneFlag` to mostly fit my needs for parsing a series of JSON messages over TCP.  Since TCP can give me a partial message, I would like a way to detect a failure to parse due to an incomplete message (as in go back and wait for more bytes) vs a malformed message (throw the buffer away, maybe disconnect).  Any suggestions?

**Comment by miloyip** [comment]
There is a `parsebyparts` example.

**Comment by jmille01** [comment]
Thanks, I spent some time looking at the `parsebyparts` example.  I can see that if we can block the stream then we can pull this off.  Shuttling the parsing off to a separate thread isn't always (or in my case is never) an acceptable solution.  It would be super useful we could detect that after calling `ParseStream` the parse operation hit the end of the stream in an incomplete state.

**Comment by jmille01** [comment]
It occurred to me that if `HasParseError()` is true and `stream.Tell()` is equal to the input size then that means parsing got all the way to the end of input before hitting the error, and probably the document is just incomplete.  Looking at the sources of errors, it looks like most JSON format errors would occur prior to the end of the stream.  Does that seem like a reasonable approach?

**Comment by miloyip** [comment]
I can not confirm that will be alright for all cases. It cannot distinguish whether the JSON is invalid or   the JSON is incomplete. Sometimes, a partial JSON can be valid. For example, `3.14` is a valid JSON (a number at root with value 3.14), but it is actually a partial JSON, and the complete one is `3.1416`.
I think you need some protocols to make the JSON complete before parsing, e.g. adding a length before it, or using some kind of EOF symbol.
