### ISSUE TITLE
I do not know if this is a Bug, description...

### ISSUE THREAD

**Issue by myhlj** [miloyip/rapidjson#599]
like this:
void mychangevalue(Value& obj,Document& doc)
{
        string str="my";
	obj.AddMember("lj",StringRef(str.c_str()),doc.GetAllocator());
}

Docment doc;
Value liudehua(kObjectType);
mychangevalue(liudehua,doc);

but
std::cout<<liudehua["lj"].GetString()<<endl;
is wrong!

**Comment by MaxDZ8** [comment]
As far as I recall, using `StringRef` will tell rapidjson _keep a direct reference to this memory blob, I will take care of letting it exist as long as the referring object exists_.

This is not what happens; after your function returns your string is destroyed so the internal rapidjson pointer goes to garbage.

Try `StringRef("my")` instead or perhaps just giving in the string literal. String literals are constant existing as long as the program runs, whereas your `string` object is creating a new, temporary memory blob.

Go to `StringRef` definition (super easy for any decent ide). You will read:

> Mark a plain character pointer as a "string literal".  This function
    can be used to avoid copying a character string to be referenced as a
    value in a JSON GenericValue object, if the string's lifetime is known
    to be valid long enough.

**Comment by myhlj** [comment]
Thank you for your answer.I have learned
