### ISSUE TITLE
Object's member access is O(n)

### ISSUE THREAD

**Issue by miloyip** [miloyip/rapidjson#6]
_From [milo...@gmail.com](https://code.google.com/u/112820317621364945160/) on November 30, 2011 13:31:34_

Object member access, i.e. Value::FindMember(), is in O(n) by linear searching.

Design a faster approach for member access.

_Original issue: http://code.google.com/p/rapidjson/issues/detail?id=5_

**Comment by lukeworthtkbt** [comment]
I am comparing two JSON objects, each with ~180,000 elements and `operator==` is really slow because of this. Just my 2¢.
