### ISSUE TITLE
rapidjson crashes in cocos2d-x 3.x Android release build

### ISSUE THREAD

**Issue by vkreal** [miloyip/rapidjson#601]
rapidjson crashing in Android cocos2d-x 3.x release build. Below code works fine for stock Android but crashes for Kindle Fire. Anyone have any ideas how to fix?

Odd thing it works fine in debug build.

typedef rapidjson::GenericDocument<rapidjson::UTF8<>,rapidjson::CrtAllocator> RapidJsonDocuType;
//rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::CrtAllocator> doc(&crtAllocator);
typedef rapidjson::GenericValue<rapidjson::UTF8<>,rapidjson::CrtAllocator> RapidJsonValue;

**Comment by vkreal** [comment]
sorry it was something else causing issue.

**Comment by ermanhaskan** [comment]
I am experiencing the same problem. What was causing the issue?

**Comment by vkreal** [comment]
Doing below fixed the issue for me.

```
//rapidjson::CrtAllocator crtAllocator;
typedef rapidjson::GenericDocument<rapidjson::UTF8<>,rapidjson::CrtAllocator> RapidJsonDocuType;
//rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::CrtAllocator> doc(&crtAllocator);
typedef rapidjson::GenericValue<rapidjson::UTF8<>,rapidjson::CrtAllocator> RapidJsonValue;

```

**Comment by ermanhaskan** [comment]
Thanks man !  :)
