### ISSUE TITLE
MSVC 14 Warning C4244

### ISSUE THREAD

**Issue by dkuegler** [miloyip/rapidjson#611]
This should happen every time rapidjson is compiled with MSVC 14 2015

2>c:\programs\rapidjson\include\rapidjson\reader.h(889): warning C4244: '=': conversion from 'uint64_t' to 'double', possible loss of data
[...]
2>c:\programs\rapidjson\include\rapidjson\reader.h(900): warning C4244: '=': conversion from 'uint64_t' to 'double', possible loss of data
2>c:\programs\rapidjson\include\rapidjson\reader.h(971): warning C4244: '=': conversion from 'uint64_t' to 'double', possible loss of data

Additionally

2>  c:\programs\rapidjson\include\rapidjson\reader.h(1054): note: see reference to function template instantiation 'void rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::ParseNumber<0,InputStream,Handler>(InputStream &,Handler &)' being compiled
2>          with
2>          [
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>,
2>              Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
2>          ]
2>  c:\programs\rapidjson\include\rapidjson\reader.h(1054): note: see reference to function template instantiation 'void rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::ParseNumber<0,InputStream,Handler>(InputStream &,Handler &)' being compiled
2>          with
2>          [
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>,
2>              Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
2>          ]
2>  c:\programs\rapidjson\include\rapidjson\reader.h(416): note: see reference to function template instantiation 'void rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::ParseValue<0,InputStream,Handler>(InputStream &,Handler &)' being compiled
2>          with
2>          [
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>,
2>              Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
2>          ]
2>  c:\programs\rapidjson\include\rapidjson\reader.h(416): note: see reference to function template instantiation 'void rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::ParseValue<0,InputStream,Handler>(InputStream &,Handler &)' being compiled
2>          with
2>          [
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>,
2>              Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
2>          ]
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1887): note: see reference to function template instantiation 'rapidjson::ParseResult rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::Parse<0,InputStream,rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>>(InputStream &,Handler &)' being compiled
2>          with
2>          [
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>,
2>              Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
2>          ]
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1887): note: see reference to function template instantiation 'rapidjson::ParseResult rapidjson::GenericReader<rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator>::Parse<0,InputStream,rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>>(InputStream &,Handler &)' being compiled
2>          with
2>          [
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>,
2>              Handler=rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>
2>          ]
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1952): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<0,SourceEncoding,rapidjson::GenericStringStream<rapidjson::UTF8<char>>>(InputStream &)' being compiled
2>          with
2>          [
2>              SourceEncoding=rapidjson::UTF8<char>,
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>
2>          ]
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1952): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::ParseStream<0,SourceEncoding,rapidjson::GenericStringStream<rapidjson::UTF8<char>>>(InputStream &)' being compiled
2>          with
2>          [
2>              SourceEncoding=rapidjson::UTF8<char>,
2>              InputStream=rapidjson::GenericStringStream<rapidjson::UTF8<char>>
2>          ]
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1961): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::Parse<0,Encoding>(const char *)' being compiled
2>          with
2>          [
2>              Encoding=rapidjson::UTF8<char>
2>          ]
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1961): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::Parse<0,Encoding>(const char *)' being compiled
2>          with
2>          [
2>              Encoding=rapidjson::UTF8<char>
2>          ]
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1968): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::Parse<0>(const char *)' being compiled
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1968): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::Parse<0>(const char *)' being compiled
2>  C:\Programs\RapidJSON\include\rapidjson\document.h(1967): note: while compiling class template member function 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::Parse(const char *)'

2>  G:\gitdev\lib\mukno\json\Document.cpp(70): note: see reference to function template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>::Parse(const char *)' being compiled

2>  g:\gitdev\lib\mukno\json\Document.h(32): note: see reference to class template instantiation 'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>,rapidjson::CrtAllocator>' being compiled

So cDocument is a derivative of rapidjson::Document:
G:\gitdev\lib\mukno\json\Document.h(32)
		class cDocument : public rapidjson::Document, public cHasLogger {

G:\gitdev\lib\mukno\json\Document.cpp(70) (in cDocument-Member-function)
	else if (Parse(strJSONData.c_str()).HasParseError() && hasLogger())

**Comment by miloyip** [comment]
It seems that you are using an older version. 
The master branch should have no VC warning, as in https://ci.appveyor.com/project/miloyip/rapidjson .
