### ISSUE TITLE
assert(message.IsObject()); fails while it shouldn't 

### ISSUE THREAD

**Issue by ikbenlike** [miloyip/rapidjson#620]
this is my code:

~~~cpp
#include "rapidjson/document.h"
#include <stdio.h>
#include <iostream>

int main() {

    const char* json =
    "{"
        "\"hello\": \"world\","
        "\"t\": \"world\""
    "}";

    const char* msgJson =
    "{"
        "\"d\": {"
            "\"attachments\": ["
                "{"
                    "\"filename\": \"afile\""
                    "\"id\": \"somemoreid\""
                    "\"proxy_url\": \"qvw.xyz\""
                    "\"size\": 5"
                    "\"url\": \"abc.def\""
                "}"
            "]"
            "\"author\": {"
                "\"avatar\": \"some_string\""
                "\"discriminator\": \"#1234\""
                "\"id\": \"someid\""
                "\"username\": \"watcher\""
            "}"
            "\"channel_id\": \"chanid\""
            "\"content\": \"this was parced with c++\""
            "\"edited_timestamp\": null"
            "\"embeds\": []"
            "\"id\": \"123abc\""
            "\"mention_everyone\": false"
            "\"mentions\": ["
                "{"
                    "\"avatar\": \"somefile\""
                    "\"discriminator\": \"#0001\""
                    "\"id\": \"123\""
                    "\"username\": \"James\""
                "}"
            "]"
            "\"timestamp\": \"now\""
            "\"tts\": false"
        "}"
        "\"op\": 0"
        "\"s\": 0"
        "\"t\": \"MESSAGE_CREATE\""
    "}";

    rapidjson::Document document;
    document.Parse(json);
    assert(document.IsObject());
    assert(document.HasMember("hello"));
    assert(document["hello"].IsString());
    printf("hello = %s\n", document["hello"].GetString());
    assert(document.HasMember("t"));
    assert(document["t"].IsString());
    printf("t = %s\n", document["t"].GetString());

    rapidjson::Document message;
    rapidjson::ParseResult result = message.Parse(msgJson);
    std::cout << result << std::endl;
    assert(message.IsObject());
    assert(message.HasMember("t"));
    printf("%s\n", message["t"].GetString());
}
~~~

the first part with document works fine, but `assert(message.IsObject());` fails. What am I doing wrong?

**Comment by miloyip** [comment]
That is not a valid JSON as parsing it with my naked eyes.
There is no comma to separate each values!
And result should returns `false`, you can get the error code and offset for the exact problem.

**Comment by ikbenlike** [comment]
how did I not see that -_-
thanks, I'll try if it works now

**Comment by ikbenlike** [comment]
I corrected the JSON but it's still not working. This is my code now:
`
#include "rapidjson/document.h"
#include <stdio.h>
#include <iostream>

int main() {

    const char* json =
    "{"
        "\"hello\": \"world\","
        "\"t\": \"world\""
    "}";

    const char* msgJson =
    "{"
        "\"t\": 'MESSAGE_CREATE',"
        "\"s\": 59,"
        "\"op\": 0,"
        "\"d\":{"
            "\"tts\": false,"
            "\"timestamp\": '2016-04-29T02:40:47.490000+00:00',"
            "\"nonce\": '175436196699176960',"
            "\"mentions\": [ [Object] ],"
            "\"mention_everyone\": false,"
            "\"id\": '175436191456428032',"
            "\"embeds\": [],"
            "\"edited_timestamp\": null,"
            "\"content\": '<@174463430873317376> count stuff',"
            "\"channel_id\": '81402706320699392',"
            "\"author\': {"
                "\"username\": '#C2185B #AD1457 #880E4F',"
                "\"id\": '125422419736395777',"
                "\"discriminator\": '0672',"
                "\"avatar\": '57ca1bf97372796648a2aac4b20614af'"
            "},"
            "\"attachments\": []"
        "}"
    "}";

    rapidjson::Document document;
    document.Parse(json);
    assert(document.IsObject());
    assert(document.HasMember("hello"));
    assert(document["hello"].IsString());
    printf("hello = %s\n", document["hello"].GetString());
    assert(document.HasMember("t"));
    assert(document["t"].IsString());
    printf("t = %s\n", document["t"].GetString());

    rapidjson::Document message;
    rapidjson::ParseResult result = message.Parse(msgJson);
    std::cout << result << std::endl;
    assert(message.IsObject());
    assert(message.HasMember("t"));
    printf("%s\n", message["t"].GetString());

    return 0;
}
`

**Comment by miloyip** [comment]
You should check the error code...
The JSON uses single quotes `'` in some strings, which is not a valid JSON.

**Comment by ikbenlike** [comment]
okay. How would one print the error code? Because that'd probably help me in the future

**Comment by miloyip** [comment]
http://rapidjson.org/md_doc_dom.html#ParseError

**Comment by ikbenlike** [comment]
but that says 
`
json_example.cpp: In function ‘int main()’:
json_example.cpp:52:62: error: ‘GetParseError_En’ is not a member of ‘rapidjson’
     printf("%u - %s\n", (unsigned)document.GetErrorOffset(), rapidjson::GetParseError_En(document.GetParseErrorCode()));
                                                              ^
json_example.cpp:52:99: error: ‘rapidjson::Document’ has no member named ‘GetParseErrorCode’
     printf("%u - %s\n", (unsigned)document.GetErrorOffset(), rapidjson::GetParseError_En(document.GetParseErrorCode()));
`

this is my code:
`
printf("%u - %s\n", (unsigned)message.GetErrorOffset(), rapidjson::GetParseError_En(message.GetParseErrorCode()));
`

**Comment by ikbenlike** [comment]
changed my code to this:
`
printf("%u - %s\n", (unsigned)message.GetErrorOffset(), rapidjson::GetParseError_En(message.GetParseErrorCode()));`

now I only get this:
`
json_example.cpp: In function ‘int main()’:
json_example.cpp:53:97: error: ‘rapidjson::Document’ has no member named ‘GetParseErrorCode’
     printf("%u - %s\n", (unsigned)message.GetErrorOffset(), rapidjson::GetParseError_En(message.GetParseErrorCode()));
`

**Comment by miloyip** [comment]
From the link, you can see that
~~~
#include "rapidjson/document.h"
#include "rapidjson/error/en.h"
// ...
Document d;
if (d.Parse(json).HasParseError()) {
    fprintf(stderr, "\nError(offset %u): %s\n", 
        (unsigned)d.GetErrorOffset(),
        GetParseError_En(d.GetParseErrorCode()));
    // ...
}
~~~

You need to include that `error/en.h` for `GetParseError_En()`.

**Comment by ikbenlike** [comment]
but I already include that

**Comment by ikbenlike** [comment]
the only error that the compiler gives me is:
`
json_example.cpp: In function ‘int main()’:
json_example.cpp:53:97: error: ‘rapidjson::Document’ has no member named ‘GetParseErrorCode’
     printf("%u - %s\n", (unsigned)message.GetErrorOffset(), rapidjson::GetParseError_En(message.GetParseErrorCode()));
`

**Comment by miloyip** [comment]
Oh... the document was wrong, should be `GetParseError()`

**Comment by ikbenlike** [comment]
thanks! it compiles now, but it still doesn't get past the JSON...

**Comment by ikbenlike** [comment]
I figured out at what part of the JSON it breaks: the `[ [ Object ] ]` value of `mentions`

**Comment by miloyip** [comment]
`[ [ Object ] ]` is not a valid JSON value. 
`[ [ "Object" ] ]` is valid.

**Comment by ikbenlike** [comment]
yeah I just figured that out. Everything is working fine now, thanks for your help!
