### ISSUE TITLE
Writer producing invalid output

### ISSUE THREAD

**Issue by AO-StreetArt** [miloyip/rapidjson#621]
I have an example of the writer producing unreadable output, following almost exactly the SimpleWriter example.

Have posted the code in question to [stackoverflow] (http://stackoverflow.com/questions/36958028/c-rapidjson-writer-and-string-buffer-outputting-unknown-characters)

**Comment by AO-StreetArt** [comment]
Found to be a result of passing output of StringBuffer::GetString() via const char* rather than std::string.  Perhaps an example of a to_json() method within a class of private variables would be helpful?

**Comment by miloyip** [comment]
It seems that your problem has been solved.
