### ISSUE TITLE
Parsing large Json File

### ISSUE THREAD

**Issue by newterminator** [miloyip/rapidjson#624]
Hi,
I am a newbie to C++, having recently learnt it. I tried RapidJSON with smaller json files (< 1MB) and it works as described in the [tutorial](http://rapidjson.org/md_doc_tutorial.html). 

I also followed the guide online to parse a large json file (1.1 GB): 
```
#include "rapidjson/filereadstream.h"
#include <cstdio>
using namespace rapidjson;

FILE* fp = fopen("myfile.json", "r"); 
char readBuffer[65536];
FileReadStream is(fp, readBuffer, sizeof(readBuffer));

Document d;
d.ParseStream(is);
assert(d.IsObject()); 
fclose(fp);
```
I get the error `Assertion 'document.IsObject()' failed`. Could you tell me what might be causing this error?

**Comment by newterminator** [comment]
Well after doing more searching around, I found this [issue](https://github.com/miloyip/rapidjson/issues/578), which pointed out to check the format of the json. 
This is how the json is:
```
{
  "productID": "3GASNN3B",
  "pnumber": "2014",
  "purchaser": "Jerry S",
  "comment": "If you combine both medium and large deals then you get both for $13.98 wowowow. Jump on this quick.  Great purchase though!",
  "time": "05 16, 2013"
}
```
So I checked with `document.IsArray()` and that also failed, but `document.IsNull()` came to be true.

**Comment by miloyip** [comment]
The JSON may contain invalid format. You may firstly check if it returns error code, as in [here](http://rapidjson.org/md_doc_dom.html#ParseError).

**Comment by newterminator** [comment]
Hey @miloyip , Thanks for replying quickly (and btw huge thanks for creating such a fast JSON parser library). 

So I checked out the page you linked and followed the sample and got the following `Error(offset 339): The document root must not be followed by other values.`. 

So yeah you were right about the JSON being invalid format, is there something to fix it ...

**Comment by miloyip** [comment]
I think the file may contains multiple JSONs. If that is the case, you can use `kParseStopWhenDoneFlag` as shown [here](http://rapidjson.org/md_doc_dom.html#Parsing). It will stop when a complete JSON is parsed. Then you can parse another JSON using the same input stream.

If the file is supposed to have only one JSON but `kParseErrorDocumentRootNotSingular` happens, then you should fix the file instead.

**Comment by newterminator** [comment]
Hey @miloyip , I went to sleep after my last comment. Woke up to see your reply and instantly tried out your suggestion, and hurray hurray using the `kParseStopWhenDoneFlag` worked. 

What a good start to the day. Thanks so much!

An another question: I tried to parse another large json file and this time while testing for error, I got `Error(offset 1): Missing a name for object member.` 

How could I resolve this ...

**Comment by miloyip** [comment]
Single quoted string `'productID'` is not valid in JSON standard.
It is currently not supported by RapidJSON, but has been noted in #36 .

**Comment by newterminator** [comment]
Hey @miloyip , Thanks for referencing the planned enhancement, so I can see what other syntax can cause issues. 

Well in any case you solved the initial issue I had with ease, so I will close this issue. 

Just a quick question: Does RapidJSON use multiple cores of a machine...If yes, is there a way to activate it?

**Comment by miloyip** [comment]
> Just a quick question: Does RapidJSON use multiple cores of a machine...If yes, is there a way to activate it?

No. But RapidJSON is carefully developed as reentrant. You can parses JSONs in different threads.

**Comment by newterminator** [comment]
Ok, thanks for the quick response. Have a good day @miloyip !

**Comment by michcleary** [comment]
I see that ParseStream with the kParseStopWhenDoneFlag has another thin,g InputStream, in the <>.  What needs to be provided for that?  I just want to do doc.ParseStream<rapidjson::kParseStopWhenDoneFlag>(json);  Do I need that InputStream in the syntax in <>? I can't find any examples where someone is actually using it.

**Comment by miloyip** [comment]
Yes. You need. Please check [the overloads](http://rapidjson.org/md_doc_dom.html#Parsing).
And there are [a few examples](http://rapidjson.org/md_doc_stream.html).
