### ISSUE TITLE
xlib Bool 

### ISSUE THREAD

**Issue by gzjiangying** [miloyip/rapidjson#628]
X11
#define Bool int 
reader.h
bool Bool(bool) { return static_cast<Override&>(*this).Default(); }
Define conflict(定义冲突);
Bool change Bool_(里面所有的Bool改为Bool_即可);
[Uploading file.zip…]()

**Comment by miloyip** [comment]
I think this cannot be resolved in a good way, if other library defined conflicted name macro.
A workaround is to include rapidjson before those includes. Or #undef Bool before including RapidJSON.

**Comment by gzjiangying** [comment]
ok,You are right,but in x11 with this problem.
