### ISSUE TITLE
Comparing values in large multiple json files

### ISSUE THREAD

**Issue by newterminator** [miloyip/rapidjson#638]
Moving on from the last [issue](https://github.com/miloyip/rapidjson/issues/624) (resolved with Milo Yip's help) I faced, I am now trying to do this:
```c++
Document data;
int matchCounter = 0;
Document matchArray[] = {};
while (!data.ParseStream<kParseStopWhenDoneFlag>(dataStream).HasParseError()) {
   Document product;
   while (!product.ParseStream<kParseStopWhenDoneFlag>(productStream).HasParseError()) {
       if (data["id"] == product["id"]) {
           matchArray[matchCounter] = data;
           matchCounter++;
       }
    }
 }
```
I have got about 5 Million "data" multiple json documents and 2 million "product" multiple json documents.

First issue is that the if statement only compares the first "data" document with all the 2 million "product" documents.

Second, the line `matchArray[matchCounter] = data` produces an error as well. Even if I try to add the matched "data" to a vector like so: `matchVector.push_back(data)` it doesn't work.

**Comment by miloyip** [comment]
First, if you need to load all the data and then process them, you need to create some data structures to store them in memory and access them efficiently. For example, here you need to do a "inner join" between the "tables". You should first create the table with "indexing". For example, using `std::map<int, Document *>` (or `shared_ptr<Document>` in C++11) to store both tables.

Second, Document does not permit assignment. You can use `d1.Swap(d2)` or doing a deep clone with `d1.CopyFrom(d2, d1.GetAllocator())`. But I think you should `new` a `Document` here for storing it in container.

In addition, I am not sure what is the purpose of your application. If memory is an issue, I think you may consider converting JSON into your own data structure, or even better, use some database solutions to do the processing instead.

**Comment by newterminator** [comment]
Hi @miloyip , Thank you so much for replying. I am going to use your guidance in the json processing. I am going to work out your guidance in detail and reopen the issue if I need further help. Thank you once again. I really appreciate it!
