### ISSUE TITLE
null-allocator when building rapidjson for armv-7

### ISSUE THREAD

**Issue by pglushkov** [miloyip/rapidjson#640]
Hello, rapidjson team!

Found a very strange compiler-specific bug when working with rapidjson. Issue is that when building lib rapidjson with a special compiler and a special set of flags, allocator_, that is created in constructor of GenericDocument class becomes NULL ! As if an optimizer had cut-out its initialization for some reason. If building just the same code, but adding an extra-line to GenericConstructor, like:

```
GenericDocument(Allocator* allocator = 0, size_t stackCapacity = kDefaultStackCapacity, StackAllocator* stackAllocator = 0) : 
    allocator_(allocator), ownAllocator_(0), stack_(stackAllocator, stackCapacity), parseResult_()
    {
        if (!allocator_)
            ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator());

        // FIGHTING WITH COMPILER OPTIMIZATION !!!
        printf(" In GenericDocument::Ctor () 2 , allocator = 0x%p \n", allocator_);
    }
```
then everything works just fine and allocator_ is not NULL.

More details are as follows:

rapidjson version : 1.0.2

compiler used : arm-linux-androideabi-g++ (GCC) 4.9.x-google 20140827 (prerelease)

compiler flags :  -c  -fno-exceptions -Wno-multichar -msoft-float -ffunction-sections -fdata-sections -funwind-tables -fstack-protector -Wa,--noexecstack -Werror=format-security    -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -fno-canonical-system-headers -mcpu=cortex-a7 -D__ARM_FEATURE_LPAE=1 -mfloat-abi=softfp -mfpu=neon  -include build/core/combo/include/arch/linux-arm/AndroidConfig.h -I build/core/combo/include/arch/linux-arm/ -fno-builtin-sin -fno-strict-volatile-bitfields -Wno-psabi -mthumb-interwork -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -DNDEBUG -g -Wstrict-aliasing=2 -fgcse-after-reload -frerun-cse-after-loop -frename-registers -DNDEBUG -UDEBUG   -fvisibility-inlines-hidden   -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wsign-promo -std=gnu++11 -Werror=return-type -Werror=non-virtual-dtor -Werror=address   -Werror=sequence-point -DNDEBUG -UDEBUG -mthumb -Os -fomit-frame-pointer -fno-strict-aliasing  -fno-rtti -DAES_DSO=1 -DAES_DSO_EXPORTS=1 -fPIC -D_USING_LIBCXX   -DAES_DSO=1 -DAES_DSO_EXPORTS=1  -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast

What additional information can I provide to help to reproduce or fix the issue?

**Comment by miloyip** [comment]
It seems a problem that have been reported sometimes ago.
Can you check if the compiler really removed the code incorrectly?
If it is really a compiler issue, I think it is needed to report to the compiler team.
There may be possible to do some workaround but it needs experimentation. For example, if the optimizer incorrectly think `(!allocator)` is always false, then it may be possible to do `volatile Allocator* temp = allocator;` and then use `(!temp)` instead to prevent such optimization.

**Comment by pglushkov** [comment]
Unfortunately I'm not familiar with the ARM assembler, so I cannot claim for sure how compiler transformed the code. My judgement comes from indirect evidences. I can run a few more thorough tests and try to narrow down the exact combination of the flags that created the problem, if that will be of any help. What other assistance can I provide?

If this issue was found before, maybe it would be proficient the create some sort of 'known issues' section in the documentation and put there this and other known issues there?

**Comment by miloyip** [comment]
I am not sure if it is related to #388 .
If you can create a simple reproduction case (independent to RapidJSON), it will be easier to submit help to the compiler teams.

**Comment by pglushkov** [comment]
Ok then. I suppose we can close the issue for now. I will go one and try to write a few tests for the compiler developers, may that would be of any help :)

**Comment by miloyip** [comment]
I am not sure if this uses the same configuration as #758, but you may try if that workaround works.
