### ISSUE TITLE
as_array and as_object

### ISSUE THREAD

**Issue by capsocrates** [miloyip/rapidjson#642]
It would be nice if there were some helper utilities to make `rapidjson::GenericValue`s get along nicely with range-based for and other range-based interfaces. Obviously you can't just pass the `Value` as-is, because it's ambiguous whether it's an array or an object. With a helper function, you could do

`for(rapidjson::GenericValue& val : as_array(my_JSON_array)) { /* operate on the array values */ }`
or
`for(rapidjson::GenericMember& member : as_object(my_JSON_object)) { /* operate on the JSON members */ }`

It wouldn't be many lines of code; a struct that holds a pointer to the `rapidjson::GenericValue` and has `begin`, `cbegin`, `end`, and `cend` functions and some aliases for the various types (like a standard library container or the other `rapidjson` types).

`as_const_array` and `as_const_object` would also be handy.

**Comment by miloyip** [comment]
When `RAPIDJSON_HAS_CXX11_RANGE_FOR` is defined, you can code as follows.

~~~
Value& o = ...
for (auto& m : o.GetObject()) {
    Value& name = m.name;
    Value& value = m.value;
}

Value& a = ...
for (Value& v = a.GetArray()) {
    
}
~~~

**Comment by capsocrates** [comment]
Oh cool, I did not know that's what those functions did.
