### ISSUE TITLE
Not giving error for invalid JSON

### ISSUE THREAD

**Issue by DiptiGupta** [miloyip/rapidjson#643]
Hi 

I am parsing an invalid JSON file using rapidJson parser whose structure is as follow
----- Json file start----
{
"name" : "mohan",
"address" : "noida"
},
{
"name" : "rohan",
"address" : "noida"
}
----- json file end-----

This file is invalid because array brackets are missing in this. But during parsing of this file, parser is treating this json file as a array.

**Comment by miloyip** [comment]
This seems strange. Can you show your code?

**Comment by DiptiGupta** [comment]
Sorry. It was my mistake. It is not treating parsing as an array.
I dint get any result for invalid JSON. It should give parse error. 
If there is any way to get parsing error without schema validation, please suggest me as i am using it first time.

**Comment by miloyip** [comment]
If it is an invalid JSON, the parser can report accordingly.
Please refer to:

http://rapidjson.org/md_doc_dom.html#ParseError

**Comment by DiptiGupta** [comment]
Thank you for providing the information. I am closing the issue.
