### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by thedrow** [miloyip/rapidjson#648]
There are a lot of improvements and bug fixes in master.
Maybe it's time for a new release?

**Comment by miloyip** [comment]
There was some issues related the JSON schema which blocks the progress of release...
To make it going, I think maybe I should just make a release and make that feature continue to be experimental.

**Comment by thedrow** [comment]
People who don't need JSON schemas can still benefit from the improvements in the JSON parser itself. I agree.

**Comment by paresy** [comment]
+1

**Comment by barboteur** [comment]
Hello. I also need a release to fix the bug when parsing an empty object. Thank you.

**Comment by kkaefer** [comment]
Release would be cool; master currently has [723 commits](https://github.com/miloyip/rapidjson/compare/v1.0.2...master) that aren't in the most recent 1.0.2 release.

**Comment by vasyan1337h4x0r** [comment]
@miloyip So what's the plan? Are we going to see a new release in the near future?

**Comment by 2underscores-vic** [comment]
Waiting for the release more than one year...

**Comment by mscdex** [comment]
+1 Do you have a timeline for a new release, @miloyip ? I think JSON Schema support should not hold up the improvements made in other parts of the library.

**Comment by kkaefer** [comment]
🎉

**Comment by mscdex** [comment]
Thank you! :-)
