### ISSUE TITLE
RapidJSON unable to access values using GetInt() or GetUint() -> Value results in 0

### ISSUE THREAD

**Issue by kchenh** [miloyip/rapidjson#652]
Hi there, I have been trying to implement RapidJSON and found some strange behaviour. 

I am reading members of an object containing various types (arrays, numbers, strings, etc) using the iterator method found in the tutorial. A snippet of my code is as follows:

```
 for (Value::ConstMemberIterator itr = Object.MemberBegin(); itr != Object.MemberEnd(); ++itr)
 {
 		const char* getstring = itr->name.GetString();
 		string name = getstring;
 		getstring = kTypeNames[itr->value.GetType()];
 		string type = getstring;
 
 		cout << "Type of \"" << name << "\" is \"" << type << "\": ";
 		const Value& subObject = Object[name.c_str()];

        // some if else code before this on "type" variable, for handling array, objects, strings, null, true false
 		else if (type == "Number") 
 		{
 			if (subObject.IsInt())
 			{
 				cout << "(Int) Value: " << subObject.GetInt() << endl;
 			} 
 			else if (subObject.IsUint())
 			{
 				cout << "(Uint) Value: " << subObject.GetUint() << endl;
 			} 
            // if else code to handle the other number formats, UInt64, Int64, Double, Float 
 		}
 }
```

Using the tutorial JSON as an example of an input,

 
```
{
    "hello": "world",
    "t": true ,
    "f": false,
    "n": null,
    "i": 123,
    "pi": 3.1416,
    "a": [1, 2, 3, 4]
}
```

The "pi" prints fine as a double. However, for "i" , even though "subObject.IsInt()" returns true,  subObject.GetInt() returns 0. 

I've done a couple of other tests and found that this also occurs for subObject.GetUint(). The strange thing is that if I change the GetInt() to GetInt64():

```
if (subObject.IsInt())
{
     cout << "(Int) Value: " << subObject.GetInt64() << endl;
} 
else if (subObject.IsUint())
{
     cout << "(Uint) Value: " << subObject.GetUint64() << endl;
}
```

Then the integer values print correctly, ie. "i" prints 123

Help on this would be much appreciated.

**Comment by pah** [comment]
On which platform are you running the tests?
Did you check, that [`RAPIDJSON_ENDIAN`][1] is correctly detected?

[1]: http://rapidjson.org/group___r_a_p_i_d_j_s_o_n___c_o_n_f_i_g.html#gaba2445f582142cf918e74c2d22d1aa07

**Comment by kchenh** [comment]
Thanks pah! problem solved.

I was initially using gcc 4.2.0 and the compiler complained that RAPIDJSON_ENDIAN was not defined, so I #defined it to big endian. I later moved the code to VS 2015 and forgot to remove that line. It works as expected now, when letting the compiler automatically detect endianness. 

Thanks once again, that was of great help
