### ISSUE TITLE
issue in new version about swap

### ISSUE THREAD

**Issue by ahju** [miloyip/rapidjson#657]
hi all,

the code

`rapidjson::Document addoc;`
`addoc.Parse<0>(global_def_adjson.c_str());`
`rapidjson::Document::AllocatorType &adposallocator=addoc.GetAllocator();`
`rapidjson::Document mdoc;`
`mdoc.Parse<0>(material_info.c_str());`
`rapidjson::Document::AllocatorType &mallocator=mdoc.GetAllocator();`

`rapidjson::Value custom(rapidjson::kObjectType);`
`mdoc.Swap(custom);`
`rapidjson::Value custom1(rapidjson::kObjectType);`
`custom1.CopyFrom(custom, adposallocator);`
		   		
`addoc.AddMember("custom", custom1, adposallocator);`

worked well when I used the old version of rapidjson, but it was wrong when I update rapidjson to new version, and the error is:

`jobs.cpp:1193:24: error: no matching function for call to 'rapidjson::GenericDocument<rapidjson::UTF8<> >::Swap(rapidjson::Value&)'
        mdoc.Swap(custom);
                        ^
`
`jobs.cpp:1193:24: note: candidate is:
In file included from jobs.cpp:5:0:
/usr/local/include/rapidjson/document.h:1854:22: note: rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Swap(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]
     GenericDocument& Swap(GenericDocument& rhs) RAPIDJSON_NOEXCEPT {
                      ^`
`
does anyone knows how to fix it?

thanks

**Comment by miloyip** [comment]
Using `custom.Swap(mdoc);` should work.

**Comment by ahju** [comment]
Thanks for miloyip kindly reply, it work.  And I Using `mdoc.Value::Swap(custom)`, it work too
