### ISSUE TITLE
parse with length option

### ISSUE THREAD

**Issue by douxing** [miloyip/rapidjson#659]
I think that GenericDocument::Parse should have a version with length option, like:
```C
GenericDocument::Parse(const Ch* str, size_t length)
```

it might be redundant but is very handy with communication data, thus i don't have to reallocate memory for the \0 at the tail after receiving the data.

**Comment by gggin** [comment]
you can use std::string version

**Comment by pah** [comment]
This is available in the current master since the merge of #553, see also #158 for more discussion.

**Comment by miloyip** [comment]
Thanks @pah

**Comment by douxing** [comment]
@pah @miloyip after a git pull, every thing is okay, thank you!
