### ISSUE TITLE
Build error on Fedora 24 with gcc 6.1.1

### ISSUE THREAD

**Issue by ragnar-ouchterlony** [miloyip/rapidjson#666]
Built using "cmake -DRAPIDJSON_HAS_STDSTRING=ON .. && make".

System is Fedora 24

gcc is 6.1.1.

Build ends with:

/extra/ragnar/source/rapidjson-master/test/unittest/namespacetest.cpp:39:19:   required from here
/extra/ragnar/source/rapidjson-master/include/rapidjson/document.h:755:66: error: throw will always call terminate() [-Werror=terminate]
         RAPIDJSON_ASSERT(this != &rhs);

Full output from cmake and make attached.

[cmake.txt](https://github.com/miloyip/rapidjson/files/327739/cmake.txt)
[build.txt](https://github.com/miloyip/rapidjson/files/327738/build.txt)

**Comment by pah** [comment]
Do you override `RAPIDJSON_ASSERT` with some kind of exception throwing mechanism?
The functions where this warnings are generated from are marked as `RAPIDJSON_NOEXCEPT`, which means that indeed throwing an exception from there will lead to a call to `std::terminate`.

**Comment by ragnar-ouchterlony** [comment]
No. I have not done any conscious overriding at least. I can reproduce it by doing the following steps:

git clone https://github.com/miloyip/rapidjson
cd rapidjson
mkdir build
cd build
cmake -DRAPIDJSON_HAS_STDSTRING=ON ..
make

**Comment by pah** [comment]
I have just added #667 with a proposed fix.

For `document.h`, I decided to keep the offending code, i.e. suppress the warning locally on GCC 6 and later (Clang might need to be added as well at some point).

For `schema.h`, the `RAPIDJSON_NOEXCEPT` annotation has been removed, as the corresponding constructor calls `RAPIDJSON_NEW`, which might indeed throw.

Some tests exposed `-Wdangling-else` warnings, which have been addressed, too.

**Comment by ragnar-ouchterlony** [comment]
Thanks for the fix.

But the change in readertest.cpp exposes another build problem for me. 

[ 68%] Building CXX object test/unittest/CMakeFiles/unittest.dir/readertest.cpp.o
/extra/ragnar/source/rapidjson/test/unittest/readertest.cpp:32:1: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
 RAPIDJSON_DIAG_OFF(dangling-else)
 ^~~~~~~~~

And I am a bit confused about that flag, since my gcc (from Fedora 24) does not seem to have any "-Wdangling-else" as seen by "gcc --help=warnings". I can also not find any reference to it in the online gcc documentation: https://gcc.gnu.org/onlinedocs/gcc-6.1.0/gcc/Option-Summary.html

$ gcc --version
gcc (GCC) 6.1.1 20160621 (Red Hat 6.1.1-3)

**Comment by pah** [comment]
Ok, it seems that the `-Wdangling-else` warnings showed up on a GCC 7.x development version.  For now, it should be safe to drop the corresponding suppression in `readertest.cpp`.

**Comment by ragnar-ouchterlony** [comment]
Ah, I suspected as much, but did not find it easily.

**Comment by pah** [comment]
I've raised the GCC version to suppress the warning in readertest.cpp to 7.x or later, see #669.

**Comment by ragnar-ouchterlony** [comment]
Great! Now I was able to build without problems.

**Comment by miloyip** [comment]
Thanks @pah
