### ISSUE TITLE
Cannot reference nested objects efficiently.

### ISSUE THREAD

**Issue by heaths** [miloyip/rapidjson#675]
I have a JSON document with an array of objects. It's easy enough to enumerate the elements in the array, but if I try to get a reference to the current element of the iterator, I get that the necessary constructor is inaccessible using 1.0.2:

```c++
if (doc["resources"].IsArray())
{
  for (auto it = doc["resources"].Begin(); it != doc["resources"].End(); ++it)
  {
    auto elem = *lt; // error: GenericValue copy constructor is inaccessible
  }
}
```

Instead, I have to use numeric iterator against `Size()` and keep using `doc["resources"][i]["name"].GetString()`, which I imagine is requiring a lot of look ups and, thus, slowing down what could be faster.

**Comment by miloyip** [comment]
Before C++11, it should be:

~~~cpp
rapidjson::value& elem = *it;
~~~

Since it is a reference type, you can do this in C++11:

~~~cpp
auto& elem = *it;
~~~

or

~~~cpp
const auto& elem = *it;
~~~

**Comment by miloyip** [comment]
~~~cpp
auto& elem = *it;
// or
const auto& elem = *it;
~~~

**Comment by heaths** [comment]
Thanks. That worked.
