### ISSUE TITLE
Can i just to modify one field in existing json? (no need to rebuild the entire json file)

### ISSUE THREAD

**Issue by nbtthief** [miloyip/rapidjson#677]
Hi, first i'm really sorry to create this topic on this issue section, but i just dont know how to ask you about this problem, if it's inconvenience, pls close it.

I wonder if i can write to json file just one section or one field in existing json file without stringify entire json content. For ex: { "obj1" : 10, "obj2" : 20 <- modify this only }

i've read the documentation and notice about sax writer: "If your application only need to converts some data into JSON, it may be a good choice to use Writer directly, instead of building a Document and then stringifying it with a Writer". But the example cannot show this feature ambigously, i dont find it any difference than just stringify buffer the DOM way.

Can you give me some clearer example?

**Comment by miloyip** [comment]
Sorry, no. Currently you cannot just modifying the JSON directly. You need to parse the whole JSON, modify some values, and the stringify the whole JSON. DOM is the easiest way to do modification. Using SAX is also possible and it can reduce memory and time, yet it is limited by one-pass processing.

**Comment by nbtthief** [comment]
Oh i see, thanks you for your quick replying and this awesome library 👍
