### ISSUE TITLE
Reverse iterators

### ISSUE THREAD

**Issue by nils-ballmann** [miloyip/rapidjson#678]
**std::vector<type>** has next to _.begin()_ and _.end()_ also _.rbegin()_ and _.rend()_ as _::const_iterator_ and _::iterator_.

Wouldn't it be nice to also have (const) reverse iterators in RapidJSON?

Up to now i iterate (const) over values/members, calculate some intermediate results, push them to a std::vector and iterate reversely on that to get it in my final resulting data structure. This is in **O(2n)**. With reverse iterators this would cut down to **O(n)**.

So this is my proposal:
GenericValue<...>**::ReverseMemberIterator**
GenericValue<...>**::ConstReverseMemberIterator**

GenericValue<...>**::MemberRBegin()**
GenericValue<...>**::MemberREnd()**

GenericValue<...>**::ReverseValueIterator**
GenericValue<...>**::ConstReverseValueIterator**

GenericValue<...>**::RBegin()**
GenericValue<...>**::REnd()**

**Comment by dachziegel** [comment]
You can use `std::reverse_iterator` for this, e.g.:

    using Iterator = rapidjson::Value::MemberIterator;
    using ReverseIterator = std::reverse_iterator<Iterator>;

    ReverseIterator rbegin(document.MemberEnd());
    ReverseIterator rend(document.MemberBegin());
    while(rbegin != rend) {... ++rbegin; }
