### ISSUE TITLE
Compilation error on AIX platform - due to rapidjson inclusion

### ISSUE THREAD

**Issue by psbramsiva** [miloyip/rapidjson#685]
I am using rapidjson v1.0.2 on AIX platform for compiling. it gives internal service error once i include rapidjson header files. but the same issue got resolved when i use rapidjson master branch code. 
So can you let me know if there is any fix for the issue checked in on master branch and when will be new version contain master branch changes released.

**Comment by miloyip** [comment]
I think I can hardly figure out which commit fixes that.
I hope a new version would be released very soon.
