### ISSUE TITLE
Wrong double printed

### ISSUE THREAD

**Issue by dtolnay** [miloyip/rapidjson#687]
```cpp
#include "rapidjson/internal/dtoa.h"
#include <iostream>

int main() {
  double d = 4094.1111111111113;
  char buf[24];
  *rapidjson::internal::dtoa(d, buf) = '\0';
  std::cout << buf << std::endl;
}
```

Expected: 4094.1111111111113
Actual: 4094.1111111111115

The exact value represented by `d` is 4094.111111111111313221044838428497314453125. My understanding is grisu2 is always-accurate and usually-shortest, so this seems like a bug in dtoa.h.

**Comment by miloyip** [comment]
As my understanding, Grisu's correctness depends on whether the string representation can be converted back to the original binary representation.

And I tested:

~~~cpp
double d = 4094.1111111111113;
char buf[24];
*rapidjson::internal::dtoa(d, buf) = '\0'; // 4094.1111111111115
double d = std::atof(buf);
printf("%.17g\n", d); // 4094.1111111111113
~~~

**Comment by dtolnay** [comment]
Makes sense, thanks for clarifying.
