### ISSUE TITLE
rapidjson newbie: getting error "function is inaccessible" when using document.FindMember

### ISSUE THREAD

**Issue by TappyApp** [miloyip/rapidjson#693]
Hello world!

My first post on GitHub, happy to join the community.

So....I'm a bit of a newbie. Trying to use rapidjson, with marmalade sdk.

Here's what I'm trying to do:

`// Open json file and create json document
	
        std::ostringstream sstream;
	std::ifstream fs("json/myfile.json");
	sstream << fs.rdbuf();
	const std::string str(sstream.str());
	const char *ptr = str.c_str();
		
        Document document;
	document.Parse<0>(ptr);
	Value::MemberIterator member = document.FindMember("member1");`

First off, when I tried to do document.Parse(ptr), I get the compiler error:

> Severity	Code	Description	Project	File	Line
Error	C2783	'rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>> &rapidjson::GenericDocument<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::Parse(const char *)': could not deduce template argument for 'parseFlags'	Project_vc14	c:\users\co\documents\app\source\app.cpp	369

So I tried putting in the <0>, although I'm not sure what that does.

Secondly, when compiling the line 

`Value::MemberIterator` member = document.FindMember("member1");`

I get the compiler error:

> Severity	Code	Description	Project	File	Line
Error (active)		function "rapidjson::GenericValue<Encoding, Allocator>::FindMember(const rapidjson::GenericValue<Encoding, Allocator>::Ch *name) [with Encoding=rapidjson::UTF8<char>, Allocator=rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]" (declared at line 618 of "c:\Users\co\Documents\app\rapidjson\include\rapidjson\document.h") is inaccessible	Project_vc14	c:\Users\co\Documents\app\source\app.cpp	1273

and also

> Severity	Code	Description	Project	File	Line
Error	C2248	'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::FindMember': cannot access private member declared in class 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>'	Project_vc14	c:\users\co\documents\app\source\app.cpp	1273

well, duh, clearly I wont be able to access a private function. So the question is how do I get around that and access a member in the doc?

Any help appreciated

**Comment by miloyip** [comment]
What version of RapidJSON are you using? I suspect that you were using a very old version of RapidJSON.

**Comment by TappyApp** [comment]
Thanks for the response. I was indeed using an old version. I downloaded the latest one, and looks like I'm no longer facing that issue. Thanks again!
