### ISSUE TITLE
A huge number and volume of RAM allocs/deallocs.

### ISSUE THREAD

**Issue by dkorolev** [miloyip/rapidjson#694]
Hello and thanks for RapidJSON, you guys rock.

Before we dig further, thought I'd ask here. We ran our RapidJSON-heavy app ([C5T/Current](https://github.com/C5T/current)) under Valgrind using a ~10MB data file of ~50K JSONs.

The by far most frequently called function is RapidJSON's allocation, and the total amount of memory allocated/deallocated is in hundreds of gigabytes. I've been expecting ~200x, but not ~5000x used-to-actual.

Any quick pointer to what we might be doing wrong? Don't mean to spend a lot of your time, a random link to a relevant conversation or two would be more than sufficient to close this question. Thanks!

Dima

**Comment by miloyip** [comment]
A `Document` owns an `PoolAllocator` by default. `PoolAllocator` does not free memory. If you repeatedly calls `Parse()` on the same `Document`, then the allocated memory will be accumulate.
So, it will be better use a new `Document` to `Parse()`, or manually clear the allocator.

**Comment by dkorolev** [comment]
Thank you!
