### ISSUE TITLE
StackAllocator = rapidjson::MemoryPoolAllocator<>]: Assertion `!HasParseError()' failed.

### ISSUE THREAD

**Issue by xcl3721** [miloyip/rapidjson#695]
src/thirdpart/rapidjson/reader.h:704: void rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::ParseStringToStream(InputStream&, OutputStream&) [with unsigned int parseFlags = 0u; SEncoding = rapidjson::UTF8<>; TEncoding = rapidjson::UTF8<>; InputStream = rapidjson::GenericStringStream<rapidjson::UTF8<> >; OutputStream = rapidjson::GenericReader<rapidjson::UTF8<>, rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >::StackStream<char>; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::MemoryPoolAllocator<>]: Assertion `!HasParseError()' failed.

my code:
 rapidjson::Document document;
        document.Parse(msg.c_str());  //<-- it's seem here

        if (document.HasParseError()) {  //<-- or here
            LOG_ERROR << "Json Parser Error:" << msg.c_str();
            return true;
        }

-------
the 704 line from reader.h

        RAPIDJSON_ASSERT(is.Peek() == '\"');
        is.Take();  // Skip '\"'

        for (;;) {
            Ch c = is.Peek();
            if (c == '\\') {    // Escape
                is.Take();
                Ch e = is.Take();
                if ((sizeof(Ch) == 1 || unsigned(e) < 256) && escape[(unsigned char)e]) {
                    os.Put(escape[(unsigned char)e]);
                }
                else if (e == 'u') {    // Unicode
                    unsigned codepoint = ParseHex4(is);
                    if (codepoint >= 0xD800 && codepoint <= 0xDBFF) {
                        // Handle UTF-16 surrogate pair
                        if (is.Take() != '\\' || is.Take() != 'u')
                            RAPIDJSON_PARSE_ERROR(kParseErrorStringUnicodeSurrogateInvalid, is.Tell() - 2);
                        unsigned codepoint2 = ParseHex4(is);
                        if (codepoint2 < 0xDC00 || codepoint2 > 0xDFFF)
                            RAPIDJSON_PARSE_ERROR(kParseErrorStringUnicodeSurrogateInvalid, is.Tell() - 2); //here is 704line －－－－－－－－－－－－－－－－－
                        codepoint = (((codepoint - 0xD800) << 10) | (codepoint2 - 0xDC00)) + 0x10000;
                    }
                    TEncoding::Encode(os, codepoint);
                }
                else
                    RAPIDJSON_PARSE_ERROR(kParseErrorStringEscapeInvalid, is.Tell() - 1);
            }
            else if (c == '"') {    // Closing double quote
                is.Take();
                os.Put('\0');   // null-terminate the string
                return;
            }

**Comment by miloyip** [comment]
Can you provide an example to reproduce the error independently?

**Comment by xcl3721** [comment]
This error is not frequent occurrence......
i guess the unicode code was wrong ....

**Comment by miloyip** [comment]
When there is invalid unicode encoding, it should not fail an assertion but just returning a parse error. As the line number is not consistent with the latest version, I think you may be using some older versions of RapidJSON. You may try update to the latest head version.

If you can find a JSON that causes assertion, you may report with that.

**Comment by xcl3721** [comment]
thank you sir , i will update and try to find it
