### ISSUE TITLE
Error in RapidJson.h

### ISSUE THREAD

**Issue by hiba91** [miloyip/rapidjson#699]
Hi all,

I tried to run the example in example/tutorial/tutorial.cpp on ROOT(CERN) command line. I added the include folder in the ROOT include folder.

When I Run the code I have these errors:

Error: Invalid type 'namespaceRAPIDJSON_NAMESPACE{typedef' in declaration of 'unsigned SizeType' ...\root_v5.34.36/include\rapidjson/rapidjson.h(380)
Error: Symbol namespaceRAPIDJSON_NAMESPACE{typedef unsigned SizeType is not defined in current scope  ...\root_v5.34.36/include\rapidjson/rapidjson.h(380)

Any ideas to correst this?
Thanks for your help.

**Comment by miloyip** [comment]
Can you tell the compiler being used, and also show the command line?

BTW, I think that part of code is pretty safe:

~~~
RAPIDJSON_NAMESPACE_BEGIN
//! Size type (for string lengths, array sizes, etc.)
/*! RapidJSON uses 32-bit array/string indices even on 64-bit platforms,
    instead of using \c size_t. Users may override the SizeType by defining
    \ref RAPIDJSON_NO_SIZETYPEDEFINE.
*/
typedef unsigned SizeType;          // line 380
RAPIDJSON_NAMESPACE_END
#endif~~~

**Comment by hiba91** [comment]
Hi,

I'm using ROOT v5 on windows.
Please find below what all the command line of ROOT shows:


  *******************************************
  *                                         *
  *        W E L C O M E  to  R O O T       *
  *                                         *
  *   Version   5.34/36      5 April 2016   *
  *                                         *
  *  You are welcome to visit our Web site  *
  *          http://root.cern.ch            *
  *                                         *
  *******************************************

ROOT 5.34/36 (v5-34-36@v5-34-36, Apr 05 2016, 10:25:45 on win32)

CINT/ROOT C/C++ Interpreter version 5.18.00, July 2, 2010
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.

root [0] .x tutorial.cpp

Error: Invalid type 'namespaceRAPIDJSON_NAMESPACE{typedef' in declaration of 'unsigned SizeType' ...\root_v5.34.36/include\rapidjson/rapidjson.h(380)
Error: Symbol namespaceRAPIDJSON_NAMESPACE{typedef unsigned SizeType is not defined in current scope  ...\root_v5.34.36/include\rapidjson/rapidjson.h(380)
*** Interpreter error recovered ***

root [1]

**Comment by evsedykh** [comment]
Hi hiba91,

CINT is quite specific tool and is not 100% C++ standard compatible so your question is better to ask at ROOT forum. Another thing that it's not already supported by ROOT team. Now they are using Cling interpreter https://root.cern.ch/cling.

**Comment by hiba91** [comment]
Hello evsedykh,

You're right. In fact I tried to work with ROOT v6 on a Linux server, I used Cling interpreter, and RapidJson is working pretty well with it.

Thank you :)
