### ISSUE TITLE
GetValueByPointer do not allow using std::string directly?

### ISSUE THREAD

**Issue by gas1121** [miloyip/rapidjson#700]
Seems like only `Pointer(source).Get(root)` and `GetValueByPointer(root, Pointer(source), ...)` support std::string and I can't pass std::string directly to `GetValueByPointer`.

**Comment by miloyip** [comment]
Yes, I think it is missing. I will fix it.

**Comment by miloyip** [comment]
I remembered that it is due to prevent too much code bloat by combination explosion.
And in most cases `source` should be literal string.

**Comment by gas1121** [comment]
So should I just use `Pointer(source).Get(root)` instead or convert string to char array before use Pointer?Is there any problem to use `std::string` and `Pointer` together?

**Comment by miloyip** [comment]
Both are fine.

**Comment by gas1121** [comment]
Ok I see. Thank you.

**Comment by LeenLi** [comment]
Pointer(source).Get(root) is good. 
GetValueByPointer is Confusing...
the following code as an example：

har nameArr[MAX_NAME_ARR_SIZE]={0};
snprintf(nameArr,31,"/%s",str.c_str());
const rapidjson::Value* pValue=GetValueByPointer(*val,nameArr);

there is hidden bug
