### ISSUE TITLE
operator [] 重载问题

### ISSUE THREAD

**Issue by lonelymemo** [miloyip/rapidjson#701]
Value &item = list[i]; 为什么不支持这种访问呢？
const Value &list = document["data"]["oc_list"];这样访问就没问题
现有项目使用的jsoncpp，基本都是这样利用json::array的。

**Comment by miloyip** [comment]
http://rapidjson.org/zh-cn/md_doc_tutorial_8zh-cn.html#QueryArray

支持的，但请用 `rapidjson::SizeType` 而不是 `int`。

**Comment by lonelymemo** [comment]
多谢了，我不小心写错了类型，已经解决了
