### ISSUE TITLE
Crash issue!   A string is determined as Double but not a Number

### ISSUE THREAD

**Issue by gujinku** [miloyip/rapidjson#706]
IsDouble() returns true

BUT

IsNumber() returns false

Please double check with your code.

**Comment by miloyip** [comment]
Can you provide reproducible code?

**Comment by gujinku** [comment]
Hi Miloyip, I just override all the old code with the latest version in our project.  I will try to figure out the reproducible code but not sure.  At the same time, could you please review the code?

**Comment by gujinku** [comment]
@miloyip , sorry, my bad. I misused it.
