### ISSUE TITLE
Error building on Raspberry Pi // Raspbian || Error in `/usr/bin/c++': double free or corruption (top)

### ISSUE THREAD

**Issue by Trig0n** [miloyip/rapidjson#707]
Whilst making the Project I get this Error:
**\* Error in `/usr/bin/c++': double free or corruption (top): 0x001ff398 ***

"Trace":
example/CMakeFiles/schemavalidator.dir/build.make:62: recipe for target 'example/CMakeFiles/schemavalidator.dir/schemavalidator/schemavalidator.cpp.o' failed
make[2]: **\* [example/CMakeFiles/schemavalidator.dir/schemavalidator/schemavalidator.cpp.o] Error 134
CMakeFiles/Makefile2:1061: recipe for target 'example/CMakeFiles/schemavalidator.dir/all' failed
make[1]: **\* [example/CMakeFiles/schemavalidator.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

Am I missing something or is that a bug?

**Comment by houtianze** [comment]
Is it due to this bug in GCC?
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091&p=922980
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132

Can't believe GCC devs allowed this kind of sloppy code in.

**Comment by Trig0n** [comment]
@houtianze 
Thanks for the response.
I'm going to upgrade GCC and report back.

**Comment by Andy1978** [comment]
I'm seeing the same problem and I manually patched CMakeLists.txt in line 58:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mcpu=cortex-a53 -mfpu=neon-vfpv4")`

**Comment by Trig0n** [comment]
Somehow I forgot to respond. Sorry for that.
As far as I remember it was because of that bug.
