### ISSUE TITLE
operator [] 取值 coredump

### ISSUE THREAD

**Issue by lonelymemo** [miloyip/rapidjson#712]
代码中有一段是
const Value &str_time = datatime["datetime"];
运行了很长一段时间没有问题后，突然在周末coredump了。gdb跟进发现是core在了rapidjson/document.h:1154的FindMember的
RAPIDJSON_ASSERT(IsObject());这短代码上了，gdb显示flags = 0.
请问这是什么情况导致的呢？

**Comment by miloyip** [comment]
就是说那个 JSON 不是 object。
应先检测 `if (datatime.IsObject()) ...`

**Comment by lonelymemo** [comment]
for (SizeType j = 0; j < datavalue.Size(); ++j)
            {
                    const Value &datatime = datavalue[j];
这个应该不需要把？代码多次运行到这里，到现在为止出现过一次CORE。

**Comment by lonelymemo** [comment]
原因找到了。低级错误

**Comment by ShufengWang** [comment]
> 原因找到了。低级错误

请教下是什么原因呢？最近也遇到类似问题
