### ISSUE TITLE
parsebyparts example AsyncDocumentParser class issue

### ISSUE THREAD

**Issue by v-vodyanov** [miloyip/rapidjson#716]
I tried to use AsyncDocumentParser from parsebyparts example to process some json many times and almost always (not in the same place, but practically guaranteed on the long run) got crash on unique_lock creation in the beginning of parsing thread. Further research showed that things might go that way: parseThread_ is creating and immediately staring to execute, and mutex, initialized right after might, **or might not** get created by time of his first locking by parse thread. After moving thread creation to the end of list, problem disappeared. Maybe it's worth fixing, if someone else will try to use this example as working source? I tried this on XCode 7.3.1 (clang-703.0.31).

**Comment by miloyip** [comment]
I think this should be what you mean. Please help verifying if this works. Thank you.
