### ISSUE TITLE
GenericStringRef::operator= does not compile

### ISSUE THREAD

**Issue by yachoor** [miloyip/rapidjson#718]
[`GenericStringRef::operator=`](https://github.com/miloyip/rapidjson/blob/f54b0e47a08782a6131cc3d60f94d038fa6e0a51/include/rapidjson/document.h#L319) tries to assign values to constant members, failing to compile:
```c++
rapidjson::GenericStringRef<char> a("");
rapidjson::GenericStringRef<char> b("");
a = b;
```
generates errors:
error: assignment of read-only member 'rapidjson::GenericStringRef<char>::s'
error: assignment of read-only member 'rapidjson::GenericStringRef<char>::length'

Unfortunately one of the compilers I use is overeager with member functions of templates and fails compilation even if it is never called :(
Since it doesn't compile anyways and compiler-generated default one will fail the same I think it can be safely deleted.

**Comment by miloyip** [comment]
Thank you
