### ISSUE TITLE
惭愧，英文非常不好。

### ISSUE THREAD

**Issue by githublaohu** [miloyip/rapidjson#735]
大神，你好。
看了 api文档，与源码里面的注释。诠释英文。看起来很吃力.......
能支持一点，中文api文档吗？
多谢。

**Comment by miloyip** [comment]
API 文档比较难支持多种语言。
如需要，可以考虑加多点例子或使用手册内容。

**Comment by githublaohu** [comment]
更多是想 深入了解，rapidjson，优秀，友好的设计，编码。

**Comment by lonelymemo** [comment]
coder英文能力还是要有的，可以不会写，至少要能读。
