### ISSUE TITLE
compile error by gcc-4.4.7

### ISSUE THREAD

**Issue by acelyc111** [miloyip/rapidjson#741]
the error is:
include/rapidjson/writer.h:110: error：‘nullptr’ has not been declared
it seemed that RAPIDJSON_HAS_CXX11_RVALUE_REFS has been defined as 1 by
#elif (defined(RAPIDJSON_GNUC) && (RAPIDJSON_GNUC >= RAPIDJSON_VERSION_CODE(4,3,0)) && defined(__GXX_EXPERIMENTAL_CXX0X__)) || \
      (defined(_MSC_VER) && _MSC_VER >= 1600)

#define RAPIDJSON_HAS_CXX11_RVALUE_REFS 1
#else
#define RAPIDJSON_HAS_CXX11_RVALUE_REFS 0
#endif

but nullptr is sopported after gcc 4.6
https://gcc.gnu.org/gcc-4.6/changes.html

**Comment by miloyip** [comment]
Thanks
