### ISSUE TITLE
Why not virtual destructor for GenericValue class?

### ISSUE THREAD

**Issue by sin0emp** [miloyip/rapidjson#751]
Lets say
```
rapidjson::Value* d = new rapidjson::Document();
delete d;
```
This causes memory leak because GenericValue class's destructor is not virtual. So is there a reason it is this way? Maybe avoiding the performance cost?

**Comment by sin0emp** [comment]
Ok, it is described in the comments.

> warning Although GenericDocument inherits from GenericValue, the API does not provide any virtual functions, especially no virtual destructor.  To avoid memory leaks, do not delete a GenericDocument object via a pointer to a GenericValue.

I think the library should provide a workaround for this situation, at least have a type info in the GenericValue class as dynamic_cast wont work on it either.

**Comment by stervo4ka** [comment]
If it's not about "style" and you just need a workaround, you can use shared_ptr which calls the original deleter even after upcast. Or you can keep track of the original destructor manually whatever way you want.
