### ISSUE TITLE
transfer Value to caller place (out of life cycle)

### ISSUE THREAD

**Issue by lincoln310** [miloyip/rapidjson#754]
Hi, i got a question:
  I want to define a function:
     rapidjson::Value jsonValue(){}
  for a class, to translate it's value to json object.
  And transfer it to caller place, then write to string, or continue to transfer.
  But i'm confused by allocator. As i understand, the memory used by a Value is allocated by the allocator, and when allocator is finished, the value should be killed to.
  So, do i need a globle allocator? 

如果英文表述错误或者不清晰，我用中文再描述下：
  我想为我的每个class都定义一个json生成函数，这样可以方便获取json变量，然后传递到调用者的位置，然后继续传递或者输出等。
  但是大部分的rapidjson都需要一个allocator来控制内存分配。如果我在生成的地方定义一个rapidjson::Document，并使用其GetAllocator，那么在返回json的时候，该document就会析构，同时其allocator也会析构，那么基于这个allocator分配的value就失效了，返回值就不可预测了。
   我应该怎么做？

**Comment by miloyip** [comment]
Global allocator is not a good choice.
How about this?

~~~cpp
class Foo {
public:
    virtual void CreateValue(RapidJSON::Value& value, RapidJSON::Document::AllocatorType& allocator) const = 0;
};

Document d;
Value v;
d.SetArray();
const Foo* f = ...
f->CreateValue(v, d.GetAllocator());
d.PushBack(v. d.GetAllocator());
~~~

**Comment by lincoln310** [comment]
yes, this seems good, why not use shared_ptr as default?
BTW, can i use SetValueByPoint to set a Value?

**Comment by miloyip** [comment]
RapidJSON can support C++03.
`SetValueByPointer()` can be used to set a `Value` into the DOM.

**Comment by lincoln310** [comment]
ok, i understand. Thank you!
