### ISSUE TITLE
Use of "enum" in "oneOf" results in incorrect validation failure

### ISSUE THREAD

**Issue by sbalousek** [miloyip/rapidjson#764]
Hi folks.

RapidJSON is great, thanks for the effort!

I ran across an issue with schema validation in version 1.1.0 that looks like a bug to me.

Using this schema:
``` .json
{
    "description":  "Illustrate a validation bug related to oneOf and enum in RapidJSON",
    "$schema":      "http://json-schema.org/draft-04/schema#",
    "type":         "object",
    "properties": {
        "when": {
            "oneOf": [
                {   "enum": [ "now"    ]  },
                {   "type":   "string",
                    "format": "date-time" }
            ]
        }
    }
}

```

validation fails with this document, but it should succeed:
``` .json
{ "when": "now" }
```

validation succeeds with these documents but should fail:
``` .json
{ "when": "later" }
{ "when": "2016-10-06T10:00" }
```

It looks like "date-time" string validation might be missing, which would explain the false positive on the last two documents.  The first document, however, should validate.

I'm new to RapidJSON, so perhaps there is something I am missing.  I've attached my example source code.

Thanks!
- Steve B

**Example code**
[oneOfBug.cpp](https://github.com/miloyip/rapidjson/files/514385/oneOfBug.txt)

**Comment by miloyip** [comment]
It is stated in the [documentation](http://rapidjson.org/md_doc_schema.html) that:

> Besides, the format schema keyword for string values is ignored, since it is not required by the specification.

It is not required by the [spec](http://json-schema.org/latest/json-schema-validation.html#anchor104):

> 7.2.  Implementation requirements
> Implementations MAY support the "format" keyword. Should they choose to do so:
> they SHOULD implement validation for attributes defined below;
> they SHOULD offer an option to disable validation for this keyword.
> Implementations MAY add custom format attributes. Save for agreement between parties, schema authors SHALL NOT expect a peer implementation to support this keyword and/or custom format attributes.

It is quite difficult to implement all the formats  in the spec, with small code size.

However, you may use the `pattern` keyword instead, if it is suitable.

**Comment by sbalousek** [comment]
Thanks for the feedback on the `format` keyword.  I did not know the specification declared it optional.  Other validation engines I've seen treat the `format` keyword the same as `pattern` but with pre-defined regular expressions.  I wouldn't expect the code size to increase much with that approach.

There still is an issue with the first document mentioned, though.  Why would this document not be considered valid?

``` .json
{ "when": "now" }
```

**Comment by miloyip** [comment]
As I know, email or uri are very complicated (for fully conformance) and cannot be represented by regex.

It is because `oneOf` requires one and only one schema to be valid, but in your schema, both the enum one and the string one (`format` is ignored) are valid for `"now"`:

~~~
$ ./schemavalidator /tmp/s.json < /tmp/a.json
Input JSON is invalid.
Invalid schema: #/properties/when
Invalid keyword: oneOf
Invalid document: #/when
~~~

Changing `oneOf` to `anyOf` can make it pass.

**Comment by sbalousek** [comment]
Of course.  Thanks for the response.

I'll look into using `pattern` where I can.
