### ISSUE TITLE
warning C4003: “max”宏的实参不足

### ISSUE THREAD

**Issue by ccpaging** [miloyip/rapidjson#766]
rapidjson\document.h(958): warning C4003: “max”宏的实参不足
rapidjson\document.h(964): warning C4003: “min”宏的实参不足
rapidjson\document.h(965): warning C4003: “max”宏的实参不足
rapidjson\document.h(982): warning C4003: “max”宏的实参不足
rapidjson\document.h(983): warning C4003: “max”宏的实参不足

Visual Studio 2010

Add following in _MSC_VER section of document.h

```c
#undef max
#undef min
```

**Comment by miloyip** [comment]
These macros are not defined by Visual C++ actually.
They should have been defined by `WinDef.h`.
You may defined `NOMINMAX` macro to prevent defining such macros.
It is not safe to just undef them in `document.h` as there is no way to restore them.

**Comment by miloyip** [comment]
Fixed in #748
