### ISSUE TITLE
Document::ReplaceMember()

### ISSUE THREAD

**Issue by arg0d** [miloyip/rapidjson#771]
I'm working with RapidJSON to modify DOM tree. While JSON spec doesn't require members of an object to be ordered, in my current project it would be really nice to have ordered members.

I have written a small wrapper around Document to allow easier modification of DOM tree. What it does is if Value.HasMember() returns true, it will remove the member and insert a new one with the same name. What I don't like is that when I'm modifying object's member, the modified member will always end up in the back.

My current solution is when Value.HasMember() returns true, use function Value.ReplaceMember() - its supposed to get rid of the old member with specified name and add new value in it's place. If Value.HasMember() has returned true, I just add the member with Value.AddMember().

```
if (mValue.HasMember(key)) {
	mValue.ReplaceMember(key, value);
}
else {
	rapidjson::Value keyValue;
	keyValue.SetString(key, mDoc->GetAllocator());
	mValue.AddMember(keyValue, value, mDoc->GetAllocator());
}
```

The below code is placed somewhere in Document.h ~1300-ish line. I would be grateful if someone who knows RapidJSON internals could review this code.

```
void ReplaceMember(const char * key, GenericValue& value) {
	MemberIterator iter = FindMember(key);
	RAPIDJSON_ASSERT(iter != MemberEnd());
	
	(*iter).value.~GenericValue();
	(*iter).value.RawAssign(value);
}
```

**Comment by miloyip** [comment]
You can simply change the value in member:

~~~cpp
MemberIterator iter = parent.FindMember(key);
if (iter == MemberEnd())
    parent.AddMember(key, newValue);
else
    iter->value = newValue;
~~~

You may also use [JSON pointer](http://rapidjson.org/md_doc_pointer.html) to achieve your requirement:

~~~
SetValueByPointer(d, "/key1/key2", newValue);
~~~

This will create all intermediate nodes if not exist.

**Comment by arg0d** [comment]
Thanks, much cleaner solution to my problem.
