### ISSUE TITLE
Schema validation inheritance support

### ISSUE THREAD

**Issue by icechen1** [miloyip/rapidjson#775]
Hello!

Love the library and I've been using the json schema validation in my project. I was wondering if the `extends` keyword is supported with the validator?

Here's the relevant documentation:
https://github.com/json-schema/json-schema/wiki/Extends

Example of usage:
```
{
    "description":  "Illustrate a the use of extends keyword",
    "$schema":      "http://json-schema.org/draft-04/schema#",
    "extends" : { "$ref" : "parent.schema.json" },
    "type":         "object",
    "properties": {
         ...
    }
}
```

Now when we validate this document it will validate both the current and inherited document's fields.

**Comment by miloyip** [comment]
No. `extends` was removed in earlier draft.
You can use `allOf` to make a schema "inherit" from multiple schemas.
See https://spacetelescope.github.io/understanding-json-schema/structuring.html

**Comment by icechen1** [comment]
Thanks!
