### ISSUE TITLE
Is RAPIDJSON_SSE2 supported on ARM / iOS?

### ISSUE THREAD

**Issue by mylodeon** [miloyip/rapidjson#779]
Probably a very dumb question, but I've never tried this before on the mobile platforms:

If I enable RAPIDJSON_SSE2 I'm getting various compile errors like:

**Android**
```
Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin\..\lib64\clang\3.8.256229\include\mmintrin.h:105:19: 
error: use of undeclared identifier '__builtin_ia32_punpcklbw'
```

and 
**iOS**

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/mmintrin.h:123:19: 
note: '__builtin_arm_qadd' declared here
```

I'm not sure if this is supposed to work (and I'm just missing a header or compiler switch) or if it's not supposed to work. 

It's totally fine if it doesn't - just trying to figure out if I should spend more time trying to get the mobile builds to work or if I should RAPIDJSON_SSE2 to OSX & Windows platforms.

**Comment by miloyip** [comment]
SSE2 is one of Intel's SIMD instruction set.
ARM does not support it.

**Comment by mylodeon** [comment]
Thanks! Was just wondering if it would use Neon or something, but this is fine - I'll just disable it on ARM.
