### ISSUE TITLE
parse error on \b character

### ISSUE THREAD

**Issue by tinro** [miloyip/rapidjson#780]
Example: {"a":"\bb"}
It throws parsing error just like it is parsing {"a":b"}
I am not sure about whether there is a standard on this case.

**Comment by miloyip** [comment]
`\b` is supported. Please provide reproducible code.

**Comment by tinro** [comment]
```
#include <rapidjson/document.h>
#include <rapidjson/error/en.h>
#include <string>
#include <iostream>

int main() {
    std::string json = "{\"a\":\"\bb\"}";
    rapidjson::Document doc;
    rapidjson::StringStream is(json.c_str());
    doc.ParseStream(is);
    if (doc.HasParseError()) {
        std::cout << "parse error:" << rapidjson::GetParseError_En(doc.GetParseError()) << " offset:" << doc.GetErrorOffset() << std::endl;
    }
    return 0;
}
```
output:
```
parse error:Invalid escape character in string. offset:6
```

**Comment by miloyip** [comment]
`"\b"` is an escaped character in C++. It will be escaped as ASCII code 8, which is invalid in JSON.

I think what you want should be `"\\b"`:
~~~cpp
std::string json = "{\"a\":\"\\bb\"}";
~~~

**Comment by tinro** [comment]
Thanks for your suggestions, however the error happens when I am trying to parse the json document generated by other languages. Seems it does not meet standard's requirement. I will try to fix this problem before it goes into rapidjson.
