### ISSUE TITLE
Compilation error on AIX OS 7100-03-03-1415

### ISSUE THREAD

**Issue by amandatta16** [miloyip/rapidjson#781]
rapidjson/reader.h", line 1078.9: 1540-0064 (S) Syntax error:  "~NumberStream<rapidjson::GenericStringStream<rapidjson::UTF16<wchar_t> >,0,0>" was expected but "~NumberStream" was found.

**Comment by miloyip** [comment]
~~~cpp
    template<typename InputStream>
    class NumberStream<InputStream, false, false> {
    public:
        typedef typename InputStream::Ch Ch;

        NumberStream(GenericReader& reader, InputStream& s) : is(s) { (void)reader;  }
        ~NumberStream() {} // line: 1078
~~~

I have no idea what gets wrong here.

**Comment by amandatta16** [comment]
Hi Miloyip, thanks for replying. Actually i am building the same project on windows , Linux and AIX.
.Not sure why it is failing only on AIX

**Comment by miloyip** [comment]
@FrozenGene not sure if you know how to solve this.

**Comment by amandatta16** [comment]
I am using a 64bit AIX machine any conflict between library and my machine

**Comment by FrozenGene** [comment]
Hi, @amandatta16 could you tell me more about the build environment? especially OS version and XL compiler version. I will try to reproduce the problem when I am free tomorrow. Thanks.

**Comment by amandatta16** [comment]
Hi, @FrozenGene, here are the details.

OS version -7 - AIX OS 7100-03-03-1415
compiler - IBM XL C/C++ for AIX, V10.1, Version: 10.01.0000.0011

sample program copied from http://rapidjson.org/index.html

// rapidjson/example/simpledom/simpledom.cpp

#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"
#include <iostream>
using namespace rapidjson;
int main() {
    // 1. Parse a JSON string into DOM.
    const char* json = "{\"project\":\"rapidjson\",\"stars\":10}";
    Document d;
    d.Parse(json);
    // 2. Modify it by DOM.
    Value& s = d["stars"];
    s.SetInt(s.GetInt() + 1);
    // 3. Stringify the DOM
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);
    // Output {"project":"rapidjson","stars":11}
    std::cout << buffer.GetString() << std::endl;
    return 0;
}

**Comment by FrozenGene** [comment]
Hi  @miloyip @amandatta16 

Firstly, this is one bug of IBM AIX XL C++ compiler, the source code is not wrong.

Secondly, we have fixed it in the recent compiler. IBM AIX XL C++ V10.1 is released in the 2008, but our newest AIX XL C++ is 13.1.3. I have tested the newest compiler 13.1.3, which has no problem. I suggest @amandatta16 could upgrade the compiler.

Thirdly, if we don't want to upgrade and want to support the old IBM AIX XL C++ compiler, @miloyip would you mind changing the source code? For example:

```cpp
template<typename InputStream>
class NumberStream<InputStream, false, false> {
public:
    typedef typename InputStream::Ch Ch;
    
    NumberStream(GenericReader& reader, InputStream& s) : is(s) { (void)reader;  }
    // ~NumberStream() {} // line: 1078
```

just remove the destructor. As far as I know, this destructor does nothing and not virtual, so from the syntax view, we could remove it safely, if not right, please correct me.  

And if we remove the destructor , IBM AIX XL C++ compiler would be happy, which can compile and run whole rapidjson project well.

**Comment by amandatta16** [comment]
Thanks @FrozenGene @miloyip , I think i can not upgrade the IBM AIX XL C++ compiler, @miloyip help  regarding commenting ~NumberStream() {}

**Comment by miloyip** [comment]
Thank you @FrozenGene for the solution.
