### ISSUE TITLE
GenericValue.CopyFrom inherits StackAllocator

### ISSUE THREAD

**Issue by robertturner** [miloyip/rapidjson#786]
Actual error is in method GenericValue<Encoding,Allocator>::GenericValue(const GenericValue<Encoding,SourceAllocator>& rhs, Allocator& allocator)

when deep copying array or object, local GenericDocument d doesn't allow custom StackAllocator.

**Comment by miloyip** [comment]
Can you explain in more detail, or with an example to illustrate the issue?

**Comment by robertturner** [comment]
Yeah of course:
Background: We use rapidjson in an embedded environment and use our own Allocator instead of the CrtAllocator. We use our custom allocator and provide an instance for the StringBuffer, Writer & both of the GenericDocument's values and stack allcators. This generally works very well as the template arguments and constructors are perfectly suited.

We discovered a bug when using the CopyFrom method, which then calls the GenericValue copy constructor   (line 2419 @ document.h current master). If the rhs argument is an object or array (as tested by the switch statement on the first line of the copy constructor), I suspect the source of the bug is in the next line of code: 
`GenericDocument<Encoding,Allocator> d(&allocator);` (line 2424)
Which doesn't specify custom template argument for the StackAllocator (template argument 3 of GenericDocument) and thus defaults to the CrtAllocator.
Does that make sense?
Thanks

**Comment by miloyip** [comment]
Thank you for your detailed explanation. I will try to fix it.

**Comment by robertturner** [comment]
Great work, thanks for the fast turn around!
