### ISSUE TITLE
[Question] Best way for convert to GenericValue to GenericDocument?

### ISSUE THREAD

**Issue by xpol** [miloyip/rapidjson#787]
I need a way to convert `GenericValue` to `GenericDocument`, I have found the follow way:

if I have a temp (or rvalue ref) `GenericValue` named `value` and a newly constructed `GenericDocument` named `document`.

1. `value.Swap(document);`
2. `Pointer("").Set(document, value);`

Did I miss some? Which is the best?

**Comment by miloyip** [comment]
The main issue will be whether the value has allocated memory from some allocators.
If that is the case, and you want the `value` to use memory allocated by the `document`, then you can use `CopyFrom()` to deep-clone it:
~~~
document.CopyFrom(value, document.GetAllocator());
~~~

If the `value` was created with `document`'s allocator already, and you just want to assign it to `document`, then I will suggest your first option.

**Comment by xpol** [comment]
Thank you very much!
I have change my code to pass final `document`'s allocator into the construction method for `value`.

Then later it is better for using `value.Swap(document);`.
