### ISSUE TITLE
Handling NAN values when kWriteNanAndInfFlag is not set

### ISSUE THREAD

**Issue by BongoVR** [miloyip/rapidjson#795]
The comment in writer.h at line 526 is not quite correct.

When you create a document at runtime using AddMember like this:
> obj.AddMember("nix", std::numeric_limits<double>::quiet_NaN(), dok2.GetAllocator());

you will fail to write the JSON file with default settings.
AFAIK, the JSON standard says that NAN and INF values have to be written as null values.
Therefore, the library should always make sure that NAN and INF values get correctly written to JSON:
>        if (!(kWriteDefaultFlags & kWriteNanAndInfFlag)) {
>            PutReserve(*os_, 4);
>            PutUnsafe(*os_, 'n'); PutUnsafe(*os_, 'u'); PutUnsafe(*os_, 'l'); PutUnsafe(*os_, 'l');
>            return true;
>        }

This fixes the problem in (default) standard mode.

**Comment by pah** [comment]
Quoting [RFC7159](https://tools.ietf.org/html/rfc7159):
>  Numeric values that cannot be represented in the grammar below (such 
   as Infinity and NaN) are not permitted.

**Comment by BongoVR** [comment]
But according to ECMA-262 (http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf):
"Finite numbers are stringified as if by calling ToString(number). NaN and Infinity regardless of sign are represented as the String null."
(See chapter 24.3.2, p. 507, NOTE 4).

**Comment by miloyip** [comment]
In [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) §8:

> Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not permitted. 

`JSON.stringify()` is an ECMAScript function that generates JSON text (according to ECMA-404). Converting NaN/inf into `null` will make the result text a valid JSON. However, this is only what ECMAScript does, ECMA-404 did not state this conversion.
