### ISSUE TITLE
no errors with wrong schema 

### ISSUE THREAD

**Issue by Christian-Holz** [miloyip/rapidjson#804]
Hi,

is it possible to add an error or at least warning for this invalid schema?
```
{
    "$schema": "http://json-schema.org/schema#",
    "definitions": {
        "jobList": {
            "pages2":                  { "type": "integer", "minimum":0 },
            "required": [
                "pages2"
            ]
        }
    },

    "type": "object",
    "properties": {
        "pages1":                  { "type": "integer", "minimum":0 },
        "jobLists": {
            "type": "array",
            "items": { "$ref": "#/definitions/jobList" }
        }
    },
    "required": [ "jobLists" ]
}
```

Input:
```
{
  "pages1": 0,
  "jobLists":[
	{
	  "pages2": 0
	}
	]
}
```

In definitions/jobList are property and type missing.
thx
regards
zerochen

**Comment by miloyip** [comment]
You can validate a JSON schema by the JSON schema.
However, JSON schema allows keys that is not included in the schema. 
You can try http://www.jsonschemavalidator.net/ for seeing this.

**Comment by Christian-Holz** [comment]
Yes i used this one https://json-schema-validator.herokuapp.com/
It warns about some keywords are ignored.
So i guess it is not possible to add some warnings.

Thx
Regards
Chris
