### ISSUE TITLE
Combining DOM and SAX parsing

### ISSUE THREAD

**Issue by mmaypo** [miloyip/rapidjson#807]
First, I really appreciate Rapidjson, nice work! 

Ok, I have a JSON configuration string which contains many optional values. 
Among these optional values is an array of conditional logic expressions 
in prefix order, each of which looks something like this:

    { "AND": [
        {"==": ["is_bit_field", "true"]},
        {"OR": [
                {"==": [{"&": ["val1", "0xFFFF8800"]}, "0x17706000"]},
                {"==": ["(val1 & 0xFFFF6000)", "0x10006000"]},
                {"==": ["(val2 & 0xFFFF6000)", "0x32106000"]}
            ]
        },
        { "<": ["val3", 3]},
        { ">": ["val4", 4]}	
        ]
    }

each expression needs to be converted into an infix C syntax string like this:

 if (!is_bit_field && ((val1 & 0xFFFF6000) == 0x10006000 || (val2 & 0xFFFF6000) == 0x12006000)
		&& val3 > 8 && val4 > 3)
		
the Rapidjson SAX parser with a handler and stack i maintain works nicely for this. However, it's not practical to use the SAX parser on the entire configuration file, just each conditional expression. So I ended up converting the JSON string to a document, iterating over the conditional expressions, copying each to a StringStream, and then using the SAX parser.
This is all working properly, but I need to do a lot of these fast and would like to reduce the copying
by having the SAX parser accept a GenericValue as shown in this code snippet (error handling omitted for brevity):

`

	 struct MyHandler : public BaseReaderHandler<UTF8<>, MyHandler> {
		// ....
	 }

	bool
	from_doc(rapidjson::Document const & jdoc)
	{
		using namespace rapidjson;

		MyHandler handler;
		Reader reader;
		StringBuffer sb;
		
		// ... other Document element handling 

		if (jdoc.HasMember("filters")) {

			Value const & filters = jdoc["filters"];
			if (!filters.IsArray()) return false;

			for (SizeType i = 0; i < filters.Size(); i++) {
				auto sval = filters[i].FindMember("filter_json");

				// ===>> HOW IT WORKS NOW <<===
				sb.Clear();
				Writer<StringBuffer> writer(sb);
				sval->value.Accept(writer); 

				StringStream ss(sb.GetString());
				handler.Reset();
				auto result = reader.Parse(ss, handler);

				// ===>> WOULD BE NICE <<===
				handler.Reset();
				auto result = reader.Parse(sval->value, handler);
			}
		}

		return true;
	}
`

So, am I missing something that could make it faster using existing Rapidjson functionality, or is this a reasonable feature request?

**Comment by miloyip** [comment]
You can use `sval.Accept(handler)` to generate SAX events to your handler. No need to stringify it.

**Comment by mmaypo** [comment]
perfect! thank you.
