### ISSUE TITLE
Not able to create objects using helper functions

### ISSUE THREAD

**Issue by agupta-riverbed** [miloyip/rapidjson#813]
I am very new to rapidjson and trying to use in my project. Below is the scenario I created

void helper(const std::string& data, Value& obj, Document::AllocatorType& allocator){
  ...
  obj.AddMember(key, value, allocator);
  ...
}

Document some_func(){
  ...
  Document doc;
  doc.SetObject();
  Document::AllocatorType& allocator = doc.GetAllocator();
  Value objValue(kObjectType);
  objValue.AddMember(key,value , allocator);
  string data = some_data();
  helper(data, objValue, allocator);

  string data_one = some_data();
  helper(data_one, objValue, allocator);

  doc.AddMember(key, objValue, allocator);
}

The final Document is gibberish looks like allocator is not able to allocate memory for new object in helper function. Is this a bug or I am missing something? Please correct me if I am doing sometging wrong? Thanks!

**Comment by miloyip** [comment]
I don't see the problem in the code. Can you give a minimal reproducible example that shows the problem?

**Comment by agupta-riverbed** [comment]
@miloyip I figured out the issue, it was the way I was passing the string. Earlier I was passing the string by refs which was causing the issue. Thanks for your response :)
