### ISSUE TITLE
patternProperties & additionalProperties lead to ASSERT

### ISSUE THREAD

**Issue by SnapKrakPop** [miloyip/rapidjson#825]
Using this awesome lib has been a tremendous time saver, so thanks for that =)

Curious case I'm experiencing:

    schema:
    {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^i": { "type": "string" }
      }
    }
    input: { "item": "hello" }

This leads to schema.h:1844:
  
`RAPIDJSON_ASSERT(CurrentContext().valueSchema);`

Compiled in Visual Studio 2013, x64.  

However, if I remove additionalProperties, everything runs just fine.  So, no urgency on my end, the workaround is not a problem, just thought I'd let you know.

Keep up the good work!

UPDATE: I've added the following lines and everything seems to function...

schema.h:786:

    bool Schema::Key()
    {
        if (patternProperties_) {
            context.patternPropertiesSchemaCount = 0;
            for (SizeType i = 0; i < patternPropertyCount_; i++)
            {
                if (patternProperties_[i].pattern && IsPatternMatch(patternProperties_[i].pattern, str, len))
                {
                    context.patternPropertiesSchemas[context.patternPropertiesSchemaCount++] = patternProperties_[i].schema;
                    context.valueSchema = typeless_;
                }
            }
        }
        ....
    }

**Comment by tucher** [comment]
I've faced the same problem and this fix seems to be working.

**Comment by miloyip** [comment]
Sorry for late response to this. The fix has been commited. Thank @SnapKrakPop for reporting and providing a fix on this.
