### ISSUE TITLE
RAPIDJSON_HAS_CXX11_RANGE_FOR is error defined

### ISSUE THREAD

**Issue by acelyc111** [miloyip/rapidjson#831]
in include/rapidjson/rapidjson.h:
#elif (defined(RAPIDJSON_GNUC) && (RAPIDJSON_GNUC >= RAPIDJSON_VERSION_CODE(4,3,0)) && defined(__GXX_EXPERIMENTAL_CXX0X__)) || \
      (defined(_MSC_VER) && _MSC_VER >= 1700)
#define RAPIDJSON_HAS_CXX11_RANGE_FOR 1
RAPIDJSON_HAS_CXX11_RANGE_FOR is defined as 1 when gcc version is greater than 4.3.0, but range-based for loops is supported in gcc 4.6. https://gcc.gnu.org/gcc-4.6/changes.html

**Comment by acelyc111** [comment]
https://gcc.gnu.org/projects/cxx-status.html#cxx11
this page can give more information about C++11 features supported in gcc

**Comment by miloyip** [comment]
Thank you
