### ISSUE TITLE
Most efficient way to go from rapidjson::StringBuffer to std::string ?

### ISSUE THREAD

**Issue by jcelerier** [miloyip/rapidjson#846]
It seems that currently the only way implies a copy from one to the other.

Wouldn't it be possible, under the RAPIDJSON_HAS_STDSTRING conditions, to have an allocator for the rapidjson::StringBuffer that uses a std::string internally, so that it could be fetched afterwards without unnecessary copies ?

**Comment by masseman** [comment]
Do you mean for writing the finished `rapidjson::Document` to a string? For that, I do the following:

```
void writeDocumentToString(const rapidjson::Document& document,
                           std::string& output)
{
  class StringHolder
  {
  public:
    typedef char Ch;
    StringHolder(std::string& s) : s_(s) { s_.reserve(4096); }
    void Put(char c) { s_.push_back(c); }
    void Clear() { s_.clear(); }
    void Flush() { return; }
    size_t Size() const { return s_.length(); }
  private:
    std::string& s_;
  };

  StringHolder os(output);
  rapidjson::Writer<StringHolder> writer(os);
  document.Accept(writer);
}
```

**Comment by jcelerier** [comment]
yes, this makes sense ! I'm not using the rapidjson::Document api but writer directly. Thanks !

**Comment by OlafvdSpek** [comment]
It might be nice to such a class be part of the library itself.

**Comment by miloyip** [comment]
`rapidjson::OStreamWrapper` in [`rapidjson/ostreamwrapper.h`](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/ostreamwrapper.h) can wrap `std::ostringstream`. And then you can get a `std::string` from the `std::ostringstream` instance.

**Comment by jcelerier** [comment]
@miloyip std::ostringstream::str() does a copy which I'd like to avoid

**Comment by OlafvdSpek** [comment]
@miloyip What about a `write(const Document&, std::string&)` function? That'd nicely hide the details.
