### ISSUE TITLE
In-situ non-destrutive parsing

### ISSUE THREAD

**Issue by michaeleiselsc** [miloyip/rapidjson#850]
Hi, I'd like to have in-situ non-destructive parsing. for example, i don't need a '\0' at the end of a string because i can just use the length property that's passed back, so it doesn't need to change. is this possible?

**Comment by StilesCrisis** [comment]
Not really possible in many cases. The string can have escape codes like \r \n \" or \u1234 in it, which need to be converted to native form.

**Comment by michaeleiselsc** [comment]
no worries, turns out that if i just memcpy the old string back, the performance isn't much different

**Comment by StilesCrisis** [comment]
I think this issue can be closed.
