### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by madguy02** [miloyip/rapidjson#855]
"/include/rapidjson/document.h: No such file or directory
compilation terminated"

According to the installation procedure,i have added include to the project folder,inside build.The structure looks something like : "folder/build/include/rapidjson".But still facing issues with "document.h".
Help me out with this

**Comment by miloyip** [comment]
You need to set include path or copy rapidjson/include into your own source folder.

**Comment by madguy02** [comment]
absolutely ...yes thanks a lot
