### ISSUE TITLE
How to handle (unknown) data in huge nested JSON documents 

### ISSUE THREAD

**Issue by blacksheep1970** [miloyip/rapidjson#861]
Hello,
I am new to C++ and JSON so please be kind and don't blame on me ;)

I have written code which downloads a huge JSON file from a REST API. The JSON is in a string and can be successful parsed with rapidjson.

Since the data in JSON can change I do not have a fix possibility to access the data like e.g. on database tables. So my dream is to be able to loop over the JSON data and store the content in a vector.

The DOM (describing a star system) looks like the following (not all nodes are open, there are deep nodes containing up to 900 members:

object {4}
...............success :1
...........->data {5}
...............config{6}
...........->systems{9}
..............................rowcount:	90
..............................	totalrows:	90
..............................estimatedrows:	false
..............................pagesize:0
..............................pagecount:null
..............................page:	1
..............................offset:0
..............................startrow:0
..............................resultset[90]
..........................->tunnels{9}
..........................->species{9}
..........................->affiliations{9}
..............................rowcount:6
..............................totalrows:6
..............................estimatedrows:false
..............................pagesize:0
..............................pagecount:null
..............................page:1
..............................offset:0
..............................startrow:	0
..........................->resultset[6]
..........................................->0 {4}
..........................................->1 {4}
..........................................->2 {4}
..........................................->3 {4}
..........................................->4 {4}
......................................................id: 7
......................................................name:Developing
......................................................code:DEV
......................................................color:#ca922d
..........................................->5 {4}
code: OK
msg:` OK

I have following working code wich puts out the members of "data"

`
// Create json string and remove \n
    string json = out.str();
    rm_nl(json); // Remove any new line \n

  
/// Start JSON parsing

    // Create DOM
    Document d;

    d.Parse(json.c_str());

    // Stringify the DOM
    StringBuffer buffer;
    Writer<StringBuffer> writer(buffer);
    d.Accept(writer);

    // Get type
    static const char* kTypeNames[] = { "Null", "False", "True", "Object", "Array", "String", "Number" };
    for (Value::ConstMemberIterator itr = d.MemberBegin();
        itr != d.MemberEnd(); ++itr)
        {
            printf("Type of member %s is %s\n",
            itr->name.GetString(), kTypeNames[itr->value.GetType()]);
        }

    // Play with members

    const Value& k = d["data"];                                                                                    // Define root
    assert(d["data"].IsObject());
    // Don't know the exact value of "root" so play using d["root"] to get access the members
    for (auto it = k.MemberBegin(); it != k.MemberEnd(); ++it) {
            {
                printf("Type of member %s is %s\n",it->name.GetString(), kTypeNames[it->value.GetType()]);

            }
`
Output of the code is

´
Type of member success is Number
Type of member data is Object
Type of member code is String
Type of member msg is String
Type of member config is Object
Type of member systems is Object
Type of member tunnels is Object
Type of member species is Object
Type of member affiliations is Object

Parsing to document succeeded.

Process returned 0 (0x0)   execution time : 2.399 s
´

So there is a point where I don't have a clue how to relize that. The provided examples are working with "flat" json data only but not nested ones.

- How can I access a member 4 underneath object/data/affiliations/resultset (there are 90 members) using rapidjson NOT using pointers?
  My understanding is that with d.Parse(json.c_str()); I have the complete DOM in d. But I can't use 
  
  ´
    const Value& k = d["species"];                                                                                    // Define root
    assert(d["data"].IsObject());
    // Don't know the exact value of "root" so play using d["root"] to get access the members
  ´
This fails then with "Assertion failed: false"

**Comment by blacksheep1970** [comment]
Just to add:

the
´´
const Value& k = d["species"]; // Define root
assert(d["data"].IsObject());
// Don't know the exact value of "root" so play using d["root"] to get access the members
´´

must be

´
´
const Value& k = d["species"]; // Define root
assert(d["species"].IsObject());
// Don't know the exact value of "root" so play using d["root"] to get access the members
´
´

of course

**Comment by AVV86** [comment]
Try to use recursion which will go deeper inside the loop(array ,objects)

       static void getKey(const Value &json) {
        for (Value::ConstMemberIterator itr = json.MemberBegin(); itr != json.MemberEnd(); itr++) {
            cout << itr->name.GetString() << endl;
            if (itr->value.GetType() == kObjectType) {

                for (Value::ConstMemberIterator itr1 = itr->value.MemberBegin();
                     itr1 != itr->value.MemberEnd(); itr1++) {

                    if (itr1->value.GetType() == kObjectType) {
                        getKey(itr1->value);
                    } else if (itr1->value.GetType() == kArrayType) {
                        for (auto itr2 = itr1->value.Begin(); itr2 != itr1->value.End(); itr2++) {

                            if (itr2->GetType() == kArrayType || itr2->GetType() == kObjectType) {

                                getKey(*(itr2));
                            }
                        }
                    }
                }
            } else if (itr->value.GetType() == kArrayType) {

                for (Value::ConstValueIterator itr1 = itr->value.Begin(); itr1 != itr->value.End(); itr1++) {
                  
                    if (itr1->GetType() == kArrayType || itr1->GetType() == kObjectType) {
                        
                        getKey(*(itr1));
                       
                    }
                }
            }
        }
    }

The json contains the parsed Json (parsed in Document and sent as parameter)  Hopefully this will solve your problem.
