### ISSUE TITLE
Is there any way of minifying/compressing output?

### ISSUE THREAD

**Issue by paulwuertz** [miloyip/rapidjson#868]
I enjoy rapidjson very much and use it to spit out some big chunk of data(~100MB) in one file.

Applying a compressor/minifier afterwards reduces file size to 18MB.
Is there a way of doing so with rapidjson natively?

I output some objects data like this:

```c++
string filename="output.json";
StringBuffer sb;
PrettyWriter<StringBuffer> writer(sb);
writer.StartArray();
for (std::vector<O_Class>::const_iterator netItr = O_Class_Array.begin();   netItr != O_Class_Array.end(); ++netItr)
    netItr->Serialize(writer);
writer.EndArray();

ofstream out;
out.open(filename);
out << sb.GetString() ;
```

Thanks!
Paul

**Comment by stervo4ka** [comment]
Try [Writer](https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/writer.h) instead of PrettyWriter.

**Comment by StilesCrisis** [comment]
I believe this issue can be closed.
