### ISSUE TITLE
Executable bit is set for various .json files

### ISSUE THREAD

**Issue by erikfroseth** [miloyip/rapidjson#875]
Hi,

Is there any reason why the executable bit is set for these files?

bin/types/booleans.json
bin/types/floats.json
bin/types/guids.json
bin/types/integers.json
bin/types/mixed.json
bin/types/nulls.json
bin/types/paragraphs.json

**Comment by erikfroseth** [comment]
I made a pull request for this (very simple fix)

**Comment by miloyip** [comment]
Fixed by your PR #876
