### ISSUE TITLE
Feature: Adding SizeType typedef to Writer

### ISSUE THREAD

**Issue by Johnnyxy** [miloyip/rapidjson#877]
Hi,
I'm working with rapidshare in a header file.
The Writer has a "Ch" typedef what is good for getting the actual char/string type.

Rapidjson offers a custom definition of the SizeType. Unfortunately I could not find a way to detemine the sizetype used by the writer, e.g. for array size.

Could it be possible to add a typedef of the underlying sizetype (like the "Ch" definition) to the writer?

Best regards

**Comment by miloyip** [comment]
`rapidjson::SizeType` is a namespace-wise defined typedef. 
It is different from `Ch` which is derived from template parameter.
You can use `rapidjson::SizeType` anywhere.

**Comment by Johnnyxy** [comment]
I'm writing a templated class that uses a rapidjson-Writer to output data. The thing is, that I can write the whole class without including any rapidjson-header.
Now if no rapidjson-header is included the namespace or the specifically the SizeType of rapidjson is not known (see the "EndArray" line in the minimal example).

This puts a constrained to my header file, that the user has to take care to include rapidjson first before including my header file. Later this could lead to problems with header inclusion order.
Like the common problems in windows with windows sockets, that "winsock2.h" has to be included before "windows.h".

But as I can see in the rapidjson code, the EndArray parameter "elementCount" is not used by rapidjson, so I can omit the array size. Therefore I can completely remove the static_cast and rapidjson::SizeType dependency.



```c++
class Abc
{
  public:
    template<typename TWriter>
    bool Write(TWriter& writer, std::vector<int> const& arr)
    {
      if (writer.StartArray())
      {       
        for (auto& element : value)
        {         
          if (!writer.Int(element)
          {
            return false;
          }
        }
        return writer.EndArray(static_cast<RAPIDJSON_NAMESPACE::SizeType>(value.size()));
      }
      else
      {
        return false;
      }
    }
};



Usage:
------
PrettyWriter<...> writer(...);
Abc<PrettyWriter<...>> abc;

abc.Write(writer, std::vector<int>{1,2,3,4,5});
`
