### ISSUE TITLE
How to pass json object from factory to server.

### ISSUE THREAD

**Issue by aadgithub** [miloyip/rapidjson#885]
When I change data from HTML it gets updated in factory.how to send this updated JSON object to server.  
My JSON object is "graphConfig".

 saveInJsonFile: function (filePath,graphConfig){
            console.log("Factory object",graphConfig.graph.nodes[0]);
            return $http({
                method: "POST",
                data: {
                    filePath: filePath,
                    graphConfig: graphConfig
                },
                url: appConfig.endPointUrl + "/api/saveInJsonFile",
                headers: {"Content-Type": "application/json"}
            }).then(function (response){
                return response.data;
            });
}

//server function 
 app.post('/api/saveInJsonFile', function (req, res) {
           var newgraphConfig = req.body.graphConfig;
           console.log("In Server",req.body.graphConfig.graph.nodes[0]);
        });

In server it takes old object.

**Comment by StilesCrisis** [comment]
Rapidjson is a C++ library. I think you posted this issue in the wrong place.
