### ISSUE TITLE
Build fails - error: ‘LookaheadParserHandler::v_’ should be initialized in the member initialization list

### ISSUE THREAD

**Issue by michaelpog** [miloyip/rapidjson#886]
Just cloned rapidjson. Followed the instructions and when I ran make I got a bunch of failures:
...
```
[  1%] Built target doc
Scanning dependencies of target pretty
[  2%] Building CXX object example/CMakeFiles/pretty.dir/pretty/pretty.cpp.o
[  4%] Linking CXX executable ../bin/pretty
[  4%] Built target pretty
Scanning dependencies of target simplewriter
[  5%] Building CXX object example/CMakeFiles/simplewriter.dir/simplewriter/simplewriter.cpp.o
[  6%] Linking CXX executable ../bin/simplewriter
[  6%] Built target simplewriter
Scanning dependencies of target lookaheadparser
[  8%] Building CXX object example/CMakeFiles/lookaheadparser.dir/lookaheadparser/lookaheadparser.cpp.o
/home/michaelpog/development/rapidjson/example/lookaheadparser/lookaheadparser.cpp: In constructor ‘LookaheadParserHandler::LookaheadParserHandler(char*)’:
/home/michaelpog/development/rapidjson/example/lookaheadparser/lookaheadparser.cpp:78:1: error: ‘LookaheadParserHandler::v_’ should be initialized in the member initialization list [-Werror=effc++]
 LookaheadParserHandler::LookaheadParserHandler(char* str) : ss_(str) {
 ^
/home/michaelpog/development/rapidjson/example/lookaheadparser/lookaheadparser.cpp:78:1: error: ‘LookaheadParserHandler::st_’ should be initialized in the member initialization list [-Werror=effc++]
/home/michaelpog/development/rapidjson/example/lookaheadparser/lookaheadparser.cpp:78:1: error: ‘LookaheadParserHandler::r_’ should be initialized in the member initialization list [-Werror=effc++]
/home/michaelpog/development/rapidjson/example/lookaheadparser/lookaheadparser.cpp: In member function ‘void LookaheadParser::SkipValue()’:
/home/michaelpog/development/rapidjson/example/lookaheadparser/lookaheadparser.cpp:226:16: error: switch missing default case [-Werror=switch-default]
         switch (st_) {
                ^
cc1plus: all warnings being treated as errors
example/CMakeFiles/lookaheadparser.dir/build.make:62: recipe for target 'example/CMakeFiles/lookaheadparser.dir/lookaheadparser/lookaheadparser.cpp.o' failed
make[2]: *** [example/CMakeFiles/lookaheadparser.dir/lookaheadparser/lookaheadparser.cpp.o] Error 1
CMakeFiles/Makefile2:1176: recipe for target 'example/CMakeFiles/lookaheadparser.dir/all' failed
make[1]: *** [example/CMakeFiles/lookaheadparser.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

My GCC version: 
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by rshanor** [comment]
Same error here

**Comment by StilesCrisis** [comment]
Clang's -Wswitch-enum actually complains if I include a default case. Is there a good way to make both GCC and Clang happy?? (Cast st_ to int?)

**Comment by StilesCrisis** [comment]
Should be addressed in PR #891. Thanks for the report.

**Comment by svml** [comment]
Please, let me know if it is expected to be resolved by now? I have just pulled master and have the same problem (gcc-6.3.0):

> 
example/lookaheadparser/lookaheadparser.cpp: In constructor 'LookaheadParserHandler::LookaheadParserHandler(char*)':
example/lookaheadparser/lookaheadparser.cpp:78:1: error: 'LookaheadParserHandler::v_' should be initialized in the member initialization list [-Werror=effc++]
 LookaheadParserHandler::LookaheadParserHandler(char* str) : ss_(str) {
 ^~~~~~~~~~~~~~~~~~~~~~
example/lookaheadparser/lookaheadparser.cpp:78:1: error: 'LookaheadParserHandler::st_' should be initialized in the member initialization list [-Werror=effc++]
example/lookaheadparser/lookaheadparser.cpp:78:1: error: 'LookaheadParserHandler::r_' should be initialized in the member initialization list [-Werror=effc++]
example/lookaheadparser/lookaheadparser.cpp: In member function 'void LookaheadParser::SkipValue()':
example/lookaheadparser/lookaheadparser.cpp:226:16: error: switch missing default case [-Werror=switch-default]
         switch (st_) {
                ^
cc1plus: all warnings being treated as errors
gmake[2]: *** [example/CMakeFiles/lookaheadparser.dir/lookaheadparser/lookaheadparser.cpp.o] Error 1
gmake[1]: *** [example/CMakeFiles/lookaheadparser.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by StilesCrisis** [comment]
The author (Milo Yip) hasn't merged the pull request yet. Wait for PR #891 to reach "closed" state.
