### ISSUE TITLE
UTF8 encoding decoding

### ISSUE THREAD

**Issue by comtrexbrian** [miloyip/rapidjson#887]
Rapidjson is a great product. It really makes json handling very simple to code. We love it.
The only problem we are having is that we have to manually utf8 encode using other software after the json is created, and decode the incoming json with other software prior to parsing with document.  Our json packets frequently have 0xA3 uk pound signs so utf8 encoding is necessary.
We are using MBCS in a windows app and our buffers are BYTEs, not unicode. We have tried both UTF8 and ASCII for in and out parameters but nothing seems to work.  
Is there a way to make rapidjson handle the utf8?
Thanks
Brian

**Comment by StilesCrisis** [comment]
Almost all Rapidjson classes have an "Encoding" template parameter which controls the character encoding. By default this parameter is set to UTF8 but you can change it as needed.

Take a look at Encodings.h and see how "UTF8" and "UTF16" classes are implemented. You could very easily create a "MBCS" encoding class which implements the required methods. If you do not require transcoding into other encodings, the methods could be extremely simple (just leave the character unchanged). If you want it to support transcoding to Unicode, you would just need to add in a small MBCS<->Unicode mapping table.

**Comment by comtrexbrian** [comment]
Thanks for the tip. I was hoping some way was already built in.  I will take your advise and copy the UTF8 encoding/decoding into my own class. Seems existing UTF8 will not encode unless you are passing unicode. We are strictly bytes (MBCS). Tried ASCII but it issues a protection fault if you pass anything greater than 0x7f.  Thanks again.

**Comment by miloyip** [comment]
Yes. Currently RapidJSON only supports Unicode encodings, as this is specified in [JSON RFC](https://tools.ietf.org/html/rfc7159). 

> A string is a sequence of zero or more Unicode characters [UNICODE].
   Note that this citation references the latest version of Unicode
   rather than a specific release.  It is not expected that future
   changes in the UNICODE specification will impact the syntax of JSON.

I have no plan to add support for MBCS as there are quite a lot of encodings for MBCS and require large tables for so.

**Comment by comtrexbrian** [comment]
Thanks for that. We will work around it.
