### ISSUE TITLE
Issues about auto-sized by temple

### ISSUE THREAD

**Issue by harrywong** [miloyip/rapidjson#889]
I found an issue when updating rapidjson to the latest version. I found there's some issue about the auto-sized template updates.

I have a struct has a char[16] field. When the text is 'abcdefg\0', in the previous rapdjson can handle it using the strlen() method, while will wirte abcdefg in the json. In the new version, it will write all the \0 to the end of string, which is not the same behavior as the old version.

One workaround is to call strlen myself in the program.

**Comment by StilesCrisis** [comment]
Hmm, OK. I'll revert that change.

**Comment by StilesCrisis** [comment]
OK, Pull Request #890 fixes the issue by reverting the change, and includes a unit test which confirms your findings. Sorry about this!

**Comment by harrywong** [comment]
Thanks very much!

**Comment by StilesCrisis** [comment]
Just realized I forgot to address the same bug in PrettyWriter. Added PR #897 to handle this.
