### ISSUE TITLE
BUG - patternProperties check crashes the program

### ISSUE THREAD

**Issue by SollyTaylor** [miloyip/rapidjson#898]
target object:

```
{
	"tree" : {
		"vehicle" : {}
	}
}
```

using the schema:

```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type" : "object",
	"properties" : {
		"tree" : {
			"type" : "object",
			"patternProperties" : {
				"^[a-zA-Z][a-zA-Z0-9_]*$" : {
					"type" : "object"
				}
			},
  			"additionalProperties" : false
		}
	}
}
```

using the schema check the target object, crashes the application. Error elaborated as:

> Assertion Failed!
> Program: ......
> File:  ...      schema.h
> Line: 1844
> Expression: CurrentContext().valueSchema
> 
> For more information on how your program can cause an assertion failure, see Visual C++ documentation on asserts
> 
> (Press Retry to debug the application - JIT must be enabled)

Would you please help me out on this, I've been sticking here for quite a while.

**Comment by miloyip** [comment]
I am unable to reproduce the issue:

~~~cpp
TEST(SchemaValidator, Issue898_PatternPropertiesCrash) {
    Document sd;
    sd.Parse("{ \"tree\" : {\"vehicle\" : {} } }");
    SchemaDocument s(sd);
    VALIDATE(s, "{\"$schema\": \"http://json-schema.org/draft-04/schema#\", \"type\" : \"object\", \"properties\" : {\"tree\" : {\"type\" : \"object\", \"patternProperties\" : {\"^[a-zA-Z][a-zA-Z0-9_]*$\" : {\"type\" : \"object\"} }, \"additionalProperties\" : false } } }", true);
}
~~~

**Comment by SollyTaylor** [comment]
temporarily, I cannot reproduce the error either, I'll reheat this issue once I feel it's necessary.
