### ISSUE TITLE
How to erase an object in objects array

### ISSUE THREAD

**Issue by eanon** [miloyip/rapidjson#908]
Hello,

Say I have something like :
`{
	"items": [{
			"name": "Pink",
			"level": "10"
		}, {
			"name": "Blue",
			"level": "20"
		}
	]
}`

How do I delete the first object {"name": "Pink", "level": "10"} in the "items" array?

**Comment by miloyip** [comment]
~~~cpp
Value& items = doc["items"];
items.Erase(items.Begin());
~~~

**Comment by eanon** [comment]
Thanks Milo, I was a little in confusion between Erase and EraseMember (or, rather, didn't noticed one was for array and the other for object).

Well, here is my final real code (if it can help someone a day) in context (variants without associated image are stripped out) :

`        Value& variants = pdt["variants"];
        for (int idx = 0 ; idx < (int) variants.Size() ; idx++)
        {   
            if (!variants[idx].HasMember("image_id")){
                variants.Erase(variants.Begin() + idx--);}
        }
`

NB: The loop contains a lot more and was initially build around iterated index rather than dedicated RapidJSON iterator, because I don't only manage JSON in this loop -- but matching arrays and list controls beside too.

**Comment by Phunkafizer** [comment]
How does this work using range-based for loops?

```
for (auto &it: data.GetArray()) {
		if (it["test"] == 1) {
			data.Erase(it); //does not compile
			break;
		}
	}
```

**Comment by maheshmns** [comment]
How do i find an object in an array and delete it? Erase seems to only take an iterator and I couldnt find documentation on how to find an object in an array.

**Comment by foxguy75** [comment]
For ranged based for loop with `auto`

```C++
for( const auto& it : data.GetArray() )
{
    auto itemToDelete = it.FindMember( "test" );

    if( itemToDelete != it.MemberEnd() && itemToDelete->value == 1) 
    {
        data.Erase( &it );
    }
}
```
For ranged based for loop without `auto`
```C++
for( const rapidjson::Value& it : data.GetArray() )
{
    rapidjson::GenericValueIterator itemToDelete = it.FindMember( "test" );

    if( itemToDelete != it.MemberEnd() && itemToDelete->value == 1) 
    {
        data.Erase( &it );
    }
}
````
