### ISSUE TITLE
some gcc versions generate wrong warnings

### ISSUE THREAD

**Issue by yrxwin** [miloyip/rapidjson#922]
when I compile with gcc 4.8.4, I will encountered the following warning, would there be anyway to avoid this? Thanks!
```
 warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
RAPIDJSON_DIAG_OFF(array - bounds)  // some gcc versions generate wrong warnings
```

**Comment by Bu11etmagnet** [comment]
You should write `RAPIDJSON_DIAG_OFF(array-bounds)` instead of `RAPIDJSON_DIAG_OFF(array - bounds)`. (Note the spaces; they are causing the problem).

**Comment by yrxwin** [comment]
@Bu11etmagnet Thanks! But why the source codes have the space? Could we remove the space in source code?

**Comment by miloyip** [comment]
I cannot find files with such spaces. Can you mention which file(s) has problem?

**Comment by yrxwin** [comment]
When I switch the flag from `c++0x` to `c++11`, the warning disappears. I will close this issue.
