### ISSUE TITLE
How to update array in object

### ISSUE THREAD

**Issue by yrxwin** [miloyip/rapidjson#934]
I have an object with several arrays. Is there any way to append an element to a certain array in place (without remove and add element). Thanks

**Comment by miloyip** [comment]
Just using `=`.

**Comment by miloyip** [comment]
I don't know if you mean`a[i] = v;`. This is supported. Not that this assignment is with move semantics.

**Comment by yrxwin** [comment]
Thanks for the fast response! I found out that the reason that I could not do that previously is that I used the `ConstMemberIterator` as the tutorial mentioned, but if we want to change it, should use `MemberIterator` :)
