### ISSUE TITLE
中文帮助文档转移语义示例疑似有问题

### ISSUE THREAD

**Issue by kk5171** [miloyip/rapidjson#943]
http://rapidjson.org/zh-cn/md_doc_tutorial_8zh-cn.html#MoveSemantics
转移和非转移的实例看起来都是相同的代码，区别在哪里？
Value o(kObjectType);
{
    Value contacts(kArrayType);
    // 把元素加进 contacts 数组。
    // ...
    o.AddMember("contacts", contacts, d.GetAllocator());  // 深度复制 contacts （可能有大量内存分配）
    // 析构 contacts。
}

Value o(kObjectType);
{
    Value contacts(kArrayType);
    // adding elements to contacts array.
    o.AddMember("contacts", contacts, d.GetAllocator());  // 只需 memcpy() contacts 本身至新成员的 Value（16 字节）
    // contacts 在这里变成 Null。它的析构是平凡的。
}

**Comment by miloyip** [comment]
前段是假设如果用了 copy 语意所做成的问题。代码是一样的。

**Comment by kk5171** [comment]
代码相同的情况下，如何知道是实际做了copy还是转移？

**Comment by miloyip** [comment]
是按实现决定的。
就像以前 `std::auto_ptr<T>` 转移所有权。
