### ISSUE TITLE
Beginner question: Error: “User needs to define RAPIDJSON_ENDIAN” when following rapidJSON tutorial 

### ISSUE THREAD

**Issue by myo3** [miloyip/rapidjson#953]
I'm just trying to test out `rapidjson` `simpledom.cpp` example [that was displayed on their website][1], however when I try to complie it I get the error:
```
compiling simpledom.cpp...
    .\rapidjson/rapidjson.h(249): error:  #35: #error directive: Unknown machine endianess detected. User needs to define RAPIDJSON_ENDIAN.   
      #    error Unknown machine endianess detected. User needs to define RAPIDJSON_ENDIAN.
```
I'm also getting the following error on line `#include "rapidjson/document.h"`:

    error in include chain (encodings.h): expected parameter declarator
    error in include chain (encodedstream.h): expected parameter declaratory

And I'm not too familiar with C++ so looking at `encodings.h` and `encodedstream.h` does not enlighten me on what I need to do to run the simple example.

I feel that this tutorial `simpledom.cpp` is really simple, and I literally copied and pasted, so I don't understand what I could be doing wrong.

If anyone could advise me on what I'm doing wrong that would be great!

## Code
**Info:**

- using `uVision`

**simpledom.cpp**

    // JSON simple example
    // This example does not handle errors.
    
    #include "rapidjson/document.h"
    #include "rapidjson/writer.h"
    #include "rapidjson/stringbuffer.h"
    #include <iostream>
    
    using namespace rapidjson;
    
    int main() {
        // 1. Parse a JSON string into DOM.
        const char* json = "{\"project\":\"rapidjson\",\"stars\":10}";
        Document d;
        d.Parse(json);
    
        // 2. Modify it by DOM.
        Value& s = d["stars"];
        s.SetInt(s.GetInt() + 1);
    
        // 3. Stringify the DOM
        StringBuffer buffer;
        Writer<StringBuffer> writer(buffer);
        d.Accept(writer);
    
        // Output {"project":"rapidjson","stars":11}
        std::cout << buffer.GetString() << std::endl;
        return 0;
    }

  [1]: http://rapidjson.org/

**Comment by miloyip** [comment]
Please provide your compiler/platform information.

**Comment by myo3** [comment]
On the build output on `uVision` it says `*** Using Compiler 'V5.06 update 4 (build 422)', folder: 'C:\Keil_v5\ARM\ARMCC\Bin'`. Is that what you're looking for?

**Comment by miloyip** [comment]
Sorry I don't know about uVision. From the above message it seems the compiler is for ARM CPU.
I am not sure which endianness does the toolchain use. After checking that, you should add `RAPIDJSON_ENDIAN=RAPIDJSON_LITTLEENDIAN` or `RAPIDJSON_ENDIAN=RAPIDJSON_BIGENDIAN` as pre-defined macro.
You may consult others who know about uVision.

**Comment by myo3** [comment]
Thanks for your help. I got it not to produce the error by doing `#define RAPIDJSON_ENDIAN RAPIDJSON_LITTLEENDIAN` in `rapidjson.h`. But turns out my board is too small to fit the entire library, which is unfortunate so I will be on the hunt for another json parser compatible for the `ARM` compiler 🙃 Thanks for the reply!

**Comment by miloyip** [comment]
How much memory does your board have?

**Comment by myo3** [comment]
1 MB flash memory, 256 KB RAM

It's the [NXP FRDM-K64F board](http://www.nxp.com/products/software-and-tools/hardware-development-tools/freedom-development-boards/freedom-development-platform-for-kinetis-k64-k63-and-k24-mcus:FRDM-K64F#featuresExpand)

**Comment by miloyip** [comment]
That seems sufficient.
From [this stats](https://github.com/miloyip/nativejson-benchmark#code-size), the program of parsing a JSON is only about 31KB on Mac/x64.

**Comment by myo3** [comment]
Thanks to you I tried compiling on https://developer.mbed.org/compiler/, got the `*.bin` file and manually installed that on my board and now it works! =D It must be smtg about `uVision` that doesn't like compiling the `rapidjson` files for some reason, and I've always had problems with `uVision` so this is expected. Thanks so much! 

PS: I will probably be back pestering you with questions ^^; b/c this project is due on Thursday and me n my partner have a long way to go (Sigh... iOS development is so much simpler in the compilation process but what can you do when you're required to use the board ¯\_(ツ)_/¯) Thanks for being active on Git issues 🙃
