### ISSUE TITLE
allocator的使用方法

### ISSUE THREAD

**Issue by kk5171** [miloyip/rapidjson#966]
对rapidjson中的allocator的用法有点疑惑

http://rapidjson.org/zh-cn/md_doc_dom_8zh-cn.html#Allocator

>  GenericDocument 的缺省分配器是 MemoryPoolAllocator。此分配器实际上会顺序地分配内存，并且不能逐一释放。当要解析一个 JSON 并生成 DOM，这种分配器是非常合适的。
> RapidJSON 还提供另一个分配器 CrtAllocator，当中 CRT 是 C 运行库（C RunTime library）的缩写。此分配器简单地读用标准的 malloc()/realloc()/free()。当我们需要许多增减操作，这种分配器会更为适合。然而这种分配器远远比 MemoryPoolAllocator 低效。

如果Document对象使用了MemoryPoolAllocator：

1. 如何释放其申请的内存？是使用MemoryPoolAllocator::Clear()方法么？
2. 如果json解析成DOM后，需要经常添加、修改成员，MemoryPoolAllocator和CrtAllocator哪个会更高效？
3. 为什么说当我们需要许多增减操作，CrtAllocator会更为适合？

非常感谢！

**Comment by miloyip** [comment]
1. 可以。但如果之前还有引用到那些内存就会 dangling pointer。
2. 性能是 `MemoryPoolAllocator` 高，但不断分配会一直增加内存。如果一个 `Document` 修改很多次后，可考虑把它复制至另一 `Document`，那就像 `vector::shrink_to_fit()`。
3. 如果不做 2 的话，heap 内存会一直增加。

**Comment by kk5171** [comment]
谢谢 @miloyip ，我研究一下

**Comment by kk5171** [comment]
@miloyip 请教为什么GenericValue的析构函数没有真正执行？有什么特殊的考虑？
```
    //! Destructor.
    /*! Need to destruct elements of array, members of object, or copy-string.
    */
    ~GenericValue() {
        if (false/*Allocator::kNeedFree*/) { // Shortcut by Allocator's trait
            switch (flags_) {
            case kArrayFlag:
                for (GenericValue* v = data_.a.elements; v != data_.a.elements + data_.a.size; ++v)
                    v->~GenericValue();
                Allocator::Free(data_.a.elements);
                break;

            case kObjectFlag:
                for (MemberIterator m = MemberBegin(); m != MemberEnd(); ++m)
                    m->~Member();
                Allocator::Free(data_.o.members);
                break;

            case kCopyStringFlag:
                Allocator::Free(const_cast<Ch*>(data_.s.str));
                break;

            default:
                break;  // Do nothing for other types.
            }
        }
    }
```

**Comment by miloyip** [comment]
那样便不用递归所有节点，而每个节点都不做事情。

**Comment by kk5171** [comment]
明白了，感谢！

**Comment by wangdahao** [comment]
请问怎么才能copy一个document呢？
