### ISSUE TITLE
Documentation links dont work

### ISSUE THREAD

**Issue by TimDykes** [miloyip/rapidjson#974]
The links in various documentation files lead to 404, due to extra `/doc` in the address, e.g all the links in the WhatsNext section at the bottom of [doc/tutorial.md](https://github.com/miloyip/rapidjson/blob/master/doc/tutorial.md)

**Comment by miloyip** [comment]
It needs to be this form, in order to work with Doxygen. The generated [HTML](http://rapidjson.org/md_doc_tutorial.html) works.

**Comment by TimDykes** [comment]
Oh right I see, I found rapidjson via a link to the github and was browsing the md files directly, I didnt realise there was a prebuilt version of the docs on the website! Thanks I'll close this.
