### ISSUE TITLE
Using Value crashes

### ISSUE THREAD

**Issue by zammbi** [miloyip/rapidjson#976]
I have created a helper method that parses a block of json and returns a `Value`. But the library asserts fail if I try to use the returned value. E.g  fails on `RAPIDJSON_ASSERT(m->name.IsString());`

This is the code
```
static Value parseJson(const char *json) {
    Document doc;
    doc.Parse(json);
    return doc.GetArray(); //Always an array.
}
...
auto parsedJson = parseJson(jsonToParse);
```

Is that how should I be getting the Value? If not how?

**Comment by miloyip** [comment]
You should return `Document` instead. Because `Document` holds the allocator (memory with the parsing result).

**Comment by zammbi** [comment]
Ah right, to me documentation wasn't clear that you couldn't do this. But I've found a way to store the `Document` (as a shared_ptr) and still pass around `Value`.
Thanks for your help.
