### ISSUE TITLE
Writing to Value is verbose

### ISSUE THREAD

**Issue by zammbi** [miloyip/rapidjson#980]
I've been slowly converting a codebase over to rapidjson. 

My old code used to be:
```
void Class::addJson(Value& v) const {
v[Interface::JSON_KEY] = getStringData();
}
```
Now its: 
```
void Class::addJson(Value& v, Value::AllocatorType& allocator) const {
Value key(Interface::JSON_KEY, allocator);
Value object(getStringData(), allocator);
v.AddMember(key, object, allocator);
}
```

Is there a shorter way? Otherwise another helper method :)

**Comment by zammbi** [comment]
Created a little helper method:
```
void Class::addString(Value& v, Value::AllocatorType& allocator, const std::string & key, const std::string & object) {
	Value keyValue(key, allocator);
	Value objectValue(object, allocator);
	v.AddMember(keyValue, objectValue, allocator);
}
```

**Comment by miloyip** [comment]
May be written as a single line:

~~~cpp
v.AddMember(Value(key, allocator).Move(), Value(object, allocator).Move(), allocator);
~~~

**Comment by pah** [comment]
Biggest question would be: What's the type/semantics of `Interface::JSON_KEY`?

Assuming that this is a global constant, you can avoid copying this string into the JSON and only reference it instead, see [`StringRef()`](http://rapidjson.org/structrapidjson_1_1_generic_string_ref.html#aa6b9fd9f6aa49405a574c362ba9af6b5):

```cpp
  v.AddMember( StringRef(Interface::JSON_KEY), Value(object, allocator).Move(), allocator );
```

In C++11, you don't need the call to `Move()` anymore.

**Comment by zammbi** [comment]
"May be written as a single line"
Yeah, I know. Still verbose. Just wondering if there was any shorter way. I'll just stick with my helper method. 

"What's the type/semantics of Interface::JSON_KEY?"
It's just a `static const std::string`.

**Comment by pah** [comment]
> Yeah, I know. Still verbose. Just wondering if there was any shorter way. I'll just stick with my helper method.

In your special case (`object` is a `std::string`), you should then be able to use
```cpp
  v.AddMember( StringRef(Interface::JSON_KEY), object, allocator );
```
see [this `AddMember` overload](http://rapidjson.org/classrapidjson_1_1_generic_value.html#ab018d734d189532b27943bc45776ba68), combined with the templated overload taking a `StringRefType` as name.

**Comment by zammbi** [comment]
Great that works.
