### ISSUE TITLE
Doxygen rendering of doc/internals.md broken on rapidjson.org

### ISSUE THREAD

**Issue by pah** [miloyip/rapidjson#993]
Looking at the rendered version of [`doc/internals.md`](https://github.com/miloyip/rapidjson/blob/master/doc/internals.md) at rapidjson.org, it seems that everything starting from the `Allocator` section is missing in the generated page. 

The `Allocator` section is missing entirely, while the others are still referenced in the ToC but are not present in the page at http://rapidjson.org/md_doc_internals.html.

**Comment by miloyip** [comment]
It is strange that I `make doc` locally the output is correct.
The problem may be related to `.travis.yml` and `travis-doxygen.sh`.
