### ISSUE TITLE
Is it possible to get current stream position when processing SAX events?

### ISSUE THREAD

**Issue by dsorber** [miloyip/rapidjson#997]
Is it possible to get current stream position when processing SAX events?  The only similar thing I can find is ParseResult.Offset() but that looks to be available only on a parse error.

For example, when StartObject and EndObject occur, I would like to know where in the input stream they occur.

**Comment by StilesCrisis** [comment]
You can inspect the stream object that you passed in for parsing.
(If you just passed a plain string, that's being wrapped by a stream object behind your back.)

**Comment by miloyip** [comment]
http://rapidjson.org/md_doc_stream.html#CustomStream
~~~cpp
concept Stream {
    // ...
    //! Get the current read cursor.
    //! \return Number of characters read from start.
    size_t Tell();
    // ...
}
~~~

All streams implement this concept, so you can use `Tell()` to get the read cursor. But you need to pass the reference of the stream to the handler before parsing.

**Comment by dsorber** [comment]
Oh, I see. Thanks for the clarification.
